### ISSUE TITLE
The exporter missing all metrics after upgrade to rook1.11.4

### ISSUE THREAD

**Issue by JefferyLJ** [rook/rook#12131]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
```
ubuntu60# kubectl exec -it  rook-ceph-exporter-ubuntu60-6cd5d4f765-n664m -n rook-ceph -- /bin/bash
sh-4.4# curl 127.0.0.1:9926/metrics
# HELP ceph_exporter_scrape_time Time spent scraping and transforming perfcounters to metrics
# TYPE ceph_exporter_scrape_time gauge
ceph_exporter_scrape_time{function="dump_asok_metrics",host="ubuntu60"} 71.324594
sh-4.4#
```
<img width="941" alt="image" src="https://user-images.githubusercontent.com/46212828/233920375-46a33853-47e3-44cc-acbb-3c0b4d9c60a6.png">

## ceph cluster
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/46212828/233919693-d81a9b9c-8a5d-47b1-8956-f73401c76a44.png">

## ceph pools
<img width="1355" alt="image" src="https://user-images.githubusercontent.com/46212828/233919920-f8bcfd9f-5d95-4a6f-a189-0e96c07ac121.png">

## ceph - OSD (Single)
<img width="1359" alt="image" src="https://user-images.githubusercontent.com/46212828/233920123-7a1cfe62-bfea-4de6-94b0-d8d6d778b551.png">

**Expected behavior:**
get all metrics

**How to reproduce it (minimal and precise):**

Upgrade from rook1.11.1 to rook1.11.4

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
cluster:
    id:     eea65e73-6ff7-4634-9f77-5acd9b7c0990
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum a,b,d (age 4w)
    mgr: b(active, since 29m), standbys: a
    mds: 1/1 daemons up, 1 hot standby
    osd: 12 osds: 12 up (since 4d), 12 in (since 7w)

  data:
    volumes: 1/1 healthy
    pools:   4 pools, 81 pgs
    objects: 146.79k objects, 526 GiB
    usage:   1.5 TiB used, 42 TiB / 44 TiB avail
    pgs:     81 active+clean

  io:
    client:   5.1 MiB/s rd, 3.7 MiB/s wr, 89 op/s rd, 160 op/s wr

  To get the status of the cluster, use `kubectl rook-ceph ceph status`
cluster:
    id:     eea65e73-6ff7-4634-9f77-5acd9b7c0990
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum a,b,d (age 4w)
    mgr: b(active, since 30m), standbys: a
    mds: 1/1 daemons up, 1 hot standby
    osd: 12 osds: 12 up (since 4d), 12 in (since 7w)

  data:
    volumes: 1/1 healthy
    pools:   4 pools, 81 pgs
    objects: 146.79k objects, 526 GiB
    usage:   1.5 TiB used, 42 TiB / 44 TiB avail
    pgs:     81 active+clean

  io:
    client:   7.1 MiB/s rd, 4.0 MiB/s wr, 133 op/s rd, 161 op/s wr
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
Linux ubuntu60 5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
rook: v1.11.4
go: go1.19.8

* Storage backend version (e.g. for ceph do `ceph -v`):
quay.io/ceph/ceph:v17.2.5

* Kubernetes version (use `kubectl version`):
Client Version: v1.24.9
Kustomize Version: v4.5.4
Server Version: v1.24.9

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by JefferyLJ** [comment]
The version of rook-ceph-exporter is old and not updated?  （rook-version: v1.11.1）

```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: rook-ceph-exporter-ubuntu60
  namespace: rook-ceph
  labels:
    app: rook-ceph-exporter
    ceph-version: 17.2.5-0
    kubernetes.io/hostname: ubuntu60
    node_name: ubuntu60
    rook-version: v1.11.1
  annotations:
    deployment.kubernetes.io/revision: '3'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rook-ceph-exporter
      kubernetes.io/hostname: ubuntu60
      node_name: ubuntu60
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rook-ceph-exporter
        ceph-version: 17.2.5-0
        kubernetes.io/hostname: ubuntu60
        node_name: ubuntu60
        rook-version: v1.11.1
      annotations:
        kubectl.kubernetes.io/restartedAt: '2023-03-24T18:34:27+08:00'
        kubesphere.io/restartedAt: '2023-04-24T01:32:51.691Z'
        prometheus.io/port: '9926'
        prometheus.io/scrape: 'true'
    spec:
      volumes:
        - name: rook-config-override
          projected:
            sources:
              - configMap:
                  name: rook-config-override
                  items:
                    - key: config
                      path: ceph.conf
                      mode: 292
            defaultMode: 420
        - name: ceph-daemons-sock-dir
          hostPath:
            path: /var/lib/rook/exporter
            type: DirectoryOrCreate
        - name: rook-ceph-log
          hostPath:
            path: /var/lib/rook/rook-ceph/log
            type: ''
        - name: rook-ceph-crash
          hostPath:
            path: /var/lib/rook/rook-ceph/crash
            type: ''
        - name: ceph-conf-dir
          hostPath:
            path: /var/lib/rook/rook-ceph
            type: Directory
        - name: rook-ceph-admin-keyring
          secret:
            secretName: rook-ceph-admin-keyring
            defaultMode: 420
      initContainers:
        - name: chown-container-data-dir
          image: 'quay.io/ceph/ceph:v17.2.5'
          command:
            - chown
          args:
            - '--verbose'
            - '--recursive'
            - 'ceph:ceph'
            - /var/log/ceph
            - /var/lib/ceph/crash
            - /run/ceph
          resources: {}
          volumeMounts:
            - name: rook-config-override
              readOnly: true
              mountPath: /etc/ceph
            - name: ceph-daemons-sock-dir
              mountPath: /run/ceph
            - name: rook-ceph-log
              mountPath: /var/log/ceph
            - name: rook-ceph-crash
              mountPath: /var/lib/ceph/crash
            - name: ceph-conf-dir
              mountPath: /var/lib/rook/rook-ceph
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
      containers:
        - name: ceph-exporter
          image: 'quay.io/ceph/ceph:v17.2.5'
          command:
            - ceph-exporter
          args:
            - '--sock-dir'
            - /run/ceph
            - '--port'
            - '9926'
            - '--prio-limit'
            - '5'
            - '--stats-period'
            - '5'
          env:
            - name: CONTAINER_IMAGE
              value: 'quay.io/ceph/ceph:v17.2.5'
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: POD_MEMORY_LIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
                  divisor: '0'
            - name: POD_MEMORY_REQUEST
              valueFrom:
                resourceFieldRef:
                  resource: requests.memory
                  divisor: '0'
            - name: POD_CPU_LIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
                  divisor: '1'
            - name: POD_CPU_REQUEST
              valueFrom:
                resourceFieldRef:
                  resource: requests.cpu
                  divisor: '0'
            - name: CEPH_USE_RANDOM_NONCE
              value: 'true'
            - name: ROOK_CEPH_MON_HOST
              valueFrom:
                secretKeyRef:
                  name: rook-ceph-config
                  key: mon_host
            - name: ROOK_CEPH_MON_INITIAL_MEMBERS
              valueFrom:
                secretKeyRef:
                  name: rook-ceph-config
                  key: mon_initial_members
            - name: CEPH_ARGS
              value: >-
                -m $(ROOK_CEPH_MON_HOST) -k
                /etc/ceph/admin-keyring-store/keyring
          resources: {}
          volumeMounts:
            - name: rook-config-override
              readOnly: true
              mountPath: /etc/ceph
            - name: ceph-daemons-sock-dir
              mountPath: /run/ceph
            - name: rook-ceph-log
              mountPath: /var/log/ceph
            - name: rook-ceph-crash
              mountPath: /var/lib/ceph/crash
            - name: rook-ceph-admin-keyring
              readOnly: true
              mountPath: /etc/ceph/admin-keyring-store/
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: ubuntu60
      securityContext: {}
      schedulerName: default-scheduler
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 300
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
```

**Comment by JefferyLJ** [comment]
After the following steps, it is now back to normal
1. kubectl replace -f common.yaml -f crds.yaml
2. Restart the rook-ceph-operator pod

**Comment by parth-gr** [comment]
I think the upgrade wasn't successful

The ceph exporter would be disabled for next version release because of regression
https://github.com/rook/rook/pull/12118
@avanthakkar any more insights you need to add?

**Comment by jrcichra** [comment]
I'm seeing the same / similar issue. After upgrading from v1.11.3 -> v1.11.4, I am not longer getting ceph metrics in prometheus.

Switching back to v1.11.3 did not fix the metrics.

In my case, I don't have any special prometheus deployments for rook. Instead, I believe the prometheus metrics I was getting were coming from the mgrs. According to prometheus targets those are now returning "connection refused":
![Screenshot from 2023-04-29 02-09-01](https://user-images.githubusercontent.com/1342149/235287259-cf23d7df-bbc5-449f-a710-b4dcc34a7676.png)

I've always had the `monitoring` setting set to false but still got prometheus metrics from the mgrs.

``` 
monitoring:
    # requires Prometheus to be pre-installed
    enabled: false
```

Enabling this gave me some errors which stopped the reconcile, but I might be missing some CRDs? I have prometheus deployed separately as a helm chart (no prometheus CRDs, it discovers targets via annotations):
```
rook-ceph-operator-79bd599967-b8dk4 rook-ceph-operator 2023-04-29 06:26:15.742036 E | ceph-nodedaemon-controller: node reconcile failed: failed to enable service monitor: service monitor could not be enabled: failed to retrieve servicemonitor. servicemonitors.monitoring.coreos.com "rook-ceph-exporter" is forbidden: User "system:serviceaccount:rook-ceph:rook-ceph-system" cannot get resource "servicemonitors" in API group "monitoring.coreos.com" in the namespace "rook-ceph"
```

It seems that the legacy mgr prometheus metrics may have been disabled in the last patch?

**Comment by travisn** [comment]
@avanthakkar This would this be fixed by #12118, right? 
@jrcichra We are planning the next rook release in the next day or two with that fix. In the meantime, could you test in the interim release build will work for you? `rook/ceph:v1.11.4-13.gabe5cd7d5`

**Comment by jrcichra** [comment]
@travisn no luck with `rook/ceph:v1.11.4-13.gabe5cd7d5` on the operator.  It did roll the mgr pods, but was still seeing connection refused on the mgr prometheus targets.

However, I was able to run `ceph mgr module enable prometheus` in the toolbox and am getting metrics again.

**Comment by avanthakkar** [comment]
> @travisn no luck with `rook/ceph:v1.11.4-13.gabe5cd7d5` on the operator. It did roll the mgr pods, but was still seeing connection refused on the mgr prometheus targets.
> 
Did u enabled monitoring in ceph cluster CR? Basically with that option enabled,  the prometheus mgr module is enabled.
> However, I was able to run `ceph mgr module enable prometheus` in the toolbox and am getting metrics again.

**Comment by avanthakkar** [comment]
> @avanthakkar This would this be fixed by #12118, right? @jrcichra We are planning the next rook release in the next day or two with that fix. In the meantime, could you test in the interim release build will work for you? `rook/ceph:v1.11.4-13.gabe5cd7d5`

Yes that's the fix.

**Comment by avanthakkar** [comment]
> 

Yes for now it's disabled and will be enabled once the ceph changes for main branch are backported to reef or maybe the next quincy dot release.

**Comment by avanthakkar** [comment]
> I think the upgrade wasn't successful
> 
> The ceph exporter would be disabled for next version release because of regression #12118 @avanthakkar any more insights you need to add?

Yes for now it's disabled and will be enabled once the ceph changes for main branch are backported to reef or maybe the next quincy dot release.

**Comment by travisn** [comment]
> @travisn no luck with `rook/ceph:v1.11.4-13.gabe5cd7d5` on the operator. It did roll the mgr pods, but was still seeing connection refused on the mgr prometheus targets.
> 
> However, I was able to run `ceph mgr module enable prometheus` in the toolbox and am getting metrics again.

Ah, if you were able to enable the prometheus module to get it working again, this sounds more like #12097. As Avan said, setting `monitring.enabled: true` in the cephcluster CR is the fix, but if you don't want that enabled, we should discuss more on #12097.

**Comment by jrcichra** [comment]
Thanks. That's the issue I'm hitting. I'll continue the conversation there. Thanks.
