### ISSUE TITLE
multus-cluster-network canary test is failing consistently

### ISSUE THREAD

**Issue by travisn** [rook/rook#12670]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The multus test is failing consistently. The OSDs are not starting properly.

The OSDs are not coming `in`, so the test is stuck on the "waiting for ceph to be ready" step.
```
  services:
    mon: 1 daemons, quorum a (age 9m)
    mgr: a(active, since 6m)
    mds: 0/0 daemons up
    osd: 2 osds: 0 up, 2 in (since 7m)
 ```

Looking at an OSD pod log from the multus test, it shows:
```
debug 2023-08-03T14:28:18.158+0000 7f236496e540 -1 unable to find any IPv4 address in networks '192.168.20.0/24' interfaces ''
debug 2023-08-03T14:28:18.158+0000 7f236496e540 -1 Failed to pick public address.
```

See attached for full log.
[logs--rook-ceph-osd-0-7ccf99675d-lq2fx.txt](https://github.com/rook/rook/files/12262267/logs--rook-ceph-osd-0-7ccf99675d-lq2fx.txt)

**Expected behavior:**
Tests should pass consistently.

**How to reproduce it (minimal and precise):**

Look at the Canary integration tests: https://github.com/rook/rook/actions/workflows/canary-integration-test.yml?query=branch%3Amaster

**Comment by travisn** [comment]
The multus test started failing consistently two weeks ago when other tests started failing as well.

The errors about OSDs not being up and in is just from the tests in the past day. Previously to that, looks like it was more of a network config that was failing such as in [this test](https://github.com/rook/rook/actions/runs/5741128966/job/15560540468):
```
+ echo 'verifying csi holder interfaces (multus ones must be present)'
+ kubectl -n rook-ceph exec -t ds/csi-rbdplugin-holder-my-cluster -- grep net /proc/net/dev
command terminated with exit code 1
+ kubectl -n rook-ceph exec -t ds/csi-cephfsplugin-holder-my-cluster -- grep net /proc/net/dev
command terminated with exit code 1
+ kubectl -n rook-ceph exec -t ds/csi-nfsplugin-holder-my-cluster -- grep net /proc/net/dev
command terminated with exit code 1
Error: Process completed with exit code 1.
```
Perhaps github actions fixed some network issue, since that error went away now, but it still leaves the OSDs not able to communicate.

**Comment by subhamkrai** [comment]
> The multus test started failing consistently two weeks ago when other tests started failing as well.
> 
> The errors about OSDs not being up and in is just from the tests in the past day. Previously to that, looks like it was more of a network config that was failing such as in [this test](https://github.com/rook/rook/actions/runs/5741128966/job/15560540468):
> 
> ```
> + echo 'verifying csi holder interfaces (multus ones must be present)'
> + kubectl -n rook-ceph exec -t ds/csi-rbdplugin-holder-my-cluster -- grep net /proc/net/dev
> command terminated with exit code 1
> + kubectl -n rook-ceph exec -t ds/csi-cephfsplugin-holder-my-cluster -- grep net /proc/net/dev
> command terminated with exit code 1
> + kubectl -n rook-ceph exec -t ds/csi-nfsplugin-holder-my-cluster -- grep net /proc/net/dev
> command terminated with exit code 1
> Error: Process completed with exit code 1.
> ```
> 
> Perhaps github actions fixed some network issue, since that error went away now, but it still leaves the OSDs not able to communicate.
https://github.com/rook/rook/pull/12634/commits/4502ea8ee141834a87b91fed3f41517f1d9285f6 to pass that validation. I guess something is still fixed network wise may be
Actually, I fixed that in this commit

**Comment by travisn** [comment]
> Actually, I fixed that in this commit
https://github.com/rook/rook/commit/4502ea8ee141834a87b91fed3f41517f1d9285f6 to pass that validation. I guess something is still fixed network wise may be

Oh perfect, thanks for pointing that fix out

**Comment by subhamkrai** [comment]
@travisn @BlaineEXE I tried multus on KIND, or minikube with docker driver and latest version of ubuntu
I'm seeing the same error
```yaml
unable to find any IPv4 address in networks '192.168.20.0/24' interfaces ''
```

I would like to take break from this now, I have spend good amount of time on this and seems like it is related to interface issue in ubuntu. I'll try one last thing, to use mac os for multus.

**Comment by BlaineEXE** [comment]
I'll take this over once I'm done with https://github.com/rook/rook/issues/12459

**Comment by subhamkrai** [comment]
@BlaineEXE just fyi, I tried on mac also and getting the same error, so over to you know

**Comment by obnoxxx** [comment]
shouldn't  this issue  be resolved with https://github.com/rook/rook/pull/12634 ?

@subhamkrai , @BlaineEXE, @travisn ?

**Comment by subhamkrai** [comment]
> shouldn't this issue be resolved with #12634 ?
> 
> @subhamkrai , @BlaineEXE, @travisn ?

@obnoxxx I know the title of the pr is bit misleading, the aim was to fix all but unfortunately it did not fixed all

**Comment by travisn** [comment]
The multus test started passing this afternoon in all branches! Nothing changed in Rook that I'm aware of, so perhaps there was a github actions infrastructure fix.

**Comment by subhamkrai** [comment]
> The multus test started passing this afternoon in all branches! Nothing changed in Rook that I'm aware of, so perhaps there was a github actions infrastructure fix.

Finally 🎉
