### ISSUE TITLE
The Object Gateway Service is not configured

### ISSUE THREAD

**Issue by dongdorrong** [rook/rook#13489]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
I installed Ceph Cluster with ObjectStore by following the installation instructions provided in the guide below.
https://rook.github.io/docs/rook/latest/Helm-Charts/helm-charts/

However, I am unable to access the Object Gateway from the Ceph dashboard as shown in the photo below.

![image](https://github.com/rook/rook/assets/62313586/c605264f-d53d-4503-bb33-743dc2aa6b19)

**Expected behavior:**
I think the CephObjectStore should show up in the dashboard, but I don't see it.

**How to reproduce it (minimal and precise):**
helm pull rook-release/rook-ceph --untar
helm install rook-ceph-operator . -f values.yaml -n rook-ceph

helm pull rook-release/rook-ceph-cluster  --untar
helm install rook-ceph-cluster . -f values.yaml -n rook-ceph

**File(s) to submit**:
[values_yaml.zip](https://github.com/rook/rook/files/13807010/values_yaml.zip)

**Logs to submit**:
[ceph-report-servicemap.txt](https://github.com/rook/rook/files/13807025/ceph-report-servicemap.txt)
[pod_rook-ceph-mgr-a-676bf7d4d6-c8dlx.log](https://github.com/rook/rook/files/13807041/pod_rook-ceph-mgr-a-676bf7d4d6-c8dlx.log)

**Cluster Status to submit**:
![image](https://github.com/rook/rook/assets/62313586/566c090c-18ff-4e49-b75d-4d20d8a429f4)

**Environment**:
* OS (e.g. from /etc/os-release):
❯ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"

* Kernel (e.g. `uname -a`):
Linux worker-1 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

* Cloud provider or hardware configuration:

* Rook version (use `rook version` inside of a Rook Pod):
[rook@rook-ceph-operator-5698dc8c7c-2gsdp /]$ rook version
rook: v1.13.1
go: go1.21.5

* Storage backend version (e.g. for ceph do `ceph -v`):
bash-4.4$ ceph -v
ceph version 18.2.1 (7fe91d5d5842e04be3b4f514d6dd990c54b29c76) reef (stable)

* Kubernetes version (use `kubectl version`):
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.4

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
Onpremise

* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):
bash-4.4$ ceph health
HEALTH_OK

**Comment by rkachach** [comment]
Thank you @dongdorrong for reporting the issue. The problem seems similar to what's reported on https://github.com/rook/rook/issues/9660 but this issue supposedly should be fixed on your version (`rook v1.13.1` and `ceph v18.2.1`). @nizamial09 any ideas on what could be the issue here?

**Comment by nizamial09** [comment]
```
│ mgr debug 2024-01-02T03:52:09.701+0000 7f2edcf5e700  0 [dashboard ERROR rest_client] RGW REST API failed GET, connection error (url=http://192.168.1.12:8080/admin/metadata/user?myself): [errno: 111]   
│ mgr debug 2024-01-02T03:52:09.701+0000 7f2edcf5e700  0 [dashboard ERROR rgw_client] RGW REST API cannot be reached: Connection refused [errno 111]. Please check your configuration and that the API en  
```
this is the error I see here, which means that the rgw endpoint is not reachable through kube network. Is the IP and PORT correct? And are they reachable?

**Comment by dongdorrong** [comment]
The IP is the private IP of the worker node that the pod in the objectstore is running on. And the IP and Port are not set by me.

I think it was set automatically when the CephObjectStore was created by the values.yaml used to create the ceph cluster, and the related resources were created.

For reference, if you look at the 'ceph-report-servicemap.txt' file from when I first sent you the report, you can see that the 'addr' value of the rgw daemon is registered as 192.168.1.12.
It seems that the address for the pod or service of the objectstore should be registered, but it also seems to be an issue with recognizing the IP of the node.

Additionally, when I checked the information of the pod associated with objectstore, I saw the following part, so it seems like it is trying to access port 8080.
--rgw-frontends=beast port=8080

I'll also send you the yaml for the pod for the auto-generated objectstore.

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 4b90d3946193265158d3290493fb0bfca9f6b0534358bad48b27bebeccb5c2f4
    cni.projectcalico.org/podIP: 10.0.133.201/32
    cni.projectcalico.org/podIPs: 10.0.133.201/32
  creationTimestamp: "2024-01-08T01:25:15Z"
  generateName: rook-ceph-rgw-ceph-objectstore-a-7c44769b9c-
  labels:
    app: rook-ceph-rgw
    app.kubernetes.io/component: cephobjectstores.ceph.rook.io
    app.kubernetes.io/created-by: rook-ceph-operator
    app.kubernetes.io/instance: ceph-objectstore
    app.kubernetes.io/managed-by: rook-ceph-operator
    app.kubernetes.io/name: ceph-rgw
    app.kubernetes.io/part-of: ceph-objectstore
    ceph_daemon_id: ceph-objectstore
    ceph_daemon_type: rgw
    pod-template-hash: 7c44769b9c
    rgw: ceph-objectstore
    rook.io/operator-namespace: rook-ceph
    rook_cluster: rook-ceph
    rook_object_store: ceph-objectstore
  name: rook-ceph-rgw-ceph-objectstore-a-7c44769b9c-9nkzr
  namespace: rook-ceph
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: rook-ceph-rgw-ceph-objectstore-a-7c44769b9c
    uid: aa578a0a-7b92-4fd7-acad-e88fcb02a7ee
  resourceVersion: "22974996"
  uid: cf087946-5aba-4278-92ca-48e805a3b14b
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app: rook-ceph-rgw
              ceph_daemon_id: ceph-objectstore
              rgw: ceph-objectstore
              rook_cluster: rook-ceph
              rook_object_store: ceph-objectstore
          topologyKey: kubernetes.io/hostname
        weight: 50
  containers:
  - args:
    - --fsid=12638016-2ae0-4975-8fa6-ad0126d7966d
    - --keyring=/etc/ceph/keyring-store/keyring
    - --default-log-to-stderr=true
    - --default-err-to-stderr=true
    - --default-mon-cluster-log-to-stderr=true
    - '--default-log-stderr-prefix=debug '
    - --default-log-to-file=false
    - --default-mon-cluster-log-to-file=false
    - --mon-host=$(ROOK_CEPH_MON_HOST)
    - --mon-initial-members=$(ROOK_CEPH_MON_INITIAL_MEMBERS)
    - --id=rgw.ceph.objectstore.a
    - --setuser=ceph
    - --setgroup=ceph
    - --foreground
    - --rgw-frontends=beast port=8080
    - --host=$(POD_NAME)
    - --rgw-mime-types-file=/etc/ceph/rgw/mime.types
    - --rgw-realm=ceph-objectstore
    - --rgw-zonegroup=ceph-objectstore
    - --rgw-zone=ceph-objectstore
    command:
    - radosgw
    env:
    - name: CONTAINER_IMAGE
      value: quay.io/ceph/ceph:v18.2.1
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: POD_MEMORY_LIMIT
      valueFrom:
        resourceFieldRef:
          divisor: "0"
          resource: limits.memory
    - name: POD_MEMORY_REQUEST
      valueFrom:
        resourceFieldRef:
          divisor: "0"
          resource: requests.memory
    - name: POD_CPU_LIMIT
      valueFrom:
        resourceFieldRef:
          divisor: "1"
          resource: limits.cpu
    - name: POD_CPU_REQUEST
      valueFrom:
        resourceFieldRef:
          divisor: "0"
          resource: requests.cpu
    - name: CEPH_USE_RANDOM_NONCE
      value: "true"
    - name: ROOK_MSGR2
      value: msgr2_false_encryption_false_compression_false
    - name: ROOK_CEPH_MON_HOST
      valueFrom:
        secretKeyRef:
          key: mon_host
          name: rook-ceph-config
    - name: ROOK_CEPH_MON_INITIAL_MEMBERS
      valueFrom:
        secretKeyRef:
          key: mon_initial_members
          name: rook-ceph-config
    image: quay.io/ceph/ceph:v18.2.1
    imagePullPolicy: IfNotPresent
    name: rgw
    readinessProbe:
      exec:
        command:
        - bash
        - -c
        - |
          #!/usr/bin/env bash

          PROBE_TYPE="readiness"
          PROBE_PORT="8080"
          PROBE_PROTOCOL="HTTP"

          # standard bash codes start at 126 and progress upward. pick error codes from 125 downward for
          # script as to allow curl to output new error codes and still return a distinctive number.
          USAGE_ERR_CODE=125
          PROBE_ERR_CODE=124
          # curl error codes: 1-123

          STARTUP_TYPE='startup'
          READINESS_TYPE='readiness'

          RGW_URL="$PROBE_PROTOCOL://0.0.0.0:$PROBE_PORT"

          function check() {
            local URL="$1"
            # --insecure - don't validate ssl if using secure port only
            # --silent - don't output progress info
            # --output /dev/stderr - output HTML header to stdout (good for debugging)
            # --write-out '%{response_code}' - print the HTTP response code to stdout
            curl --insecure --silent --output /dev/stderr --write-out '%{response_code}' "$URL"
          }

          http_response="$(check "$RGW_URL")"
          retcode=$?

          if [[ $retcode -ne 0 ]]; then
            # if this is the startup probe, always returning failure. if startup probe passes, all subsequent
            # probes can rely on the assumption that the health check was once succeeding without errors.
            # if this is the readiness probe, we know that curl was previously working correctly in the
            # startup probe, so curl error most likely means some new error with the RGW.
            echo "RGW health check failed with error code: $retcode. the RGW likely cannot be reached by clients" >/dev/stderr
            exit $retcode
          fi

          RGW_RATE_LIMITING_RESPONSE=503
          RGW_MISCONFIGURATION_RESPONSE=500

          if [[ $http_response -ge 200 ]] && [[ $http_response -lt 400 ]]; then
            # 200-399 are successful responses. same behavior as Kubernetes' HTTP probe
            exit 0

          elif [[ $http_response -eq $RGW_RATE_LIMITING_RESPONSE ]]; then
            # S3's '503: slow down' code is not an error but an indication that RGW is throttling client
            # traffic. failing the readiness check here would only cause an increase in client connections on
            # other RGWs and likely cause those to fail also in a cascade. i.e., a special healthy response.
            echo "INFO: RGW is rate limiting" 2>/dev/stderr
            exit 0

          elif [[ $http_response -eq $RGW_MISCONFIGURATION_RESPONSE ]]; then
            # can't specifically determine if the RGW is running or not. most likely a misconfiguration.
            case "$PROBE_TYPE" in
            "$STARTUP_TYPE")
              # fail until we can accurately get a valid healthy response when runtime starts.
              echo 'FAIL: HTTP code 500 suggests an RGW misconfiguration.' >/dev/stderr
              exit $PROBE_ERR_CODE
              ;;
            "$READINESS_TYPE")
              # config likely modified at runtime which could result in all RGWs failing this check.
              # occasional client failures are still better than total failure, so ignore this
              echo 'WARN: HTTP code 500 suggests an RGW misconfiguration' >/dev/stderr
              exit 0
              ;;
            *)
              # prior arg validation means this path should never be activated, but keep to be safe
              echo "ERROR: probe type is unknown: $PROBE_TYPE" >/dev/stderr
              exit $USAGE_ERR_CODE
              ;;
            esac

          else
            # anything else is a failing response. same behavior as Kubernetes' HTTP probe
            echo "FAIL: received an HTTP error code: $http_response"
            exit $PROBE_ERR_CODE

          fi
      failureThreshold: 3
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 3
      timeoutSeconds: 5
    resources:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: "1"
        memory: 1Gi
    securityContext:
      privileged: false
    startupProbe:
      exec:
        command:
        - bash
        - -c
        - |
          #!/usr/bin/env bash

          PROBE_TYPE="startup"
          PROBE_PORT="8080"
          PROBE_PROTOCOL="HTTP"

          # standard bash codes start at 126 and progress upward. pick error codes from 125 downward for
          # script as to allow curl to output new error codes and still return a distinctive number.
          USAGE_ERR_CODE=125
          PROBE_ERR_CODE=124
          # curl error codes: 1-123

          STARTUP_TYPE='startup'
          READINESS_TYPE='readiness'

          RGW_URL="$PROBE_PROTOCOL://0.0.0.0:$PROBE_PORT"

          function check() {
            local URL="$1"
            # --insecure - don't validate ssl if using secure port only
            # --silent - don't output progress info
            # --output /dev/stderr - output HTML header to stdout (good for debugging)
            # --write-out '%{response_code}' - print the HTTP response code to stdout
            curl --insecure --silent --output /dev/stderr --write-out '%{response_code}' "$URL"
          }

          http_response="$(check "$RGW_URL")"
          retcode=$?

          if [[ $retcode -ne 0 ]]; then
            # if this is the startup probe, always returning failure. if startup probe passes, all subsequent
            # probes can rely on the assumption that the health check was once succeeding without errors.
            # if this is the readiness probe, we know that curl was previously working correctly in the
            # startup probe, so curl error most likely means some new error with the RGW.
            echo "RGW health check failed with error code: $retcode. the RGW likely cannot be reached by clients" >/dev/stderr
            exit $retcode
          fi

          RGW_RATE_LIMITING_RESPONSE=503
          RGW_MISCONFIGURATION_RESPONSE=500

          if [[ $http_response -ge 200 ]] && [[ $http_response -lt 400 ]]; then
            # 200-399 are successful responses. same behavior as Kubernetes' HTTP probe
            exit 0

          elif [[ $http_response -eq $RGW_RATE_LIMITING_RESPONSE ]]; then
            # S3's '503: slow down' code is not an error but an indication that RGW is throttling client
            # traffic. failing the readiness check here would only cause an increase in client connections on
            # other RGWs and likely cause those to fail also in a cascade. i.e., a special healthy response.
            echo "INFO: RGW is rate limiting" 2>/dev/stderr
            exit 0

          elif [[ $http_response -eq $RGW_MISCONFIGURATION_RESPONSE ]]; then
            # can't specifically determine if the RGW is running or not. most likely a misconfiguration.
            case "$PROBE_TYPE" in
            "$STARTUP_TYPE")
              # fail until we can accurately get a valid healthy response when runtime starts.
              echo 'FAIL: HTTP code 500 suggests an RGW misconfiguration.' >/dev/stderr
              exit $PROBE_ERR_CODE
              ;;
            "$READINESS_TYPE")
              # config likely modified at runtime which could result in all RGWs failing this check.
              # occasional client failures are still better than total failure, so ignore this
              echo 'WARN: HTTP code 500 suggests an RGW misconfiguration' >/dev/stderr
              exit 0
              ;;
            *)
              # prior arg validation means this path should never be activated, but keep to be safe
              echo "ERROR: probe type is unknown: $PROBE_TYPE" >/dev/stderr
              exit $USAGE_ERR_CODE
              ;;
            esac

          else
            # anything else is a failing response. same behavior as Kubernetes' HTTP probe
            echo "FAIL: received an HTTP error code: $http_response"
            exit $PROBE_ERR_CODE

          fi
      failureThreshold: 33
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/ceph
      name: rook-config-override
      readOnly: true
    - mountPath: /run/ceph
      name: ceph-daemons-sock-dir
    - mountPath: /etc/ceph/keyring-store/
      name: rook-ceph-rgw-ceph-objectstore-a-keyring
      readOnly: true
    - mountPath: /var/log/ceph
      name: rook-ceph-log
    - mountPath: /var/lib/ceph/crash
      name: rook-ceph-crash
    - mountPath: /var/lib/ceph/rgw/ceph-ceph-objectstore
      name: ceph-daemon-data
    - mountPath: /etc/ceph/rgw
      name: rook-ceph-rgw-ceph-objectstore-mime-types
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-h6s49
      readOnly: true
    workingDir: /var/log/ceph
  - command:
    - /bin/bash
    - -x
    - -e
    - -m
    - -c
    - "\nCEPH_CLIENT_ID=ceph-client.rgw.ceph.objectstore.a\nPERIODICITY=daily\nLOG_ROTATE_CEPH_FILE=/etc/logrotate.d/ceph\nLOG_MAX_SIZE=500M\nROTATE=7\n\n#
      edit the logrotate file to only rotate a specific daemon log\n# otherwise we
      will logrotate log files without reloading certain daemons\n# this might happen
      when multiple daemons run on the same machine\nsed -i \"s|*.log|$CEPH_CLIENT_ID.log|\"
      \"$LOG_ROTATE_CEPH_FILE\"\n\n# replace default daily with given user input\nsed
      --in-place \"s/daily/$PERIODICITY/g\" \"$LOG_ROTATE_CEPH_FILE\"\n\n# replace
      rotate count, default 7 for all ceph daemons other than rbd-mirror\nsed --in-place
      \"s/rotate 7/rotate $ROTATE/g\" \"$LOG_ROTATE_CEPH_FILE\"\n\nif [ \"$LOG_MAX_SIZE\"
      != \"0\" ]; then\n\t# adding maxsize $LOG_MAX_SIZE at the 4th line of the logrotate
      config file with 4 spaces to maintain indentation\n\tsed --in-place \"4i \\
      \\ \\ \\ maxsize $LOG_MAX_SIZE\" \"$LOG_ROTATE_CEPH_FILE\"\nfi\n\nwhile true;
      do\n\t# we don't force the logrorate but we let the logrotate binary handle
      the rotation based on user's input for periodicity and size\n\tlogrotate --verbose
      \"$LOG_ROTATE_CEPH_FILE\"\n\tsleep 15m\ndone\n"
    image: quay.io/ceph/ceph:v18.2.1
    imagePullPolicy: IfNotPresent
    name: log-collector
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 100Mi
    securityContext:
      privileged: false
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
    - mountPath: /etc/ceph
      name: rook-config-override
      readOnly: true
    - mountPath: /run/ceph
      name: ceph-daemons-sock-dir
    - mountPath: /var/log/ceph
      name: rook-ceph-log
    - mountPath: /var/lib/ceph/crash
      name: rook-ceph-crash
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-h6s49
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - args:
    - --verbose
    - --recursive
    - ceph:ceph
    - /var/log/ceph
    - /var/lib/ceph/crash
    - /run/ceph
    - /var/lib/ceph/rgw/ceph-ceph-objectstore
    command:
    - chown
    image: quay.io/ceph/ceph:v18.2.1
    imagePullPolicy: IfNotPresent
    name: chown-container-data-dir
    resources:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: "1"
        memory: 1Gi
    securityContext:
      privileged: false
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/ceph
      name: rook-config-override
      readOnly: true
    - mountPath: /run/ceph
      name: ceph-daemons-sock-dir
    - mountPath: /etc/ceph/keyring-store/
      name: rook-ceph-rgw-ceph-objectstore-a-keyring
      readOnly: true
    - mountPath: /var/log/ceph
      name: rook-ceph-log
    - mountPath: /var/lib/ceph/crash
      name: rook-ceph-crash
    - mountPath: /var/lib/ceph/rgw/ceph-ceph-objectstore
      name: ceph-daemon-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-h6s49
      readOnly: true
  nodeName: worker-2
  preemptionPolicy: PreemptLowerPriority
  priority: 2000000000
  priorityClassName: system-cluster-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: rook-ceph-rgw
  serviceAccountName: rook-ceph-rgw
  shareProcessNamespace: true
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 5
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: rook-config-override
    projected:
      defaultMode: 420
      sources:
      - configMap:
          items:
          - key: config
            mode: 292
            path: ceph.conf
          name: rook-config-override
  - name: rook-ceph-rgw-ceph-objectstore-a-keyring
    secret:
      defaultMode: 420
      secretName: rook-ceph-rgw-ceph-objectstore-a-keyring
  - hostPath:
      path: /data/exporter
      type: DirectoryOrCreate
    name: ceph-daemons-sock-dir
  - hostPath:
      path: /data/rook-ceph/log
      type: ""
    name: rook-ceph-log
  - hostPath:
      path: /data/rook-ceph/crash
      type: ""
    name: rook-ceph-crash
  - emptyDir: {}
    name: ceph-daemon-data
  - configMap:
      defaultMode: 420
      name: rook-ceph-rgw-ceph-objectstore-mime-types
    name: rook-ceph-rgw-ceph-objectstore-mime-types
  - name: kube-api-access-h6s49
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-01-08T01:25:16Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-01-08T01:25:55Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-01-08T01:25:55Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-01-08T01:25:15Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://6a97fee3f2591d7f92727a2cf333e69622d712f84feef217ab9d317d528a83a0
    image: quay.io/ceph/ceph:v18.2.1
    imageID: quay.io/ceph/ceph@sha256:aca35483144ab3548a7f670db9b79772e6fc51167246421c66c0bd56a6585468
    lastState: {}
    name: log-collector
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-01-08T01:25:17Z"
  - containerID: containerd://9a044951d582a4fbfe7a8d0e22fe0f47eaa31397507aee9b00736ebcb7b207be
    image: quay.io/ceph/ceph:v18.2.1
    imageID: quay.io/ceph/ceph@sha256:aca35483144ab3548a7f670db9b79772e6fc51167246421c66c0bd56a6585468
    lastState: {}
    name: rgw
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-01-08T01:25:16Z"
  hostIP: 192.168.1.12
  initContainerStatuses:
  - containerID: containerd://6793a06218593324c457fc0e3e2ad38ffc2b61f43276f5e23d43a226fded27c9
    image: quay.io/ceph/ceph:v18.2.1
    imageID: quay.io/ceph/ceph@sha256:aca35483144ab3548a7f670db9b79772e6fc51167246421c66c0bd56a6585468
    lastState: {}
    name: chown-container-data-dir
    ready: true
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://6793a06218593324c457fc0e3e2ad38ffc2b61f43276f5e23d43a226fded27c9
        exitCode: 0
        finishedAt: "2024-01-08T01:25:15Z"
        reason: Completed
        startedAt: "2024-01-08T01:25:15Z"
  phase: Running
  podIP: 10.0.133.201
  podIPs:
  - ip: 10.0.133.201
  qosClass: Burstable
  startTime: "2024-01-08T01:25:15Z"
```

By any chance, in order to see the menu for objectgateway in the dashboard, do I need to manually apply the rgw endpoints?

**Comment by rkachach** [comment]
@dongdorrong we would like to help but it's really hard without being able to reproduce the issue. Please, can you provide some minimal setup where the issue can be reproduced? any details about your setup will be really helpful.

**Comment by dongdorrong** [comment]
When we initially built the rook-ceph environment, we deployed it with the following versions.

Ceph Operator : 1.12.8
Ceph Cluster : 17.2.6

I noticed that I couldn't access the Ceph Object Gateway's menu in the Ceph dashboard, and when I saw [#9660](https://github.com/rook/rook/issues/9660), I upgraded to the current version.

I changed the values.yaml of each Helm Chart to the latest version as confirmed by #9660, and completed the Ceph version upgrade with the helm upgrade command.

Afterwards, I realized that I didn't follow [the upgrade instructions in the official guide](https://rook.github.io/docs/rook/latest/Upgrade/health-verification/ ), so I think that might be where the problem is.

**Comment by rkachach** [comment]
@dongdorrong thank you for the feedback. Please, let us know in case after following the official upgrade instructions you still have issues :+1:

**Comment by dongdorrong** [comment]
hello.

I've been reviewing the upgrade documentation.
https://rook.github.io/docs/rook/latest-release/Upgrade/rook-upgrade/#helm

It looks like you don't need to do anything special, as it's the same upgrade method I went through.

By any chance, is there any way to force an rgw endpoint to be assigned so that I can enable the Object Gateway's menu in the dashboard?

I've searched and tried many different ways to do this, but nothing seems to work, so I'm really stumped and desperate for help. 🙏

**Comment by rkachach** [comment]
I see, the issue you are reporting was basically fixed in v18.2.1 so it's really strange you hare hitting it again :(

@nizamial09 can you please help with this? is it possible to fix the end-points manually?

**Comment by emdede** [comment]
+1

I bootstrapped a fresh cluster using 18.2.1 and I'm hitting this error. I can see in the mon logs that the dashboard rest_client tries to connect to the URL `https://<HOST-NAME>:443/admin/...`. Instead of the host name I would expect this to be either an IP in the public network by default (f.e. 10.0.1.12) or to be configurable so that I can provide my actual DNS name which does exist (not as HOST-NAME:443 but `s3.my-url.com`).

To set up RGW I ran following config file.

rgw-conf
``` yml
service_type: rgw
service_id: s3
placement:
  count: 3
spec:
  ssl: true
  rgw_frontend_ssl_certificate: |
   <CERTS>
   <KEY>
```

`ceph orch apply -i "rgw-config"`

**Comment by nizamial09** [comment]
rgw has an `rgw_dns_name` config option: https://docs.ceph.com/en/reef/radosgw/config-ref/#confval-rgw_dns_name. If this were to set to the ip addr which could be resolvable, dashboard can pick that up and show the page. Otherwise, the dashboard picks up the ip addr of the daemon assuming that it is resolvable.

**Comment by emdede** [comment]
> rgw has an `rgw_dns_name` config option: https://docs.ceph.com/en/reef/radosgw/config-ref/#confval-rgw_dns_name. If this were to set to the ip addr which could be resolvable, dashboard can pick that up and show the page. Otherwise, the dashboard picks up the ip addr of the daemon assuming that it is resolvable.

Thank you! I was not aware of this. I was able to fix our issue using this command
```
ceph config set global rgw_dns_name s3.my-url.com
```
RGW Dashboard is now working fine.

**Comment by dongdorrong** [comment]
@nizamial09 hello.
I did a test with the 'rgw_dns_name' option you mentioned.

When I applied the FQDN for the service resource provided by Kubernetes, I got the same unreachable situation in rgw_client as before, and I couldn't see the menu in Ceph Dashboard.

```
## toolbox pod

bash-4.4$ ceph config set global rgw_dns_name rook-ceph-rgw-ceph-objectstore.rook-ceph.svc.cluster.local
bash-4.4$ 
bash-4.4$ ceph config get client
WHO     MASK  LEVEL     OPTION                   VALUE                                                       RO
global        basic     log_to_file              true                                                          
global        advanced  mon_allow_pool_delete    true                                                          
global        advanced  mon_allow_pool_size_one  true                                                          
global        advanced  mon_cluster_log_file                                                                   
global        advanced  mon_pg_warn_min_per_osd  0                                                             
global        advanced  rgw_dns_name             rook-ceph-rgw-ceph-objectstore.rook-ceph.svc.cluster.local  * 
```

When I looked at the logs, I realized that rgw_client was accessing port 8080 with the FQDN, and CephObjectStore was exposing port 80.

```
## mgr pod

Traceback (most recent call last):                                                                                                                                                                                                                                                                                        
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 162, in _new_conn                                                                                                                                                                                                                                   
    (self._dns_host, self.port), self.timeout, **extra_kw)                                                                                                                                                                                                                                                                
  File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection                                                                                                                                                                                                                       
    raise err                                                                                                                                                                                                                                                                                                             
  File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection                                                                                                                                                                                                                       
    sock.connect(sa)                                                                                                                                                                                                                                                                                                      
socket.timeout: timed out                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                          
During handling of the above exception, another exception occurred:                                                
                                                                                                                                                                                                                                                                                                                          
Traceback (most recent call last):                                                                                                                                                                                                                                                                                        
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen                                                                                                                                                                                                                                 
    chunked=chunked)                                                                                                                                                                                                                                                                                                      
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request                                                                                                                                                                                                                           
    conn.request(method, url, **httplib_request_kw)                                                                                                                                                                                                                                                                       
  File "/usr/lib64/python3.6/http/client.py", line 1273, in request                                                                                                                                                                                                                                                       
    self._send_request(method, url, body, headers, encode_chunked)                                                                                                                                                                                                                                                        
  File "/usr/lib64/python3.6/http/client.py", line 1319, in _send_request                                                                                                                                                                                                                                                 
    self.endheaders(body, encode_chunked=encode_chunked)                                                                                                                                                                                                                                                                  
  File "/usr/lib64/python3.6/http/client.py", line 1268, in endheaders                                                                                                                                                                                                                                                    
    self._send_output(message_body, encode_chunked=encode_chunked)                                                                                                                                                                                                                                                        
  File "/usr/lib64/python3.6/http/client.py", line 1044, in _send_output                                                                                                                                                                                                                                                  
    self.send(msg)                                                                                                                                                                                                                                                                                                        
  File "/usr/lib64/python3.6/http/client.py", line 982, in send                                                                                                                                                                                                                                                           
    self.connect()                                                                                                                                                                                                                                                                                                        
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 184, in connect                                                                                                                                                                                                                                     
    conn = self._new_conn()                                                                                                                                                                                                                                                                                               
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 167, in _new_conn                                                                                                                                                                                                                                   
    (self.host, self.timeout))                                                                                                                                                                                                                                                                                            
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7f16f8485668>, 'Connection to rook-ceph-rgw-ceph-objectstore.rook-ceph.svc.cluster.local timed out. (connect timeout=45)')
```

So I modified the Deployment for objcetstore so that rgw_client can access port 80, but when I tested it again, I still couldn't access it.

[before]
1. --rgw-frontends=beast port=8080
2. Readiness PROBE_PORT="8080" 
3. Startup PROBE_PORT="8080"

[after]
1. --rgw-frontends=beast port=80
2. Readiness PROBE_PORT="80" 
3. Startup PROBE_PORT="80"

```
## mgr pod

debug 2024-01-18T02:03:44.726+0000 7f483517a700  0 [dashboard INFO rgw_client] Found RGW daemon with configuration: host=rook-ceph-rgw-ceph-objectstore.rook-ceph.svc.cluster.local, port=80, ssl=False                                                                                                                   
debug 2024-01-18T02:03:44.734+0000 7f483517a700  0 [dashboard ERROR rest_client] RGW REST API failed GET, connection error (url=http://rook-ceph-rgw-ceph-objectstore.rook-ceph.svc.cluster.local:80/admin/metadata/user?myself): [errno: 111] Connection refused                                                         
debug 2024-01-18T02:03:44.734+0000 7f483517a700  0 [dashboard ERROR rgw_client] RGW REST API cannot be reached: Connection refused [errno 111]. Please check your configuration and that the API endpoint is accessible                                                                                                   
Traceback (most recent call last):                                                                                                                                                                                                                                                                                        
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 162, in _new_conn                                                                                                                                                                                                                                   
    (self._dns_host, self.port), self.timeout, **extra_kw)                                                                                                                                                                                                                                                                
  File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection                                                                                                                                                                                                                       
    raise err                                                                                                                                                                                                                                                                                                             
  File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection                                                                                                                                                                                                                       
    sock.connect(sa)                                                                                                                                                                                                                                                                                                      
ConnectionRefusedError: [Errno 111] Connection refused
                                                                                                                                                                                                                                                                                                                          
During handling of the above exception, another exception occurred:                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                          
Traceback (most recent call last):                                                                                                                                                                                                                                                                                        
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen                                                                                                                                                                                                                                 
    chunked=chunked)                                                                                                                                                                                                                                                                                                      
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request                                                                                                                                                                                                                           
    conn.request(method, url, **httplib_request_kw)                                                                                                                                                                                                                                                                       
  File "/usr/lib64/python3.6/http/client.py", line 1273, in request                                                                                                                                                                                                                                                       
    self._send_request(method, url, body, headers, encode_chunked)                                                                                                                                                                                                                                                        
  File "/usr/lib64/python3.6/http/client.py", line 1319, in _send_request                                                                                                                                                                                                                                                 
    self.endheaders(body, encode_chunked=encode_chunked)                                                                                                                                                                                                                                                                  
  File "/usr/lib64/python3.6/http/client.py", line 1268, in endheaders                                                                                                                                                                                                                                                    
    self._send_output(message_body, encode_chunked=encode_chunked)                                                                                                                                                                                                                                                        
  File "/usr/lib64/python3.6/http/client.py", line 1044, in _send_output                                                                                                                                                                                                                                                  
    self.send(msg)                                                                                                                                                                                                                                                                                                        
  File "/usr/lib64/python3.6/http/client.py", line 982, in send                                                                                                                                                                                                                                                           
    self.connect()                                                                                                                                                                                                                                                                                                        
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 184, in connect                                                                                                                                                                                                                                     
    conn = self._new_conn()                                                                                                                                                                                                                                                                                               
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 171, in _new_conn                                                                                                                                                                                                                                   
    self, "Failed to establish a new connection: %s" % e)                                                                                                                                                                                                                                                                 
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f482b82ca58>: Failed to establish a new connection: [Errno 111] Connection refused
```

Finally, when I modified the targetPort value applied to the objectstore's service from 8080 to 80, I saw that I could access it from the Dashboard, but after some time, the targetPort value was restored to 8080, and the changes I made to the objectstore's Deployment in rgw_client above were also restored.

As a result, applying the rgw_dns_name option with the FQDN value failed and we decided to force the pod ip of the objectstore.

```
objectstore_pod_ip=`kubectl get pod -n rook-ceph -o wide | grep objectstore | awk '{print $6}'`
toolbox_pod_name=`kubectl get pod -n rook-ceph -o wide | grep tools | awk '{print $1}'`
kubectl -n rook-ceph exec -it $toolbox_pod_name -- ceph config set global rgw_dns_name $objectstore_pod_ip
kubectl -n rook-ceph exec -it $toolbox_pod_name -- ceph config get client
```

**Comment by BlaineEXE** [comment]
If Rook changes the port that is exposed at the service, that may risk breaking users who already have CephObjectStore deployed and are consuming it from other apps.

I think the thing Rook must do is to ensure the dashboard (mgr pod) can be configured to address the service using the CephObjectStore configuration. I suspect this might require some dashboard changes in Ceph to allow such modifications, especially considering that different CephObjectStores might use different ports.

**Comment by dongdorrong** [comment]
Finally, after processing with the script below, which I mentioned earlier, I was getting errors across the board.

Since my Kubernetes cluster is still in development, rebuilding it wasn't a problem, so I initialized it and then rebuilt it and found that I could access the dashboard for ObjectGateway without any problems.

Thank you for your attention to my issue.

```
objectstore_pod_ip=`kubectl get pod -n rook-ceph -o wide | grep objectstore | awk '{print $6}'`
toolbox_pod_name=`kubectl get pod -n rook-ceph -o wide | grep tools | awk '{print $1}'`
kubectl -n rook-ceph exec -it $toolbox_pod_name -- ceph config set global rgw_dns_name $objectstore_pod_ip
kubectl -n rook-ceph exec -it $toolbox_pod_name -- ceph config get client
```
