### ISSUE TITLE
The Service rook-ceph-mgr-dashboard does not route properly to the active mgr.

### ISSUE THREAD

**Issue by makiv2** [rook/rook#13601]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

I have two mgrs.

When mgr.a is active the dashboard service routes properly to the ceph-dashboard through the istio ingress.

When the mgr.b is active the dashboard service forwards the request to mgr.a which in turn redirects the request to the ip of mgr.b. Naturally the browser outside of the kubernetes local network can not resolve this.

`This resource can be found at <a href="[http://10.244.0.11:8080/">http://10.244.0.11:8080/](http://10.244.0.11:8080/%22%3Ehttp://10.244.0.11:8080/)</a>.`

Illustration (Not relevant routing steps have been excluded)
![image](https://github.com/rook/rook/assets/55803544/18769aca-ec67-45e5-b296-e7df7e28890e)

**Expected behavior:**

When mgr.a is active the service routes properly to the ceph-dashboard through the istio ingress

When mgr.b is active the service routes properly to the ceph-dashboard through the istio ingress

**Quick fix:**

Only deploy one manager.

**How to reproduce it (minimal and precise):**

- Deploy the operator helm chart.
- Deploy the rook-ceph-cluster helm chart.
- Disable ssl for the dashboard through the values for rook-ceph-cluster.
- Deploy a minimal Istio gateway
- Create a istio virtual service that points to the rook dashboard service.
- Wait for the active mgr to swap.
- Try to connect through the ingress.

**Logs to submit**:

Logs from mgr.a
```
debug 2024-01-22T11:12:11.506+0000 7f7a4c6c4700  0 [dashboard INFO request] [10.244.0.176:42894] [GET] [303] [0.009s] [92.0B] [d05e2f9f-11f4-4e8f-9c3f-7fb822edfc3d] /main.871e04c0fd27227d.js
debug 2024-01-22T11:12:11.506+0000 7f7a4aec1700  0 [dashboard INFO request] [10.244.0.176:42910] [GET] [303] [0.005s] [92.0B] [f450eca1-97ba-44b4-a3de-0a03db0521be] /styles.5f6140b407c420b8.css
debug 2024-01-22T11:12:11.518+0000 7f7a49ebf700  0 [dashboard INFO request] [10.244.0.176:42910] [GET] [200] [0.003s] [1.4K] [2082ed7a-f942-46ec-b50c-53442d626827] /favicon.ico
debug 2024-01-22T11:12:54.515+0000 7f7a4a6c0700  0 [dashboard INFO root] Redirecting to active 'http://10.244.0.11:8080/'
debug 2024-01-22T11:12:54.519+0000 7f7a4cec5700  0 [dashboard INFO root] Redirecting to active 'http://10.244.0.11:8080/'
debug 2024-01-22T11:12:54.519+0000 7f7a48ebd700  0 [dashboard INFO root] Redirecting to active 'http://10.244.0.11:8080/'
```

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

Both Cluster and Operator are healthy and everything else works.

**Environment**:
* OS (e.g. from /etc/os-release):  Ubuntu 22.04.3 LTS
* Kernel (e.g. `uname -a`): Linux kubernetes 5.15.0-91-generic # 101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
* Rook version (use `rook version` inside of a Rook Pod): master
* Kubernetes version (use `kubectl version`): v1.29.0

**Comment by travisn** [comment]
@makiv2 What labels do you see on the mgr pods and what labels do you have on the service selector? The active mgr is expected to have the label `mgr_role=active`, and the service selector needs to use that label. When the act mgr fails over, Rook updates the label on the mgr pods so the redirection is expected to happen automatically. We can't rely on the mgr pod forwarding the request in the K8s env.

**Comment by makiv2** [comment]
@travisn I ended up solving my problem by setting the `cephCluster.mgr.count = 1`.

But I will try to reproduce it again tomorrow with another mgr, although I'm not sure what causes the active mgr to swap and if this routing bug happens on every swap. As this has only happened to me  2-3 times at what seems like random moments.

**Comment by rkachach** [comment]
@makiv2 as already explained by @travisn, service selector relies on the `mgr_role` label. The issue you describe should be fixed starting from Rook `v1.11.6` (by the PR https://github.com/rook/rook/pull/11845). It's been a while since we release that version and we haven't seen any issues related to that old buggy behavior. 

The new HA mechanism uses the label `mgr_role=` to route the service to the active mgr. Please, can you check if your mgr pods have that label? can you show the output of `k get pod rook-ceph-mgr-xxxxx  --show-labels`?

**Comment by makiv2** [comment]
@rkachach Here are my labels. Might be related to #13577 as I have only encountered this issue after disabling ssl for the dashboard and using Istio together with and cert manager to handle all HTTPS. If I recall correctly weird bugs with the dashboard service started to occur after I applied `dashboard.ssl: false`.

Rook version: `rook: v1.13.0-alpha.0.174.gdf04e5cce, go: go1.21.5`
```
-app.kubernetes.io/component=cephclusters.ceph.rook.io
-app.kubernetes.io/created-by=rook-ceph-operator
-app.kubernetes.io/instance=a
-app.kubernetes.io/managed-by=rook-ceph-operator
-app.kubernetes.io/name=ceph-mgr
-app.kubernetes.io/part-of=rook-ceph
-app=rook-ceph-mgr
-ceph_daemon_id=a
-ceph_daemon_type=mgr
-instance=a
-mgr=a
-mgr_role=active
-pod-template-hash=66644c8fcd
-rook.io/operator-namespace=rook-ceph
-rook_cluster=rook-ceph
```

**Comment by makiv2** [comment]
I ended up "solving" issue #13577 by setting `port: 8080` in my rook-ceph-cluster values.yaml.

As setting the port to an arbitrary number did not solve the issue for  @chenlein I believe that the port value has to be set to 8080. Because on deployment the mgr logs show `ssl=on`, then after startup the mgr resolves to `ssl=off`. When SSL is turned off the mgr falls back to the default http port for the mgr, which is 8080. This in turn matches the mgr pod's port up with the  service port that has been set by the values.yaml. 

Maybe both issues (#13577 and #13601) are related to deploying rook-ceph  via the helm charts. `deploy/charts/rook-ceph-cluster` and `deploy/charts/rook-ceph` ? As I am deploying rook-ceph through argocd.

I will investigate more if I end up encountering these issues again. @rkachach

**Comment by rkachach** [comment]
Thank you @makiv2 for your investigation and for the input. I'll try to get some time and test the deployment by using the helm chart. Meanwhile plz let me know in case you find any sequence that always leads to reproduce the BUG.

**Comment by rkachach** [comment]
@makiv2 I was wondering if you are you still suffering from this issue even after https://github.com/rook/rook/issues/13577 has been fixed?

I couldn't reproduce the issue on my side so plz if you can provide detailed steps to reproduce it that would be really helpful.

**Comment by mmeier86** [comment]
@rkachach I've got at least a very similar issue since yesterday. I'm running the v1.13.7 via the Helm chart, which should already include #13577 I believe. I do have `dashboard.ssl` to false.

The relevant parts of my Cluster CRD look like this:
```yaml
clusterName: k8s-rook
operatorNamespace: rook-ceph
toolbox:
  enabled: false
monitoring:
  enabled: true
cephClusterSpec:
  mgr:
    modules:
      - name: pg_autoscaler
        enabled: true
      - name: devicehealth
        enabled: true
      - name: diskprediction_local
        enabled: true
      - name: rook
        enabled: true
  dashboard:
    ssl: false
  network:
    provider: host
ingress:
  dashboard:
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: secureweb
    host:
      name: ceph-dash.example.com
```
My Ingress is Traefik. Up to yesterday evening, everything worked fine and the dashboard connection worked as expected. But since yesterday, I'm getting the same redirection behaviour as described in the initial post. This started happening after I set `monitoring.enabled: true` yesterday. Gathering metrics immediately worked, but the dashboard started redirecting.
I've just looked at my two mgr pods, and they both have the `mgr_role=active` label.

Here are the outputs of the `ceph config` commands you noted above:
```
ceph config get mgr.a | grep mgr
Info: running 'ceph' command with args: [config get mgr.a]
mgr           advanced  mgr/dashboard/PROMETHEUS_API_SSL_VERIFY  false                                     * 
mgr           advanced  mgr/dashboard/RGW_API_ACCESS_KEY         xxxxxxx                      * 
mgr           advanced  mgr/dashboard/RGW_API_SECRET_KEY         xxxxxxx  * 
mgr           advanced  mgr/dashboard/server_port                7000                                      * 
mgr           advanced  mgr/dashboard/ssl                        false                                     * 
mgr           advanced  mgr/devicehealth/enable_monitoring       true                                        
mgr           advanced  mgr/orchestrator/orchestrator            rook                                        
mgr           advanced  mgr/prometheus/rbd_stats_pools                                                     * 
mgr           advanced  mgr/telemetry/enabled                    true                                      * 
```
```
ceph config get mgr.b | grep mgr
Info: running 'ceph' command with args: [config get mgr.b]
mgr           advanced  mgr/dashboard/PROMETHEUS_API_SSL_VERIFY  false                                     * 
mgr           advanced  mgr/dashboard/RGW_API_ACCESS_KEY         xxxxxx                      * 
mgr           advanced  mgr/dashboard/RGW_API_SECRET_KEY         xxxxxx  * 
mgr           advanced  mgr/dashboard/server_port                7000                                      * 
mgr           advanced  mgr/dashboard/ssl                        false                                     * 
mgr           advanced  mgr/devicehealth/enable_monitoring       true                                        
mgr           advanced  mgr/orchestrator/orchestrator            rook                                        
mgr           advanced  mgr/prometheus/rbd_stats_pools                                                     * 
mgr           advanced  mgr/telemetry/enabled                    true                                      * 
```
```
ceph config get mgr | grep mgr
Info: running 'ceph' command with args: [config get mgr]
mgr           advanced  mgr/dashboard/PROMETHEUS_API_SSL_VERIFY  false                                     * 
mgr           advanced  mgr/dashboard/RGW_API_ACCESS_KEY         xxxxx                     * 
mgr           advanced  mgr/dashboard/RGW_API_SECRET_KEY         xxxxx  * 
mgr           advanced  mgr/dashboard/server_port                7000                                      * 
mgr           advanced  mgr/dashboard/ssl                        false                                     * 
mgr           advanced  mgr/devicehealth/enable_monitoring       true                                        
mgr           advanced  mgr/orchestrator/orchestrator            rook                                        
mgr           advanced  mgr/prometheus/rbd_stats_pools                                                     * 
mgr           advanced  mgr/telemetry/enabled                    true                                      * 
```

I've left my cluster in the current state, so if you need something else, please ping me.

**Comment by rkachach** [comment]
@mmeier86 thank you for reporting this. Do you still have the failing cluster up&running?

**Comment by mmeier86** [comment]
I'm afraid it was too late, I did an update of all my hosts last week, and after that everything was fine with Rook again. I also did the 1.14 update today and also did not run into the issue again. I will ping here if I manage to hit it again.

**Comment by Sthing** [comment]
I experienced a similar issue today. (I use a NodePort, but the issue is the same).

Output from `kubectl describe service -n rook-ceph rook-ceph-mgr-dashboard-nodeport` included:
```
Endpoints: 10.244.3.78:8443,10.244.5.145:8443
```
The two IPs match my two manager pods, rook-ceph-mgr-a-5d8d685fb5-7rvc9 and rook-ceph-mgr-b-7c87bd47d8-rtzl6.
Both had the label `mgr_role=active`.

Output from `kubectl logs  rook-ceph-mgr-b-7c87bd47d8-rtzl6 -n rook-ceph -c watch-active`:
```
2024/04/28 06:54:26 maxprocs: Leaving GOMAXPROCS=19: CPU quota undefined
2024-04-28 06:54:26.508283 I | ceph-spec: parsing mon endpoints: c=10.104.101.12:6789,d=10.100.217.42:6789,b=10.104.6.157:6789
2024-04-28 06:54:26.508374 I | rookcmd: starting Rook v1.14.1 with arguments '/usr/local/bin/rook ceph mgr watch-active'
2024-04-28 06:54:26.508380 I | rookcmd: flag values: --ceph-version=ceph version 18.2.2-0 reef, --cluster-id=46ec4497-b022-45a4-9366-ff633969c7c9, --cluster-name=rook-ceph, --daemon-name=b, --dashboard-enabled=true, --help=false, --log-level=INFO, --monitoring-enabled=false, --update-interval=15s
2024-04-28 06:54:26.516380 I | cephclient: writing config file /var/lib/rook/rook-ceph/rook-ceph.config
2024-04-28 06:54:26.516462 I | cephclient: generated admin config in /var/lib/rook/rook-ceph
2024-04-28 06:54:26.516568 I | op-mgr: Checking mgr_role label value of daemon b (prev active mgr was unknown)
2024-04-28 06:54:26.971237 I | op-mgr: updating mgr_role label value of daemon b to 'standby'. New active mgr is a.
2024-04-28 06:54:27.132042 I | op-mgr: updating mgr_role label value of daemon b to 'standby'. New active mgr is a.
2024-04-28 06:54:27.426745 I | op-mgr: cannot update the active mgr pod "rook-ceph-mgr-b-7c87bd47d8-rtzl6". err=Operation cannot be fulfilled on pods "rook-ceph-mgr-b-7c87bd47d8-rtzl6": the object has been modified; please apply your changes to the latest version and try again
2024-04-28 06:54:27.534230 I | cephcmd: successfully checked mgr_role label. checking again in 15s
2024-04-28 06:54:42.544034 I | op-mgr: Checking mgr_role label value of daemon b (prev active mgr was a)
2024-04-28 06:54:43.001023 I | op-mgr: active mgr is still the same (a). No need to update mgr_role label on daemon b.
2024-04-28 06:54:43.001052 I | cephcmd: successfully checked mgr_role label. checking again in 15s
2024-04-28 06:54:58.001853 I | op-mgr: Checking mgr_role label value of daemon b (prev active mgr was a)
2024-04-28 06:54:58.471047 I | op-mgr: active mgr is still the same (a). No need to update mgr_role label on daemon b.
2024-04-28 06:54:58.471077 I | cephcmd: successfully checked mgr_role label. checking again in 15s
```
The important part is *cannot update the active mgr pod "rook-ceph-mgr-b-7c87bd47d8-rtzl6". err=Operation cannot be fulfilled on pods "rook-ceph-mgr-b-7c87bd47d8-rtzl6": the object has been modified; please apply your changes to the latest version and try again*

So it actually tried to change the role label, but failed because it tried to update a stale object.

And it seems that it continues to compare the wanted value to a cached value that does not match the real label value.

I "fixed" the issue by `kubectl edit ...` the pod and changing the label to `mgr_role=standby`. Now the service only points to the active manager as expected.

**Comment by rkachach** [comment]
@Sthing thank you very much for the detailed report. That's really helpful to get more information and try to understand how we reach the active-active situation. It would also help if you remember (or can provide) the steps to reproduce issue so I can try to fix it. 

I'd also be interested to know if forcing a mgr failover (by following the below instructions) fixes the issue or not.

Force a mgr failover (from toolbox):

```
bash-4.4$ ceph mgr fail
bash-4.4$ ceph mgr stat
{
    "epoch": 32,
    "available": true,
    "active_name": "a",
    "num_standby": 0
}
```

**Comment by Sthing** [comment]
@rkachach Sorry, I don't know how to trigger the "*the object has been modified; please apply your changes to the latest version and try again*" situation.

I tried:
  - `ceph mgr fail` a couple of times - it was handled as expected.
  - killing the mgr-b pod from ArgoCD - it just restarted and ran as expected.
  - adding an extra label to the pod with "kubectl edit" and then `ceph mgf fail` - but the mgr_role label was updated as it should be.
