### ISSUE TITLE
Object and Smoke suites are failing with object error on latest devel images

### ISSUE THREAD

**Issue by travisn** [rook/rook#14947]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The latest ceph image `quay.io/ceph/daemon-base:latest-squid-devel` is causing the smoke and object test suites to fail with the following errors, starting today, for example see [this job](https://github.com/rook/rook/actions/runs/11612886250/job/32337381298):
```
=== RUN   TestCephSmokeSuite/TestObjectStorage_SmokeTest/check_if_the_dashboard-admin_user_exists_in_all_existing_object_stores
2024-10-31 13:50:27.346450 D | exec: Running command: kubectl exec -i rook-ceph-tools-8896d8f44-jtb5n -n smoke-ns -- timeout 15 radosgw-admin user info --uid=dashboard-admin --rgw-realm=lite-store
2024-10-31 13:50:28.241354 W | installer: Error executing command "radosgw-admin": <exit status 22>
2024-10-31 13:50:28.241400 I | integrationTest: output: . could not fetch user info: no user info saved
command terminated with exit code 22
    ceph_base_object_test.go:182: 
        	Error Trace:	/home/runner/work/rook/rook/tests/integration/ceph_base_object_test.go:182
        	Error:      	Received unexpected error:
        	            	exit status 22
        	Test:       	TestCephSmokeSuite/TestObjectStorage_SmokeTest/check_if_the_dashboard-admin_user_exists_in_all_existing_object_stores
```
And from the [object store suite](https://github.com/rook/rook/actions/runs/11612886250/job/32337370190):
```
=== RUN   TestCephObjectSuite/TestWithTLS/check_if_the_dashboard-admin_user_exists_in_all_existing_object_stores
2024-10-31 13:41:22.974266 D | exec: Running command: kubectl exec -i rook-ceph-tools-8896d8f44-k7mj5 -n object-ns -- timeout 15 radosgw-admin user info --uid=dashboard-admin --rgw-realm=tls-test-store
2024-10-31 13:41:24.214460 W | installer: Error executing command "radosgw-admin": <exit status 22>
2024-10-31 13:41:24.214482 I | integrationTest: output: . could not fetch user info: no user info saved
command terminated with exit code 22
    ceph_base_object_test.go:182: 
        	Error Trace:	/home/runner/work/rook/rook/tests/integration/ceph_base_object_test.go:182
        	Error:      	Received unexpected error:
        	            	exit status 22
        	Test:       	TestCephObjectSuite/TestWithTLS/check_if_the_dashboard-admin_user_exists_in_all_existing_object_stores
2024-10-31 13:41:24.214611 I | integrationTest: Testing Object Operations on tls-test-store
2024-10-31 13:41:24.217758 I | integrationTest: Create Object Store "bucket-notification-tls-test-store" with replica count 1
=== NAME  TestCephObjectSuite/TestWithTLS
    ceph_bucket_notification_test.go:56: 
        	Error Trace:	/home/runner/work/rook/rook/tests/integration/ceph_bucket_notification_test.go:56
        	            				/home/runner/work/rook/rook/tests/integration/ceph_object_test.go:153
        	            				/home/runner/work/rook/rook/tests/integration/ceph_object_test.go:102
        	Error:      	Expected nil, but got: &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:"", RemainingItemCount:(*int64)(nil)}, Status:"Failure", Message:"cephobjectstores.ceph.rook.io \"bucket-notification-tls-test-store\" not found", Reason:"NotFound", Details:(*v1.StatusDetails)(0xc0007d9020), Code:[404](https://github.com/rook/rook/actions/runs/11612886250/job/32337370190#step:4:405)}}
        	Test:       	TestCephObjectSuite/TestWithTLS
    ceph_bucket_notification_test.go:58: 
        	Error Trace:	/home/runner/work/rook/rook/tests/integration/ceph_bucket_notification_test.go:58
        	            				/home/runner/work/rook/rook/tests/integration/ceph_object_test.go:153
        	            				/home/runner/work/rook/rook/tests/integration/ceph_object_test.go:102
        	Error:      	Expected nil, but got: failed to get advertise endpoint for object store "/": At least one of Port or SecurePort should be non-zero
        	Test:       	TestCephObjectSuite/TestWithTLS
```

**Expected behavior:**
Tests should pass.

**How to reproduce it (minimal and precise):**

See the CI in the latest PRs that have run today.

**Comment by BlaineEXE** [comment]
Exit code 22 seems to be `EINVAL`, suggesting that the `radosgw-admin` CLI arguments have changed recently. 

This is the failing command from the smoke suite:
`radosgw-admin user info --uid=dashboard-admin --rgw-realm=lite-store`

^^ That also fails for `tls-test-store`.

There's also a 404 issue getting the `bucket-notification-tls-test-store` CephObjectStore object from k8s in the bucket notification test later.


These are the only PRs I see that relate to RGW at all:
- https://github.com/ceph/ceph/pull/58734/files
- https://github.com/ceph/ceph/pull/58315/files

Neither seem like they would cause disruption for us.

**Comment by BlaineEXE** [comment]
@cbodley we just started seeing issues with running this radosgw-admin command with our nightly tests against `latest-squid-devel` sometime in the last day. Are you aware of any known issues or recent changes that might cause this? I noted what I found merged in Ceph for the last couple days in my previous comment.

The Rook e2e code here has no recent changes, and I don't see anything right now that suggests a misconfiguration from our side.

```
radosgw-admin user info --uid=dashboard-admin --rgw-realm=lite-store
# returns code 22 (EINVAL?)
```

We appreciate the help and suggestions

**Comment by cbodley** [comment]
> @cbodley we just started seeing issues with running this radosgw-admin command with our nightly tests against `latest-squid-devel` sometime in the last day.

@BlaineEXE how recent is that tag? 'git log src/rgw' shows one backport merged earlier today:

> ed45fc06218 Merge pull request #59671 from yuvalif/wip-67952-squid

a batch of backports merged last week on Oct 23:
> 023ef8240f7 Merge pull request #60244 from cbodley/wip-67957-squid
8b9519e5dc8 Merge pull request #60065 from cbodley/wip-68330-squid
2a474942eab Merge pull request #59670 from mkogan1/wip-67922-squid
9f6f004ca8f Merge pull request #59439 from cbodley/wip-67712-squid
4761ad2b6b9 Merge pull request #59413 from cbodley/wip-67686-squid
f7292e87a62 Merge pull request #59226 from cbodley/wip-67558-squid
dcb09a40de6 Merge pull request #59223 from cbodley/wip-67557-squid

and nothing before that since Aug 28

**Comment by BlaineEXE** [comment]
`latest-squid-devel` is 18 hours old. IIRC though, that can be an extra 24 hours delayed from when things are merged. I think those images are built daily as long as there are changes, but @guits I think would know that more definitely.

**Comment by travisn** [comment]
The [daily CI](https://github.com/rook/rook/actions/runs/11621874803/job/32366404511) shows that these failures are actually on all the latest devel tags: `latest-reef-devel`, `latest-squid-devel`, and `latest-main-devel`.

**Comment by travisn** [comment]
Rook is calling this command to enable the dashboard, and the command does not appear to exist in the devel images:
```
ceph dashboard ac-user-create admin
```
Actually, it appears all `dashboard` commands are missing:
```
$ ceph dashboard ac-user-create dashboard-admin -i /tmp/p.txt administrator
no valid command found; 10 closest matches:
pg stat
…
Error EINVAL: invalid command

$ ceph -h | grep dashboard
$ 
```
In a Squid cluster, I see `ceph -h` returns a lot of options, and now they are all missing. 

@jmolmo Are you aware of dashboard commands changing?

**Comment by nizamial09** [comment]
> Are you aware of dashboard commands changing?

there aren't any command changes recently.


> Actually, it appears all `dashboard` commands are missing:

it usually happens when the dashboard module is not started. Is there more logs or traces available to see whether enabling the dashboard module goes right or not?

**Comment by nizamial09** [comment]
We are seeing from multiple places that the dashboard module broke in newer builds. I am attempting a fix here: https://github.com/ceph/ceph/pull/60602. Probably that could be the general issue here.

**Comment by subhamkrai** [comment]
> it usually happens when the dashboard module is not started. Is there more logs or traces available to see whether enabling the dashboard module goes right or not?

@nizamial09 I'm sharing mgr logs, let me know if you 
[logs--rook-ceph-mgr-a-ccfdd59fb-9vfsz.txt](https://github.com/user-attachments/files/17617529/logs--rook-ceph-mgr-a-ccfdd59fb-9vfsz.txt)
need more logs

**Comment by subhamkrai** [comment]
[logs--rook-ceph-mon-b-7fc97c9d6-lh4kj.txt](https://github.com/user-attachments/files/17617532/logs--rook-ceph-mon-b-7fc97c9d6-lh4kj.txt)
 Also sharing mon logs as you asked

**Comment by nizamial09** [comment]
thank you @subhamkrai . I can see from the log its the same error. dashboard and prometheus is not starting. 
```
debug 2024-10-31T13:39:26.638+0000 7fd6fdb580c0 -1 mgr[py] Module not found: 'prometheus'
debug 2024-10-31T13:39:26.638+0000 7fd6fdb580c0 -1 mgr[py] Traceback (most recent call last):
  File "/usr/share/ceph/mgr/prometheus/__init__.py", line 2, in <module>
    from .module import Module, StandbyModule
  File "/usr/share/ceph/mgr/prometheus/module.py", line 38, in <module>
    v = Version(cherrypy.__version__)
  File "/usr/lib/python3.9/site-packages/packaging/version.py", line 298, in __init__
    raise InvalidVersion("Invalid version: '{0}'".format(version))
packaging.version.InvalidVersion: Invalid version: 'unknown'

debug 2024-10-31T13:39:26.638+0000 7fd6fdb580c0 -1 mgr[py] Class not found in module 'prometheus'
debug 2024-10-31T13:39:26.638+0000 7fd6fdb580c0 -1 mgr[py] Error loading module 'prometheus': (2) No such file or directory
debug 2024-10-31T13:39:26.638+0000 7fd6fdb580c0  1 mgr[py] Loading python module 'dashboard'
debug 2024-10-31T13:39:27.054+0000 7fd6fdb580c0 -1 mgr[py] Module not found: 'dashboard'
debug 2024-10-31T13:39:27.054+0000 7fd6fdb580c0 -1 mgr[py] Traceback (most recent call last):
  File "/usr/share/ceph/mgr/dashboard/__init__.py", line 60, in <module>
    from .module import Module, StandbyModule  # noqa: F401
  File "/usr/share/ceph/mgr/dashboard/module.py", line 52, in <module>
    patch_cherrypy(cherrypy.__version__)
  File "/usr/share/ceph/mgr/dashboard/cherrypy_backports.py", line 197, in patch_cherrypy
    accept_exceptions_from_builtin_ssl(ver)
  File "/usr/share/ceph/mgr/dashboard/cherrypy_backports.py", line 113, in accept_exceptions_from_builtin_ssl
    patch_builtin_ssl_wrap(v, accept_ssl_errors)
  File "/usr/share/ceph/mgr/dashboard/cherrypy_backports.py", line 75, in patch_builtin_ssl_wrap
    from cherrypy.wsgiserver.ssl_builtin import BuiltinSSLAdapter as builtin_ssl
ModuleNotFoundError: No module named 'cherrypy.wsgiserver'

debug 2024-10-31T13:39:27.054+0000 7fd6fdb580c0 -1 mgr[py] Class not found in module 'dashboard'
```

Should be fixed by https://github.com/ceph/ceph/pull/60602

**Comment by nizamial09** [comment]
this is the tracker: https://tracker.ceph.com/issues/68802

**Comment by travisn** [comment]
The reef tests are still failing with this issue in the daily CI. Squid and main are passing. @nizamial09 Is there still any fix pending merge for reef? The tests are running with the `latest-reef-devel` image, which I see is updated [here](https://quay.io/repository/ceph/daemon-base?tab=tags).

**Comment by nizamial09** [comment]
@travisn I have merged the [reef PR](https://github.com/ceph/ceph/pull/60633) this past week so nothing pending there. Could you please point me where I can look for the mgr logs of this run?

**Comment by travisn** [comment]
The latest run is [here](https://github.com/rook/rook/actions/runs/12021178476). The logs can be downloaded [here](https://github.com/rook/rook/actions/runs/12021178476/artifacts/2236177548). Look for the mgr log here: `namespace-smoke-ns/logs--rook-ceph-mgr-a-6c6b99f4d4-k7vrd.txt`. 

I see these errors:
```
debug 2024-11-26T00:23:11.804+0000 7f123791d040 -1 mgr[py] Traceback (most recent call last):
  File "/usr/share/ceph/mgr/prometheus/__init__.py", line 2, in <module>
    from .module import Module, StandbyModule
  File "/usr/share/ceph/mgr/prometheus/module.py", line 38, in <module>
    v = Version(cherrypy.__version__)
  File "/usr/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/version.py", line 277, in __init__
    raise InvalidVersion("Invalid version: '{0}'".format(version))
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: 'unknown'

debug 2024-11-26T00:23:11.804+0000 7f123791d040 -1 mgr[py] Class not found in module 'prometheus'
debug 2024-11-26T00:23:11.804+0000 7f123791d040 -1 mgr[py] Error loading module 'prometheus': (2) No such file or directory
debug 2024-11-26T00:23:11.804+0000 7f123791d040  1 mgr[py] Loading python module 'dashboard'
debug 2024-11-26T00:23:12.220+0000 7f123791d040 -1 mgr[py] Module not found: 'dashboard'
debug 2024-11-26T00:23:12.220+0000 7f123791d040 -1 mgr[py] Traceback (most recent call last):
  File "/usr/share/ceph/mgr/dashboard/__init__.py", line 60, in <module>
    from .module import Module, StandbyModule  # noqa: F401
  File "/usr/share/ceph/mgr/dashboard/module.py", line 51, in <module>
    patch_cherrypy(cherrypy.__version__)
  File "/usr/share/ceph/mgr/dashboard/cherrypy_backports.py", line 197, in patch_cherrypy
    accept_exceptions_from_builtin_ssl(ver)
  File "/usr/share/ceph/mgr/dashboard/cherrypy_backports.py", line 113, in accept_exceptions_from_builtin_ssl
    patch_builtin_ssl_wrap(v, accept_ssl_errors)
  File "/usr/share/ceph/mgr/dashboard/cherrypy_backports.py", line 75, in patch_builtin_ssl_wrap
    from cherrypy.wsgiserver.ssl_builtin import BuiltinSSLAdapter as builtin_ssl
ModuleNotFoundError: No module named 'cherrypy.wsgiserver'
```

**Comment by nizamial09** [comment]
thank you @travisn. that's really weird. I don't see those line in the [prometheus/module.py](https://github.com/ceph/ceph/blob/reef/src/pybind/mgr/prometheus/module.py) file.

I also grepped into the latest-reef-devel image for this line but its neither there as well.
```
╭─nia@alkatraz-rh ~/Downloads/logs_31324555510 
╰─$ podman run -it quay.io/ceph/daemon-base:latest-reef-devel cat /usr/share/ceph/mgr/prometheus/module.py | grep cherrypy.__version__

```

is the test running with some cached older image or it pulls regularly for the latest reef devel image?

One more thing I saw in the log is that, the version that shows there is 
```
ceph version 18.2.4-1176-g33074c09 (33074c09afca08577e35dc70666c88e608020723) reef (stable)
```

but when I enter it locally on the latest one
```
╰─$ podman run -it quay.io/ceph/daemon-base:latest-reef-devel ceph -v
ceph version 18.2.4-1196-gead6e769 (ead6e76959d5e5b2cefe40a798aa522d5db6e71a) reef (stable)

```

so the one in CI looks a little older. That might be it.

**Comment by travisn** [comment]
Great catch on the older image, I'll look into why the CI has an older version. The CI is expected to pull the latest version each time.

**Comment by travisn** [comment]
Re-running the tests passed now. A newer latest-devel-reef tag was generated since the latest daily tests were last run, so I believe the tag from yesterday just hadn't picked up the changes yet for some reason. It all looks good now, thanks!
