### ISSUE TITLE
helm repo index was not updated for v0.7

### ISSUE THREAD

**Issue by jbw976** [rook/rook#1517]
Is this a bug report or feature request?
* Bug Report

**Bug Report**

What happened:  I ran the rook/promote target on Jenkins to promote v0.7 to alpha, but the index files on https://charts.rook.io/ (both alpha and master) have not been updated to v0.7.

What you expected to happen:  The alpha and master helm repos to have been updated to v0.7.

```
$ helm repo add rook-alpha https://charts.rook.io/alpha
"rook-alpha" has been added to your repositories
$ helm search rook
NAME               VERSION    DESCRIPTION
rook-alpha/rook    v0.6.2     File, Block, and Object Storage Services for yo...
```

**Comment by jbw976** [comment]
The last version that made it into the helm repo index was `v0.6.0-202.gdb919ac`, corresponding to this commit: https://github.com/rook/rook/commit/db919acdf742f9a93028b7c073f9d3e24f3fce29

This is right around the time when the domain names were transferring over to the CNCF.  My best guess is that the https://charts.rook.io/ domain and S3 bucket transferred over to the CNCF, so the [`promote.helm` target](https://github.com/rook/rook/blob/master/build/release/Makefile#L135) is no longer using the correct S3 credentials to sync with that bucket.

I don't see direct evidence of that in the [promote pipeline logs on jenkins](https://jenkins.rook.io/blue/rest/organizations/jenkins/pipelines/release/pipelines/promote/branches/release-0.7/runs/3/nodes/13/steps/18/log/?start=0), but I do have my suspicions that this is the issue.  @bassam how can we follow up on this lead?

**Comment by pierreozoux** [comment]
I think it is now fixed.

Another (related) question, as rook is considered beta, shouldn't we add the beta channel there?

**Comment by dev10** [comment]
Unfortunately It's still not fixed. 
Also, you can download this: [https://charts.rook.io/alpha/rook-v0.6.2.tgz](https://charts.rook.io/alpha/rook-v0.6.2.tgz) 
but not this [https://charts.rook.io/alpha/rook-v0.7.0.tgz](https://charts.rook.io/alpha/rook-v0.7.0.tgz), even though both are [listed](https://charts.rook.io/alpha). 
The latter link goes to an empty directory.

**Comment by pierreozoux** [comment]
Yes, realized later too :/

How could we help to fix that?

**Comment by steven-sheehy** [comment]
Seems like this ticket fixes it for the next release, but the helm index is still not updated for 0.7. Is there any way someone can manually update it?

**Comment by jbw976** [comment]
@steven-sheehy. we will be running a new minor release 0.7.1 that will fix this issue for 0.7.  We are having issues with our build instance which has delayed this release a bit.  In the meantime, newer builds in master have already started publishing helm charts again if that works for you.

**Comment by whisper-bye** [comment]
follow the docs https://github.com/rook/rook/blob/master/Documentation/helm-operator.md

$ helm search rook

```
NAME            	CHART VERSION     	APP VERSION	DESCRIPTION
rook-master/rook	v0.7.0-10.g3bcee98	           	File, Block, and Object Storage Services for yo...
```

$ helm install rook-master/rook --name rook --version v0.7.0-10.g3bcee98

```
Error: render error in "rook/templates/wait-on-resources-job.yaml": template: rook/templates/wait-on-resources-job.yaml:25:100: executing "rook/templates/wait-on-resources-job.yaml" at <semverCompare ">=1.7...>: error calling semverCompare: Invalid Semantic Version
```

**Comment by pierreozoux** [comment]
@whisper-bye you still need to wait the 0.7.1 release.

**Comment by jbw976** [comment]
@whisper-bye @pierreozoux this may actually be an issue that is not related to the still pending 0.7.1 release.  The line that appears to be failing is https://github.com/rook/rook/blob/release-0.7/cluster/charts/rook/templates/wait-on-resources-job.yaml#L25 that is attempting to compare the Kubernetes version against "1.7".  I don't know a lot about how the `semverCompare` check works, but from the output it looks like it is getting empty strings for the k8s version.  This may be the `semverCompare` documentation here: http://masterminds.github.io/sprig/semver.

Any ideas on how to troubleshoot the possibility that `.Capabilities.KubeVersion.Major` and `Capabilities.KubeVersion.Minor`  may be empty strings in a Helm chart?

**Comment by TimJones** [comment]
@whisper-bye can you post the output of `helm version` and `kubectl version`??

**Comment by whisper-bye** [comment]
@TimJones yes, sure.

$ helm version
```
Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
```

$ kubectl version
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:51:54Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2018-01-26T19:04:38Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by jbw976** [comment]
Thanks @whisper-bye, that confirms that the Kubernetes server version is indeed blank for major and minor fields.  That's what's causing the semver check to fail.

@TimJones can that condition be handled in a template, or is this an invalid configuration?

@whisper-bye how did you deploy your kubernetes cluster?  Not sure i've seen blank major/minor versions before.

**Comment by whisper-bye** [comment]
@jbw976 minikube for gitlab devops env.

$ minikube version
```
minikube version: v0.25.0
```

**Comment by TimJones** [comment]
@whisper-bye Seems like you're running into kubernetes/minikube#2505

Not sure how it's an upstream issue though, as in my bare-metal & aws clusters version reporting works as expected.

@jbw976  As for a workaround, we could simply skip the whole wait job if we don't have `.Capabilities.KubeVersion.Major` or `.Capabilities.KubeVersion.Minor` (or assume to wait for CRDs but I don't really like that idea).

**Comment by jbw976** [comment]
@TimJones thanks for your input. how simple of a change to the job would that be to just skip if we don't have version numbers? is that something you could open a PR for?

**Comment by TimJones** [comment]
@jbw976 It's a simple 2 line fix. I'll create a PR shortly.

**Comment by rossedman** [comment]
@TimJones @jbw976 I am running into this error and my metadata output is not empty, so my install is trying not to skip the wait job. This chart worked for me not too long ago, old versions aren't cached or saved?

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.3-rancher1", GitCommit:"d5aea0c6d208786ae608d4154669de6e9319bdc7", GitTreeState:"clean", BuildDate:"2018-02-13T17:28:50Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

```
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```

**Comment by TimJones** [comment]
@rossedman Thanks for the extra info!
@jbw976 It looks like there are more permutations of versions than I accounted for. `GitVersion` looks more stable (if the `v` prefix is dropped), but I could end up just chasing all edge-cases as the bug reports come in...

**Comment by jbw976** [comment]
@TimJones @rossedman I've opened https://github.com/rook/rook/issues/1567 to track this in its own issue.

**Comment by jbw976** [comment]
@rossedman we do keep previous versions available, you should be able to install using the `--version` argument that is mentioned in https://rook.io/docs/rook/master/helm-operator.html:
```
helm install rook-alpha/rook --version v0.6.2
```
