### ISSUE TITLE
Operator logs a lot failedDeleteThreshold messages

### ISSUE THREAD

**Issue by tboerger** [rook/rook#1592]
Is this a bug report or feature request?

* Bug Report

**Bug Report**

What happened:

The operator complains over and over again that it failed to delete a volume:

```
E0322 21:05:10.853254       7 controller.go:598] Exceeded failedDeleteThreshold threshold: 15, for volume "pvc-be4c05d1-292d-11e8-98b0-96000007bc30", provisioner will not attempt retries for this volume
E0322 21:05:10.853290       7 controller.go:598] Exceeded failedDeleteThreshold threshold: 15, for volume "pvc-1273c0f3-1b94-11e8-9e81-96000007bc32", provisioner will not attempt retries for this volume
E0322 21:05:10.853345       7 controller.go:598] Exceeded failedDeleteThreshold threshold: 15, for volume "pvc-8eeab4cb-212d-11e8-9e81-96000007bc32", provisioner will not attempt retries for this volume
E0322 21:05:10.853367       7 controller.go:598] Exceeded failedDeleteThreshold threshold: 15, for volume "pvc-2081555d-26bb-11e8-98b0-96000007bc30", provisioner will not attempt retries for this volume
E0322 21:05:25.853092       7 controller.go:598] Exceeded failedDeleteThreshold threshold: 15, for volume "pvc-be4c05d1-292d-11e8-98b0-96000007bc30", provisioner will not attempt retries for this volume
E0322 21:05:25.853129       7 controller.go:598] Exceeded failedDeleteThreshold threshold: 15, for volume "pvc-1273c0f3-1b94-11e8-9e81-96000007bc32", provisioner will not attempt retries for this volume
E0322 21:05:25.853158       7 controller.go:598] Exceeded failedDeleteThreshold threshold: 15, for volume "pvc-8eeab4cb-212d-11e8-9e81-96000007bc32", provisioner will not attempt retries for this volume
E0322 21:05:25.853170       7 controller.go:598] Exceeded failedDeleteThreshold threshold: 15, for volume "pvc-2081555d-26bb-11e8-98b0-96000007bc30", provisioner will not attempt retries for this volume
E0322 21:05:25.853214       7 controller.go:598] Exceeded failedDeleteThreshold threshold: 15, for volume "pvc-509f0f63-2923-11e8-98b0-96000007bc30", provisioner will not attempt retries for this volume
E0322 21:05:25.853273       7 controller.go:598] Exceeded failedDeleteThreshold threshold: 15, for volume "pvc-1ac8a044-1b94-11e8-9e81-96000007bc32", provisioner will not attempt retries for this volume
E0322 21:05:40.853273       7 controller.go:598] Exceeded failedDeleteThreshold threshold: 15, for volume "pvc-509f0f63-2923-11e8-98b0-96000007bc30", provisioner will not attempt retries for this volume
E0322 21:05:40.853337       7 controller.go:598] Exceeded failedDeleteThreshold threshold: 15, for volume "pvc-1ac8a044-1b94-11e8-9e81-96000007bc32", provisioner will not attempt retries for this volume
E0322 21:05:40.853360       7 controller.go:598] Exceeded failedDeleteThreshold threshold: 15, for volume "pvc-be4c05d1-292d-11e8-98b0-96000007bc30", provisioner will not attempt retries for this volume
E0322 21:05:40.853379       7 controller.go:598] Exceeded failedDeleteThreshold threshold: 15, for volume "pvc-1273c0f3-1b94-11e8-9e81-96000007bc32", provisioner will not attempt retries for this volume
E0322 21:05:40.853395       7 controller.go:598] Exceeded failedDeleteThreshold threshold: 15, for volume "pvc-8eeab4cb-212d-11e8-9e81-96000007bc32", provisioner will not attempt retries for this volume
E0322 21:05:40.853413       7 controller.go:598] Exceeded failedDeleteThreshold threshold: 15, for volume "pvc-2081555d-26bb-11e8-98b0-96000007bc30", provisioner will not attempt retries for this volume
```

What you expected to happen:

That the log doesn't get flooded by the above message over and over again

How to reproduce it (minimal and precise):

I don't know how this can be reproduced, but the PVC is not listed anymore:

```
# k get pvc --all-namespaces | grep -c pvc-2081555d-26bb-11e8-98b0-96000007bc30
0

# k get pvc --all-namespaces | grep -c pvc-1273c0f3-1b94-11e8-9e81-96000007bc32
0
```

But it can be found on etcd:

```
# etcdctl ls --recursive /registry | grep pvc-2081555d-26bb-11e8-98b0-96000007bc30
/registry/persistentvolumes/pvc-2081555d-26bb-11e8-98b0-96000007bc30
/registry/rook.io/volumeattachments/rook-system/pvc-2081555d-26bb-11e8-98b0-96000007bc30
/registry/events/default/pvc-2081555d-26bb-11e8-98b0-96000007bc30.151e569a8b1c82a3

# etcdctl ls --recursive /registry | grep pvc-1273c0f3-1b94-11e8-9e81-96000007bc32
/registry/persistentvolumes/pvc-1273c0f3-1b94-11e8-9e81-96000007bc32
/registry/events/default/pvc-1273c0f3-1b94-11e8-9e81-96000007bc32.151e569a8ae9662d
```

**Environment**:
* OS (e.g. from /etc/os-release):

NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"

* Kernel (e.g. `uname -a`):

Linux buri 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* Cloud provider or hardware configuration:

on premise

* Rook version (use `rook version` inside of a Rook Pod):

v0.7.1

* Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-16T03:15:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):

bare-metal

* Ceph status (use `ceph health` in the [Rook toolbox](https://Rook.io/docs/Rook/master/toolbox.html)):

HEALTH_OK

**Comment by dimm0** [comment]
Same thing here

**Comment by jbw976** [comment]
I believe that the root cause for this was #1721, which is fixed in the upcoming v0.8 milestone.  I'm going to close this for now and re-open later on if we still this in current master builds or after v0.8 is released. Thanks!

**Comment by dimm0** [comment]
Still seeing this in 0.8.2
Deleting a volume manually can take a couple hours.
