### ISSUE TITLE
Malformed ADDR in `ceph orch host ls`

### ISSUE THREAD

**Issue by tahajahangir** [rook/rook#16482]
### Deviation from Expected Behavior

When running a Ceph NFS server with the `rook` orchestrator (`ceph orch set backend rook`), I've found that the `ceph nfs cluster info` command fails:

```bash
$ ceph nfs cluster info
Error EINVAL: Cannot resolve IP for host 192.168.0.12/ceph-node-02: [Errno -2] Name or service not known
```

The error message indicates that the `ceph-mgr` module is trying to resolve the hostname `192.168.0.12/ceph-node-02`, which is an invalid format. It seems the module gets this invalid address format from the orchestrator's host list, as shown below:

```bash
$ ceph orch host ls
HOST          ADDR                       LABELS  STATUS  
ceph-node-01  192.168.0.11/ceph-node-01                  
ceph-node-02  192.168.0.12/ceph-node-02                  
ceph-node-03  192.168.0.13/ceph-node-03                  
ceph-node-04  192.168.0.14/ceph-node-04                  
ceph-node-05  192.168.0.15/ceph-node-05                  
ceph-node-06  192.168.0.16/ceph-node-06           
...
```

The `ADDR` field is incorrectly populated with a combined `IP/hostname` string instead of just the IP address.

-----

### Expected Behavior

In other `cephadm`-managed clusters, the `ADDR` field contains only the IP address. I believe correcting the `ADDR` format in the `ceph orch host ls` output will resolve this issue, though it's possible another fix may be required to make `ceph nfs cluster info` work.

-----

### Reproduction Steps

This issue is reproducible in any simple cluster where `CephFilesystem` and `CephNFS` are both configured using `rook`.

-----

### Environment

  * **OS:** Debian 12
  * **Rook Version:** `v1.14.3` (Note: This is a production environment running an older version. I've not found any related issues/pull requests that seem to address this in more recent versions.)
  * **Ceph Version:** `ceph version 18.2.7` (Reef stable)
  * **Kubernetes Version:** `v1.32.5` (Vanilla)

**Comment by tahajahangir** [comment]
Can someone take a look at this issue?

**Comment by subhamkrai** [comment]
@tahajahangir looks like the ceph command error in ouput should be fixed in ceph repo, I don't think rook control this command behaviour `ceph nfs cluster info`. cc @BlaineEXE

**Comment by BlaineEXE** [comment]
The rook orchestrator plugin in Ceph is unmaintained, and it is often broken. At best, it is a read-only interface, but it still doesn't always work. Where it is broken, this is a Ceph issue and should be filed as a Ceph bug.

When discussions have come up about the many user issues like this, I have always pushed to remove the rook plugin from the Ceph codebase so that it isn't confusing to users. My opinion is that it would be better for Ceph to not have the Rook orchestrator plugin rather than have one that is unmaintained and causes repeated user confusion like this. I have been overruled in discussions that come up about it.

My suggestion to Rook users is to avoid the orchestrator interface in Ceph. If a user really wants to use the interface, they need to be prepared for parts of the interface to be broken (like this) and prepared for things to break in Ceph updates and major upgrades.

Ceph does allow community pull requests, so if any user is experienced with Kubernetes+Rook and with Python (used for Ceph's module code), that might be an avenue for an issue to be fixed. Also worth keeping in mind: Ceph's bug fix release timeline is usually ~4 months.

-----

For NFS specifically, the `ceph nfs export ...` subcommands work. Others rely on unmaintained orchestrator code.

**Comment by the-nando** [comment]
@tahajahangir did you happen to find a workaround for this? I'm running into the same issue (Ceph v20.2.0, Rook 1.18.7)

That `<host>/<ip>` comes from [here](https://github.com/ceph/ceph/blob/v20.3.0/src/pybind/mgr/rook/rook_cluster.py#L897)

**Comment by tahajahangir** [comment]
> [@tahajahangir](https://github.com/tahajahangir) did you happen to find a workaround for this? I'm running into the same issue (Ceph v20.2.0, Rook 1.18.7)

I worked around it outside of Rook. (in the client side)
