### ISSUE TITLE
`df --type ceph`: invalid character '-' after top-level value

### ISSUE THREAD

**Issue by anguslees** [rook/rook#2165]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

(I see this error mentioned in passing in other issues, but I didn't find one that tackled this directly)

kubelet logs include:
```
Sep 27 05:31:07 localhost kubelet-wrapper[11227]: E0927 05:31:07.618429   11227 driver-call.go:237] Failed to unmarshal output for command: unmount, output: "2018-09-27 05:31:07.191711 I | exec: Running command: df --type ceph /var/lib/kubelet/pods/95461479-c216-11e8-bcf0-02030782ac80/volumes/ceph.rook.io~rook/oe-scratch\n2018-09-27 05:46:43.808596 I | Filesystem                                                 1K-blocks     Used Available Use%!M(MISSING)ounted on\n2018-09-27 05:46:43.808659 I | 10.107.25.147:6790,10.109.173.79:6790,10.104.85.255:6790:/ 151678976 49410048 102268928  33%!/(MISSING)var/lib/kubelet/pods/95461479-c216-11e8-bcf0-02030782ac80/volumes/ceph.rook.io~rook/oe-scratch\n{\"status\":\"Success\"}\n", error: invalid character '-' after top-level value
```

**Expected behavior:**

This command should produce (pure json) output that can be parsed by kubelet (ie: just the json output), and there should be no such error logged.  Additional logging output (if any) should be written somewhere else.

**Environment**:
* Cloud provider or hardware configuration: bare-metal
* Rook version (use `rook version` inside of a Rook Pod): 0.8.2
* Kubernetes version (use `kubectl version`): 1.8.x
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm + bare-metal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html)):

**Comment by galexrt** [comment]
@anguslees This should be fixed by #2161. Which will end up in v0.8.3, which will probably be released in the next days this week.

**Comment by jbw976** [comment]
I'm not sure about that @galexrt, the output says `Failed to unmarshal output for command: unmount` and the change in #2161 only affects the mount path. This may be something different.  @anguslees do you have debug logging turned on?

**Comment by galexrt** [comment]
@jbw976 @dimm0 mentioned he had this issue too https://github.com/rook/rook/issues/2149#issuecomment-424424133 but as he closed the issue now I assumed the error was also solved by that as far as I understand.

**Comment by anguslees** [comment]
I still see this in the kubelet logs (3 minutes ago) after the upgrade to rook 0.8.3 earlier today:
```
Oct 02 08:49:16 localhost kubelet-wrapper[704]: I1002 08:49:16.797291     704 reconciler.go:191] operationExecutor.UnmountVolume started for volume "volume-0" (UniqueName: "flexvolume-ceph.rook.io/rook/b6d6acf7-c61e-11e8-88b4-02030782ac80-oe-scratch") pod "b6d6acf7-c61e-11e8-88b4-02030782ac80" (UID: "b6d6acf7-c61e-11e8-88b4-02030782ac80")
Oct 02 08:49:17 localhost kubelet-wrapper[704]: E1002 08:49:17.033424     704 driver-call.go:237] Failed to unmarshal output for command: unmount, output: "2018-10-02 08:49:17.016507 I | exec: Running command: df --type ceph /var/lib/kubelet/pods/b6d6acf7-c61e-11e8-88b4-02030782ac80/volumes/ceph.rook.io~rook/oe-scratch\n2018-10-02 08:49:17.022645 I | Filesystem                                                 1K-blocks     Used Available Use%!M(MISSING)ounted on\n2018-10-02 08:49:17.022830 I | 10.104.85.255:6790,10.111.143.113:6790,10.109.151.1:6790:/ 284844032 49410048 235433984  18%!/(MISSING)var/lib/kubelet/pods/b6d6acf7-c61e-11e8-88b4-02030782ac80/volumes/ceph.rook.io~rook/oe-scratch\n{\"status\":\"Failure\",\"message\":\"failed to unmount cephfs volume at /var/lib/kubelet/pods/b6d6acf7-c61e-11e8-88b4-02030782ac80/volumes/ceph.rook.io~rook/oe-scratch: Unmount failed: exit status 32\\nUnmounting arguments: /var/lib/kubelet/pods/b6d6acf7-c61e-11e8-88b4-02030782ac80/volumes/ceph.rook.io~rook/oe-scratch\\nOutput: umount: /var/lib/kubelet/pods/b6d6acf7-c61e-11e8-88b4-02030782ac80/volumes/ceph.rook.io~rook/oe-scratch: target is busy\\n        (In some cases useful info about processes that\\n         use the device is found by lsof(8) or fuser(1).)\\n\\n\"}\n", error: invalid character '-' after top-level value
Oct 02 08:49:17 localhost kubelet-wrapper[704]: W1002 08:49:17.033549     704 driver-call.go:145] FlexVolume: driver call failed: executable: /var/lib/kubelet/volumeplugins/ceph.rook.io~rook/rook, args: [unmount /var/lib/kubelet/pods/b6d6acf7-c61e-11e8-88b4-02030782ac80/volumes/ceph.rook.io~rook/oe-scratch], error: exit status 1, output: "2018-10-02 08:49:17.016507 I | exec: Running command: df --type ceph /var/lib/kubelet/pods/b6d6acf7-c61e-11e8-88b4-02030782ac80/volumes/ceph.rook.io~rook/oe-scratch\n2018-10-02 08:49:17.022645 I | Filesystem                                                 1K-blocks     Used Available Use%!M(MISSING)ounted on\n2018-10-02 08:49:17.022830 I | 10.104.85.255:6790,10.111.143.113:6790,10.109.151.1:6790:/ 284844032 49410048 235433984  18%!/(MISSING)var/lib/kubelet/pods/b6d6acf7-c61e-11e8-88b4-02030782ac80/volumes/ceph.rook.io~rook/oe-scratch\n{\"status\":\"Failure\",\"message\":\"failed to unmount cephfs volume at /var/lib/kubelet/pods/b6d6acf7-c61e-11e8-88b4-02030782ac80/volumes/ceph.rook.io~rook/oe-scratch: Unmount failed: exit status 32\\nUnmounting arguments: /var/lib/kubelet/pods/b6d6acf7-c61e-11e8-88b4-02030782ac80/volumes/ceph.rook.io~rook/oe-scratch\\nOutput: umount: /var/lib/kubelet/pods/b6d6acf7-c61e-11e8-88b4-02030782ac80/volumes/ceph.rook.io~rook/oe-scratch: target is busy\\n        (In some cases useful info about processes that\\n         use the device is found by lsof(8) or fuser(1).)\\n\\n\"}\n"
Oct 02 08:49:17 localhost kubelet-wrapper[704]: E1002 08:49:17.033792     704 nestedpendingoperations.go:263] Operation for "\"flexvolume-ceph.rook.io/rook/b6d6acf7-c61e-11e8-88b4-02030782ac80-oe-scratch\" (\"b6d6acf7-c61e-11e8-88b4-02030782ac80\")" failed. No retries permitted until 2018-10-02 08:51:19.033726872 +0000 UTC m=+31938.006293192 (durationBeforeRetry 2m2s). Error: "UnmountVolume.TearDown failed for volume \"volume-0\" (UniqueName: \"flexvolume-ceph.rook.io/rook/b6d6acf7-c61e-11e8-88b4-02030782ac80-oe-scratch\") pod \"b6d6acf7-c61e-11e8-88b4-02030782ac80\" (UID: \"b6d6acf7-c61e-11e8-88b4-02030782ac80\") : invalid character '-' after top-level value"
```

**Comment by rootfs** [comment]
@anguslees were you using cephfs by any chance?

**Comment by anguslees** [comment]
> @anguslees were you using cephfs by any chance?

Yes, this is a cephfs volume (and it is mounting successfully at the host level, but then containers fail to run due to #2177. Containers are going straight from "creating" to "terminating", just in case that edge on the state machine is relevant here)

I have every reason to believe the command is this line of code:
https://github.com/rook/rook/blob/d7b03a59c1ade92077117ba702fab2075a3ec236/cmd/rookflex/cmd/unmount.go#L56

It's getting logged due to https://github.com/rook/rook/blob/3b7041a27ae8a3dfe202c48dfbec61e9a41e58fc/pkg/util/exec/exec.go#L234
(aside: slightly odd semantics to log at debug-level if `debug` bool param is true, but info-level otherwise.  I think some of the callers might mistakenly expect it to not log at all if `debug` param is false - and we're not globally at log-level=debug.  Perhaps change this param to a `capnslog.LogLevel` enum?).

The core issue seems to be that `pkg/util/exec/exec.go` logs through capnslog: https://github.com/rook/rook/blob/d7b03a59c1ade92077117ba702fab2075a3ec236/pkg/util/exec/exec.go#L184
... but for `cmd/rookflex` (at least), it looks like logging output is expected to go through a remote `Controller.Log` RPC:
https://github.com/rook/rook/blob/3b7041a27ae8a3dfe202c48dfbec61e9a41e58fc/cmd/rookflex/cmd/root.go#L78

If you want to continue to use `pkg/util/exec` here, then I think the fix needs to be for `cmd/rookflex/...` to divert `capnslog` output via the same RPC channel too.  Digging through capnslog, it looks like you do that by creating a custom `capnslog.Formatter`, and passing it to `capnslog.SetFormatter()`.

Aside: there's also a bug in `exec.logOutput` that that is responsible for mangling `%` in the command output into `%!M(MISSING)` (see my logged output examples earlier in this issue)
https://github.com/rook/rook/blob/d7b03a59c1ade92077117ba702fab2075a3ec236/pkg/util/exec/exec.go#L206
```patch
	for in.Scan() {
		lastLine = in.Text()
-		childLogger.Infof(lastLine)
+		childLogger.Info(lastLine)
	}
```
