### ISSUE TITLE
OSDs crashlooping after being OOMKilled: bind unable to bind

### ISSUE THREAD

**Issue by dimm0** [rook/rook#3992]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Updated ceph from v14.2.2-20190722 to v14.2.4-20190917, which seems to have made some changes in memory management, and nodes started getting system OOMKilles followed by OSDs crashlooping.

```
2019-09-26 01:20:10.118 7f70aa104dc0 -1 Falling back to public interface
2019-09-26 01:20:10.128 7f70aa104dc0 -1  Processor -- bind unable to bind to v2:10.244.15.18:7300/0 on any port in range 6800-7300: (99) Cannot assign requested address
2019-09-26 01:20:10.128 7f70aa104dc0 -1  Processor -- bind was unable to bind. Trying again in 5 seconds
2019-09-26 01:20:15.137 7f70aa104dc0 -1  Processor -- bind unable to bind to v2:10.244.15.18:7300/0 on any port in range 6800-7300: (99) Cannot assign requested address
2019-09-26 01:20:15.137 7f70aa104dc0 -1  Processor -- bind was unable to bind. Trying again in 5 seconds
2019-09-26 01:20:20.144 7f70aa104dc0 -1  Processor -- bind unable to bind to v2:10.244.15.18:7300/0 on any port in range 6800-7300: (99) Cannot assign requested address
2019-09-26 01:20:20.144 7f70aa104dc0 -1  Processor -- bind was unable to bind after 3 attempts: (99) Cannot assign requested address
```

**How to reproduce it (minimal and precise):**
Get an OSD OOMKilled by system

* Rook version (use `rook version` inside of a Rook Pod):
1.1.1
* Storage backend version (e.g. for ceph do `ceph -v`):
v14.2.4-20190917
* Kubernetes version (use `kubectl version`):
1.15.1

**Comment by dimm0** [comment]
Current status:
I started downgrading back to v14.2.2-20190722, and new pods started crashlooping with message:

```
2019-09-26 03:08:14.880843 I | terminate called after throwing an instance of 'ceph::buffer::end_of_buffer'
2019-09-26 03:08:14.880910 I |   what():  buffer::end_of_buffer
failed to start osd. Failed to complete '': signal: aborted.
```

I stopped downgrading by scaling down the operator.
Also both CEphFS MDS'es (still 14.2.4) started crashlooping, and I manually downgraded those to v14.2.2-20190722. Now both are in reserve status for some reason.

**Comment by dimm0** [comment]
@liewegas I'd appreciate help in fixing this

**Comment by dimm0** [comment]
Tried reverting one OSD back manually to 14.2.4 by changing the image, it stayed up for 5 mins. Trying to update all back to 14.2.4.

**Comment by leseb** [comment]
Are you using `rook-config-overrides`?

**Comment by dimm0** [comment]
No, deleted all before that

**Comment by leseb** [comment]
Can you share the ceph.conf from `/var/lib/rook/ceph`?

**Comment by dimm0** [comment]
Here's rook.config from working (not crashlooping) /var/lib/rook/osd197/rook.config 14.2.4 :

```
[root@rook-ceph-osd-197-759dcc9f54-9rvx5 /]# cat /var/lib/rook/osd197/rook.config
[global]
fsid                      = 90a5afad-c313-4e49-9b5f-317100c6930e
run dir                   = /var/lib/rook/osd197
mon initial members       = hq ib hu hy hx
mon host                  = v1:10.98.219.60:6789,v1:10.97.145.86:6789,v1:10.97.145.87:6789,v1:10.101.94.248:6789,v1:10.96.77.51:6789
public addr               = 10.244.82.48
cluster addr              = 10.244.82.48
mon keyvaluedb            = rocksdb
mon_allow_pool_delete     = true
mon_max_pg_per_osd        = 1000
debug default             = 0
debug rados               = 0
debug mon                 = 0
debug osd                 = 0
debug bluestore           = 0
debug filestore           = 0
debug journal             = 0
debug leveldb             = 0
filestore_omap_backend    = rocksdb
osd pg bits               = 11
osd pgp bits              = 11
osd pool default size     = 1
osd pool default min size = 1
osd pool default pg num   = 100
osd pool default pgp num  = 100
osd objectstore           = bluestore
crush location            = root=default host=prp-dtn-noc-ucsb-edu
rbd_default_features      = 3
fatal signal handlers     = false

[osd.197]
keyring                  = /var/lib/rook/osd197/keyring
bluestore block path     = /dev/disk/by-partuuid/de8be508-8877-4bb3-98f2-6e8dd9dc8c7c
bluestore block wal path = /dev/disk/by-partuuid/bda15fb8-0f26-4e66-bc77-e57fecee4aa5
bluestore block db path  = /dev/disk/by-partuuid/06fd6021-36e5-405c-b532-7cec02ac1ec2
```

I don't see /var/lib/rook/ceph

**Comment by leseb** [comment]
Are you using HostNetworking?
Ok, so the error here: `bind unable to bind to v2:10.244.15.18:7300/0`, is it a host or container IP?

**Comment by dimm0** [comment]
That's private container IP, no HostNetworking

**Comment by dimm0** [comment]
My current status: The operator updated all OSDs back to 14.2.4, and now I see the can't bind issue again.
Also 2nd problem: both my MDSs are in standby.

**Comment by dimm0** [comment]
The error message with port bind shows a different (private) IP than the pod has
Maybe IP is not updated somehow? It would make sense it can't bind the port, since there's no such interface
What tells ceph the IP to bind to?

**Comment by dimm0** [comment]
Ok, I think I know what's happening..
OSDs are getting killed with OOMKiller, the container restarts, and then ceph is trying to start on a wrong IP

**Comment by dimm0** [comment]
Hmm... The good ones are also having the wrong IP in the config.
Where is the ceph map-to IP coming from?

**Comment by dimm0** [comment]
Ok, the issue was related to OSDs getting OOMKilled. I restarted all with MemoryLimit, and now there are no crashloops.

**Comment by travisn** [comment]
@batrick @ajarr What would cause both MDS daemons to stay in standby mode instead of one of them going to active? Could this related to OSDs going down? They are back up now though.

**Comment by dimm0** [comment]
As a result of high memory pressure, 2 OSDs got damaged rocksdb, and one PG is currently down. The PG belongs to cephFS, so cephFS is reported damaged

```
            "blocked": "peering is blocked due to down osds",
            "down_osds_we_would_probe": [
                59
            ],
            "peering_blocked_by": [
                {
                    "osd": 59,
                    "current_lost_at": 0,
                    "comment": "starting or marking this osd lost may let us proceed"
                }
            ]
```

I'm not sure if I can mark the OSD lost without losing data... Please advise

@ukernel could you help plz?

**Comment by dimm0** [comment]
Trying to export the PG and re-import somewhere else. There's no PG 23.6d7, but there is 23.6d7s1, which is I suppose shard 1 of it. Is that right?

**Comment by batrick** [comment]
> @batrick @ajarr What would cause both MDS daemons to stay in standby mode instead of one of them going to active? Could this related to OSDs going down? They are back up now though.

Only explanation is that no file system was created yet.

**Comment by dimm0** [comment]
There's almost a petabyte of data in it..

**Comment by batrick** [comment]
> Also both CEphFS MDS'es (still 14.2.4) started crashlooping, and I manually downgraded those to v14.2.2-20190722. Now both are in reserve status for some reason.

Can you provide more information about this? Please include `ceph status`, `ceph fs dump`, and a snippet of the leader monitor's logs would be helpful.

**Comment by dimm0** [comment]
As I wrote above, the PG 23.6d7 from cephFS data pool is missing something from corrupted OSD (which doesn't start)
I used the ceph-objectstore-tool to export the PG from corrupted OSD, and now importing it to a random other OSD. Is that a right thing to do?
Am I getting it right that ceph will magically discover that imported newer PG and will forget about the broken OSD?

**Comment by dimm0** [comment]
Ok, the PG is imported to osd 51.. How can I tell ceph to find it there?

**Comment by dimm0** [comment]
```
[root@fiona8-0 /]# ceph status
  cluster:
    id:     90a5afad-c313-4e49-9b5f-317100c6930e
    health: HEALTH_ERR
            1 filesystem is degraded
            1 filesystem is offline
            1 mds daemon damaged
            noout flag(s) set
            2 large omap objects
            Reduced data availability: 1 pg inactive, 1 pg down
            Degraded data redundancy: 17568237/1460638721 objects degraded (1.203%), 178 pgs degraded, 178 pgs undersized
            38 pgs not deep-scrubbed in time
            3 pgs not scrubbed in time

  services:
    mon: 5 daemons, quorum hq,hu,hx,hy,ib (age 2h)
    mgr: a(active, since 2h)
    mds: nautilusfs:0/1 2 up:standby, 1 damaged
    osd: 171 osds: 169 up (since 18m), 169 in (since 101m); 178 remapped pgs
         flags noout
    rgw: 4 daemons active (rooks3.a, rooks3.b, rooks3.c, rooks3.d)

  data:
    pools:   10 pools, 4244 pgs
    objects: 320.39M objects, 450 TiB
    usage:   917 TiB used, 627 TiB / 1.5 PiB avail
    pgs:     0.024% pgs not active
             17568237/1460638721 objects degraded (1.203%)
             4065 active+clean
             162  active+undersized+degraded+remapped+backfill_wait
             16   active+undersized+degraded+remapped+backfilling
             1    down

  io:
    client:   1.2 MiB/s rd, 56 MiB/s wr, 459 op/s rd, 748 op/s wr
    recovery: 246 MiB/s, 162 objects/s
```

```
[root@fiona8-0 /]# ceph fs dump
dumped fsmap epoch 616227
e616227
enable_multiple, ever_enabled_multiple: 0,0
compat: compat={},rocompat={},incompat={1=base v0.20,2=client writeable ranges,3=default file layouts on dirs,4=dir inode in separate object,5=mds uses versioned encoding,6=dirfrag is stored in omap,8=no anchor table,9=file layout v2,10=snaprealm v2}
legacy client fscid: 1

Filesystem 'nautilusfs' (1)
fs_name	nautilusfs
epoch	616227
flags	3c
created	2018-10-17 15:18:08.217006
modified	2019-09-27 00:28:43.861743
tableserver	0
root	0
session_timeout	60
session_autoclose	300
max_file_size	1099511627776
min_compat_client	-1 (unspecified)
last_failure	0
last_failure_osd_epoch	1014068
compat	compat={},rocompat={},incompat={1=base v0.20,2=client writeable ranges,3=default file layouts on dirs,4=dir inode in separate object,5=mds uses versioned encoding,6=dirfrag is stored in omap,8=no anchor table,9=file layout v2,10=snaprealm v2}
max_mds	1
in	0
up	{}
failed
damaged	0
stopped	1
data_pools	[23]
metadata_pool	22
inline_data	disabled
balancer
standby_count_wanted	1


Standby daemons:

212361799:	[v2:10.244.12.39:6800/1473321974,v1:10.244.12.39:6801/1473321974] 'nautilusfs-b' mds.-1.0 up:standby seq 2
212369013:	[v2:10.244.106.4:6800/691839442,v1:10.244.106.4:6801/691839442] 'nautilusfs-a' mds.-1.0 up:standby seq 2
```

```
cluster 2019-09-27 00:28:43.990502 mon.hq (mon.0) 114886 : cluster [DBG] fsmap nautilusfs:0/1 2 up:standby, 1 damaged
```

**Comment by batrick** [comment]
The MDS rank is damaged so no MDS will take the rank until it is marked repaired. You should only consider doing that after getting your PGs active. I don't have experience with that so I have no recommendations.

**Comment by dimm0** [comment]
Thanks for clarifying this part

**Comment by leseb** [comment]
It seems the original issue has been resolved, so I'm closing this.

**Comment by dimm0** [comment]
The original issue is still there. I eliminated the cause of OOMKill, but if they are OOMKilled again, the OSDs will be unable to restart.

**Comment by leseb** [comment]
Why are they being OOMKilled?

**Comment by dimm0** [comment]
Use too much memory, if container does not have mem limit

**Comment by dimm0** [comment]
If there are too many writes and disk is slow, it goes to cache

**Comment by leseb** [comment]
Then I don't how that's an issue with Rook at this point 🤔

**Comment by dimm0** [comment]
If process is killed by system the container restarts automatically, and should continue working.
But rook somehow makes it think it has a different IP than it really has, after the restart

**Comment by dimm0** [comment]
The issue is not that OSDs are being OOMKilled, but that after they are OOMKilled, the whole pod needs to be manually deleted to start normally, while it should just restart the container and keep working

**Comment by dimm0** [comment]
And it's not a new issue, I've seen it before occasionally. But it was rare, and I was killing pods manually without knowing what's causing this

**Comment by leseb** [comment]
So if I summarize:

* the ceph-osd process get OOM
* the pod restarts but the ceph.conf of the OSD has a wrong IP, thus it cannot bind

But I feel like you're saying pods don't get restarted, am I missing something? Why do you need to manually restart it? Doesn't Kubernetes do its job here?

**Comment by dimm0** [comment]
containers inside the pod can restart without the whole pod restarting.. if main process dies, only that container restarts. pod keeps working.

**Comment by dimm0** [comment]
since there can be many main (not init) containers in a pod, there's no point to kill them all I guess if one dies

**Comment by leseb** [comment]
But AFAIK, we only have one container per pod, one OSD per pod so is it really applicable here?

**Comment by dimm0** [comment]
Yes, the pod does not restart. The container restarts.

**Comment by dimm0** [comment]
That's what's called crashlooping... The container inside is crashing
You can run an ubuntu container without specifying a command. It will be crashlooping, but it will be the same pod

**Comment by leseb** [comment]
So if the container only restarts then the IP shouldn't change and the config should still be right, so I'm not sure what's going on.

**Comment by dimm0** [comment]
Me too, I haven't debugged that... I have problems with ceph still, because of rocksdb corruption

**Comment by dimm0** [comment]
I can tell that IPs in OSD's rook config dir on nodes are always different from the actual ones, even in properly working pods. I don't know what exactly you do there and how this whole workflow is set up

**Comment by travisn** [comment]
After discussing offline with @dimm0, the issues have been resolved and the cluster is healthy again. There are some follow-up issues to investigate.

To summarize the sequence of events:
1. The cluster was running v14.2.2
1. Upgraded to v14.2.4
1. OSDs started crashlooping due to the OOMKill
1. OSDs failed to start back up because of binding to the wrong IP
1. The cluster CR was updated to apply a memory limit to the OSD pods
1. The operator updated the OSDs and the OSDs were able to start successfully, except for a couple damaged OSDs
1. The critical PGs on one damaged OSD were imported successfully to another OSD. After being marked as lost on the first OSD, the PGs were healthy again and MDS was able to start up successfully on the moved PGs.

The open questions:
1. Why did the OSDs require a mem limit to be set to avoid the OOM killer? Does Rook need to set a default mem limit if not specified in the cluster CR? 
1. Why did the OSD try to bind to an invalid IP when the pod restarted? The OSD should find a valid IP.

@dimm0 Is that an accurate summary?
@leseb Thoughts on those open questions?

**Comment by dimm0** [comment]
Yes, it's all correct.
Wanted to add that OSDs corrupted under high memory pressure is a known ceph issue (I saw it in mailing lists), and should be avoided at all costs

**Comment by leseb** [comment]
> After discussing offline with @dimm0, the issues have been resolved and the cluster is healthy again. There are some follow-up issues to investigate.
> 
> To summarize the sequence of events:
> 
> 1. The cluster was running v14.2.2
> 2. Upgraded to v14.2.4
> 3. OSDs started crashlooping due to the OOMKill
> 4. OSDs failed to start back up because of binding to the wrong IP
> 5. The cluster CR was updated to apply a memory limit to the OSD pods
> 6. The operator updated the OSDs and the OSDs were able to start successfully, except for a couple damaged OSDs
> 7. The critical PGs on one damaged OSD were imported successfully to another OSD. After being marked as lost on the first OSD, the PGs were healthy again and MDS was able to start up successfully on the moved PGs.
> 
> The open questions:
> 
> 1. Why did the OSDs require a mem limit to be set to avoid the OOM killer? Does Rook need to set a default mem limit if not specified in the cluster CR?

The operator (human) is encouraged to set whatever is best for their platform. Rook cannot guess nor do an accurate prediction of the value that needs to be set. That's too error-prone and should be left to the administrator. This should be based on the amount of OSDs and memory on the host, as well as other considerations such as the workload running, are node hyper-converged and probably more.

> 2. Why did the OSD try to bind to an invalid IP when the pod restarted? The OSD should find a valid IP.

This shouldn't be a concern anymore, now OSDs will do their normal IP detection based on the NIC available inside the container. We don't force any IP anymore.

> 
> @dimm0 Is that an accurate summary?
> @leseb Thoughts on those open questions?

**Comment by travisn** [comment]
> The operator (human) is encouraged to set whatever is best for their platform. Rook cannot guess nor do an accurate prediction of the value that needs to be set. That's too error-prone and should be left to the administrator. This should be based on the amount of OSDs and memory on the host, as well as other considerations such as the workload running, are node hyper-converged and probably more.

In v14.2.2 the OSDs were running fine without mem limits. Now with v14.2.4 the OSDs can get OOM killed if there is no limit. Either a fix is needed in Ceph or we need a default limit, right? We can't have them crashing with default config. 

> This shouldn't be a concern anymore, now OSDs will do their normal IP detection based on the NIC available inside the container. We don't force any IP anymore.

This is with the osd config fix we'll have in 1.1.2?

**Comment by leseb** [comment]
> > The operator (human) is encouraged to set whatever is best for their platform. Rook cannot guess nor do an accurate prediction of the value that needs to be set. That's too error-prone and should be left to the administrator. This should be based on the amount of OSDs and memory on the host, as well as other considerations such as the workload running, are node hyper-converged and probably more.
> 
> In v14.2.2 the OSDs were running fine without mem limits. Now with v14.2.4 the OSDs can get OOM killed if there is no limit. Either a fix is needed in Ceph or we need a default limit, right? We can't have them crashing with default config.

I understand your point, I think we need to narrow down this issue of the OSDs consuming memory and end up being OOM killed. @dimm0 do you have any monitoring graph that could show the increase of memory usage by the OSD?
> 
> > This shouldn't be a concern anymore, now OSDs will do their normal IP detection based on the NIC available inside the container. We don't force any IP anymore.
> 
> This is with the osd config fix we'll have in 1.1.2?
Yes.

**Comment by dimm0** [comment]
https://grafana.nautilus.optiputer.net/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&from=now-14d&to=now&var-datasource=prometheus&var-cluster=&var-namespace=rook

The update was on the 25th

<img width="1185" alt="Screen Shot 2019-10-01 at 7 52 20 AM" src="https://user-images.githubusercontent.com/1425007/65973585-6f5d9080-e420-11e9-9715-1ec6e3c9800b.png">

**Comment by dimm0** [comment]
> This shouldn't be a concern anymore, now OSDs will do their normal IP detection based on the NIC available inside the container. We don't force any IP anymore.

Can I get this fix soon plz?

**Comment by dimm0** [comment]
I still see pods go crashloop (about one-two per day)

Also I've got 2 OSDs corrupted after the upgrade:

```
 -1428> 2019-10-02 18:50:06.176 7f4325a2b700 -1 /home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/14.2.4/rpm/el7/BUILD/ceph-14.2.4/src/kv/RocksDBStore.cc: In function 'virtual int RocksDBStore::get(const string&, const char*, size_t, ceph::bufferlist*)' thread 7f4325a2b700 time 2019-10-02 18:50:06.171417
/home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/14.2.4/rpm/el7/BUILD/ceph-14.2.4/src/kv/RocksDBStore.cc: 1247: ceph_abort_msg("block checksum mismatch: expected 382365200, got 2552017077  in db/034957.sst offset 2000594 size 4364")

 ceph version 14.2.4 (75f4de193b3ea58512f204623e6c5a16e6c1e1ba) nautilus (stable)
 1: (ceph::__ceph_abort(char const*, int, char const*, std::string const&)+0xdd) [0x55d2466ae09d]
 2: (RocksDBStore::get(std::string const&, char const*, unsigned long, ceph::buffer::v14_2_0::list*)+0x3dd) [0x55d246c321bd]
 3: (BlueStore::Collection::get_onode(ghobject_t const&, bool)+0xb5d) [0x55d246b789dd]
 4: (BlueStore::_txc_add_transaction(BlueStore::TransContext*, ObjectStore::Transaction*)+0x1b28) [0x55d246bcdeb8]
 5: (BlueStore::queue_transactions(boost::intrusive_ptr<ObjectStore::CollectionImpl>&, std::vector<ObjectStore::Transaction, std::allocator<ObjectStore::Transaction> >&, boost::intrusive_ptr<TrackedOp>, ThreadPool::TPHandle*)+0x528) [0x55d246bd4f38]
 6: (ObjectStore::queue_transaction(boost::intrusive_ptr<ObjectStore::CollectionImpl>&, ObjectStore::Transaction&&, boost::intrusive_ptr<TrackedOp>, ThreadPool::TPHandle*)+0x7f) [0x55d2467ad74f]
 7: (PrimaryLogPG::remove_missing_object(hobject_t const&, eversion_t, Context*)+0x4fb) [0x55d2468a352b]
 8: (PGBackend::handle_recovery_delete(boost::intrusive_ptr<OpRequest>)+0x168) [0x55d246946178]
 9: (PGBackend::handle_message(boost::intrusive_ptr<OpRequest>)+0xbb) [0x55d246947d9b]
 10: (PrimaryLogPG::do_request(boost::intrusive_ptr<OpRequest>&, ThreadPool::TPHandle&)+0x695) [0x55d2468f3c35]
 11: (OSD::dequeue_op(boost::intrusive_ptr<PG>, boost::intrusive_ptr<OpRequest>, ThreadPool::TPHandle&)+0x1a9) [0x55d24672d849]
 12: (PGOpItem::run(OSD*, OSDShard*, boost::intrusive_ptr<PG>&, ThreadPool::TPHandle&)+0x62) [0x55d2469cc0a2]
 13: (OSD::ShardedOpWQ::_process(unsigned int, ceph::heartbeat_handle_d*)+0x9f4) [0x55d24674aa74]
 14: (ShardedThreadPool::shardedthreadpool_worker(unsigned int)+0x433) [0x55d246d4e613]
 15: (ShardedThreadPool::WorkThreadSharded::entry()+0x10) [0x55d246d516b0]
 16: (()+0x7e65) [0x7f4348d8ae65]
 17: (clone()+0x6d) [0x7f4347c4e88d]
```

I'm not sure what my strategy should be now. When I didn't have the mem limit, OSDs could burst to higher memory consumption when needed. Now they're limited to 5G, and according to https://tracker.ceph.com/issues/24968 "Some of them mentioned high memory pressure as one of the potential root cause. Isn't that the case for you as well?" - the corruption might be caused by high mem pressure

But if I give them more than 5G, they will start getting OOMKills, since nodes only have 128G per 10-16 drives

Please suggest

**Comment by dimm0** [comment]
Talked to Sage, got a solution to try for now

**Comment by leseb** [comment]
> > This shouldn't be a concern anymore, now OSDs will do their normal IP detection based on the NIC available inside the container. We don't force any IP anymore.
> 
> Can I get this fix soon plz?

Present in 1.1.2: https://github.com/rook/rook/releases/tag/v1.1.2

**Comment by dimm0** [comment]
Closing the ticket then
