### ISSUE TITLE
rook-ceph-osd-prepare pods in init state after completion due to FailedMount

### ISSUE THREAD

**Issue by dmeijboom** [rook/rook#4208]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
`rook-ceph-osd-prepare*` pods goes into init:0/2 stage with the `FailedMount` errors.

**Expected behavior:**
Not sure.. I think the `rook-ceph-osd-prepare*` pods should've remained completed right? Simply because the OSDs were already provisioned.

**How to reproduce it (minimal and precise):**
I'm using GKE with default configuration but instead of cluster.yml I've used cluster-on-pvc for a production cluster. I added a filesystem and two PVC's based on a storageClass I created for Ceph.

Ceph is working just fine and the OSDs are up but I just want to know why this happends and if this is expected behaviour. I also tried deleting the pods so that they will be restarted but this didn't help. The strangest thing is when I describe the volume that can't be mounted:

`kubectl -n rook-ceph describe pvc/set1-0-data-w6p5c`:
```
Name:          set1-0-data-w6p5c
Namespace:     rook-ceph
StorageClass:  standard
Status:        Bound
Volume:        pvc-27482459-f985-11e9-8e67-42010aa401c2
Labels:        ceph.rook.io/DeviceSet=set1
               ceph.rook.io/DeviceSetPVCId=set1-0
               ceph.rook.io/setIndex=0
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/gce-pd
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      100Gi
Access Modes:  RWO
VolumeMode:    Block
Mounted By:    rook-ceph-osd-2-dcc7dbd6f-rnjsk
               rook-ceph-osd-prepare-set1-0-data-w6p5c-764lg
Events:        <none>
```

I would not expect it to be mounted by `osd-2` and `set1-0-data` right? Or is this not an issue?

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
https://pastebin.com/ZS3Lu2Hi
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary
`kubectl  -n rook-ceph describe pods/rook-ceph-osd-prepare-set1-0-data-w6p5c-764lg`:
```
Name:           rook-ceph-osd-prepare-set1-0-data-w6p5c-764lg
Namespace:      rook-ceph
Priority:       0
Node:           gke-production-default-pool-6cf9ff2b-5jv0/10.164.0.5
Start Time:     Tue, 29 Oct 2019 08:17:35 +0100
Labels:         app=rook-ceph-osd-prepare
                ceph.rook.io/pvc=set1-0-data-w6p5c
                controller-uid=6a9352e7-f9c8-11e9-a6fa-42010aa400e5
                job-name=rook-ceph-osd-prepare-set1-0-data-w6p5c
                rook_cluster=rook-ceph
Annotations:    <none>
Status:         Pending
IP:             
Controlled By:  Job/rook-ceph-osd-prepare-set1-0-data-w6p5c
Init Containers:
  copy-bins:
    Container ID:  
    Image:         rook/ceph:v1.1.4
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Args:
      copy-binaries
      --copy-to-dir
      /rook
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /rook from rook-binaries (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from rook-ceph-osd-token-tljsv (ro)
  blkdevmapper:
    Container ID:  
    Image:         ceph/ceph:v14.2.4-20190917
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      cp
    Args:
      -a
      /set1-0-data-w6p5c
      /mnt/set1-0-data-w6p5c
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /mnt from set1-0-data-w6p5c-bridge (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from rook-ceph-osd-token-tljsv (ro)
    Devices:
      /set1-0-data-w6p5c from set1-0-data-w6p5c
Containers:
  provision:
    Container ID:  
    Image:         ceph/ceph:v14.2.4-20190917
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      /rook/tini
    Args:
      --
      /rook/rook
      ceph
      osd
      provision
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     0
      memory:  0
    Requests:
      cpu:     0
      memory:  0
    Environment:
      ROOK_NODE_NAME:             set1-0-data-w6p5c
      ROOK_CLUSTER_ID:            48fde8b6-f984-11e9-8e67-42010aa401c2
      ROOK_PRIVATE_IP:             (v1:status.podIP)
      ROOK_PUBLIC_IP:              (v1:status.podIP)
      ROOK_CLUSTER_NAME:          rook-ceph
      ROOK_MON_ENDPOINTS:         <set to the key 'data' of config map 'rook-ceph-mon-endpoints'>  Optional: false
      ROOK_MON_SECRET:            <set to the key 'mon-secret' in secret 'rook-ceph-mon'>          Optional: false
      ROOK_ADMIN_SECRET:          <set to the key 'admin-secret' in secret 'rook-ceph-mon'>        Optional: false
      ROOK_CONFIG_DIR:            /var/lib/rook
      ROOK_CEPH_CONFIG_OVERRIDE:  /etc/ceph/ceph.conf
      ROOK_FSID:                  <set to the key 'fsid' in secret 'rook-ceph-mon'>  Optional: false
      CEPH_VOLUME_DEBUG:          1
      NODE_NAME:                   (v1:spec.nodeName)
      ROOK_CEPH_VERSION:          ceph version 14.2.4 nautilus
      ROOK_DATA_DEVICES:          /mnt/set1-0-data-w6p5c
      ROOK_PVC_BACKED_OSD:        true
    Mounts:
      /dev from devices (rw)
      /etc/ceph from ceph-conf-emptydir (rw)
      /mnt from set1-0-data-w6p5c-bridge (rw)
      /rook from rook-binaries (rw)
      /run/udev from udev (rw)
      /var/lib/rook from rook-data (rw)
      /var/log/ceph from rook-ceph-log (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from rook-ceph-osd-token-tljsv (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  rook-data:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/rook
    HostPathType:  
  ceph-conf-emptydir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  rook-ceph-log:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/rook/log/rook-ceph
    HostPathType:  
  rook-binaries:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  devices:
    Type:          HostPath (bare host directory volume)
    Path:          /dev
    HostPathType:  
  udev:
    Type:          HostPath (bare host directory volume)
    Path:          /run/udev
    HostPathType:  
  set1-0-data-w6p5c:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  set1-0-data-w6p5c
    ReadOnly:   false
  set1-0-data-w6p5c-bridge:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  rook-ceph-osd-token-tljsv:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  rook-ceph-osd-token-tljsv
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason              Age                 From                                                Message
  ----     ------              ----                ----                                                -------
  Normal   Scheduled           54m                 default-scheduler                                   Successfully assigned rook-ceph/rook-ceph-osd-prepare-set1-0-data-w6p5c-764lg to gke-production-default-pool-6cf9ff2b-5jv0
  Warning  FailedAttachVolume  54m                 attachdetach-controller                             Multi-Attach error for volume "pvc-27482459-f985-11e9-8e67-42010aa401c2" Volume is already used by pod(s) rook-ceph-osd-2-dcc7dbd6f-rnjsk
  Warning  FailedMount         47s (x24 over 52m)  kubelet, gke-production-default-pool-6cf9ff2b-5jv0  Unable to mount volumes for pod "rook-ceph-osd-prepare-set1-0-data-w6p5c-764lg_rook-ceph(2e7e8682-fa1c-11e9-a6fa-42010aa400e5)": timeout expired waiting for volumes to attach or mount for pod "rook-ceph"/"rook-ceph-osd-prepare-set1-0-data-w6p5c-764lg". list of unmounted volumes=[set1-0-data-w6p5c]. list of unattached volumes=[rook-data ceph-conf-emptydir rook-ceph-log rook-binaries devices udev set1-0-data-w6p5c set1-0-data-w6p5c-bridge rook-ceph-osd-token-tljsv]
```

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
* Kernel (e.g. `uname -a`):
`Linux gke-production-default-pool-6cf9ff2b-5jv0 4.15.0-1044-gke #46-Ubuntu SMP Fri Sep 13 15:02:00 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration:
GKE
* Rook version (use `rook version` inside of a Rook Pod):
v1.1.4
* Storage backend version (e.g. for ceph do `ceph -v`):
ceph version 14.2.4 (75f4de193b3ea58512f204623e6c5a16e6c1e1ba) nautilus (stable)
* Kubernetes version (use `kubectl version`):
v1.14.7-gke.10
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
GKE
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
HEALTH_WARN too few PGs per OSD (20 < min 30)

**Comment by kyschouv** [comment]
We're seeing this too.

**Comment by travisn** [comment]
This should have been fixed by #4277 in v1.1.7. Can you verify if that build is working for you?

**Comment by dmeijboom** [comment]
> This should have been fixed by #4277 in v1.1.7. Can you verify if that build is working for you?

I updated to `1.1.7` yesterday, now one of the jobs is completed but the other two still have the same issue.

**Comment by travisn** [comment]
@dmeijboom Were the jobs already in that state before the upgrade to 1.1.7? The jobs will be skipped completely now after the osd is first created, so if they are already in that state you may need to delete them manually.

**Comment by dmeijboom** [comment]
> @dmeijboom Were the jobs already in that state before the upgrade to 1.1.7? The jobs will be skipped completely now after the osd is first created, so if they are already in that state you may need to delete them manually.

Yeah, they were. I guess that makes sense! So it looks like it's fixed then :) nice!
