### ISSUE TITLE
Custom annotations cause operator to panic: "assignment to entry in nil map"

### ISSUE THREAD

**Issue by hmm01i** [rook/rook#4351]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Adding annotations to cluster.yaml causes Operator to crash with:
```
E1120 18:51:40.688055       8 runtime.go:69] Observed a panic: "assignment to entry in nil map" (assignment to entry in nil map)
```

Relevant snip from cluster.yaml 
```
  annotations:
#    all:
#    mon:
#    osd:
# If no mgr annotations are set, prometheus scrape annotations will be set by default.
    mgr:
      ad.datadoghq.com/mgr.check_names:  '["prometheus"]'
      ad.datadoghq.com/mgr.init_configs: '[{}]'
      ad.datadoghq.com/mgr.instances: |
        [
          {
            "prometheus_url": "http://%%host%%:9283/metrics",
            "namespace": "rook-ceph",
            "metrics": ["*"]
          }
        ]
```

**Expected behavior:**
Adding custom annotations to cluster.yaml should not panic the operator. Annotations should be added or the error should be handled more gracefully.

**How to reproduce it (minimal and precise):**

Specify a custom annotation to a single component, eg mgr.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`
[cluster.yaml.txt](https://github.com/rook/rook/files/3870988/cluster.yaml.txt)

* Operator's logs (attached panic trace)
[operator.log](https://github.com/rook/rook/files/3870982/operator.log)

**Environment**:
* OS (e.g. from /etc/os-release): CoreOS
* Kernel (e.g. `uname -a`): Linux kube-worker2 4.19.66-coreos #1 SMP Mon Aug 26 21:06:50 -00 2019 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: Azure VMs
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.1.6, go: go1.11
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 14.2.4 (75f4de193b3ea58512f204623e6c5a16e6c1e1ba) nautilus (stable)
* Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:30:22Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Custom (RKE)
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_WARN too few PGs per OSD (24 < min 30)

**Comment by hmm01i** [comment]
Maybe this is resolved by https://github.com/rook/rook/pull/4195

**Comment by BlaineEXE** [comment]
Very likely this is fixed by #4195, yes. This is present in Rook v1.1.7. Could you try updating and checking again?

**Comment by hmm01i** [comment]
So I'm still getting error but it goes away if I add an annotation to `all:`. I'm wondering if the problem might happen when trying to merge component specific annotations with "all"  annotations if `all:` is empty or not defined.

**Comment by eknudtson** [comment]
Hi,

I'm still seeing this crash on rook 1.2.2 when I set mgr annotations.

**Comment by travisn** [comment]
I see where the fix is needed. As a workaround if you specify "all" annotations in addition to the specific component such as "mgr", the annotations will be applied.
