### ISSUE TITLE
Kubelet log spamed by "Operation for "/var/lib/kubelet/plugins/rbd.csi.ceph.com/csi.sock" failed."

### ISSUE THREAD

**Issue by nalakawula** [rook/rook#4359]
**Is this a bug report or feature request?**
* Bug Report
Actually I'm not sure, this is a bug or normal behavior. I try rook v1.1 the did clean up as described in https://rook.io/docs/rook/v1.1/ceph-teardown.html

Now, now more rook's stuff in my cluster, but when I check kubelet log its spammed by:
```
nov. 22 01:50:30 KubeNode1 kubelet[1215]: E1122 01:50:30.589128    1215 goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins/rbd.csi.ceph.com/csi.sock" failed. No retries permitted until 2019-11-22 01:51:34.589085973 +0100 CET m=+230.577305520 (durationBeforeRetry 1m4s). Error: "RegisterPlugin error -- dial failed at socket /var/lib/kubelet/plugins/rbd.csi.ceph.com/csi.sock, err: failed to dial socket /var/lib/kubelet/plugins/rbd.csi.ceph.com/csi.sock, err: context deadline exceeded"
nov. 22 01:50:30 KubeNode1 kubelet[1215]: W1122 01:50:30.589152    1215 asm_amd64.s:1337] Failed to dial /var/lib/kubelet/plugins/rbd.csi.ceph.com/csi.sock: context canceled; please retry.
nov. 22 01:50:30 KubeNode1 kubelet[1215]: E1122 01:50:30.589576    1215 goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins/rook-ceph.rbd.csi.ceph.com/csi.sock" failed. No retries permitted until 2019-11-22 01:51:34.589552081 +0100 CET m=+230.577771628 (durationBeforeRetry 1m4s). Error: "RegisterPlugin error -- dial failed at socket /var/lib/kubelet/plugins/rook-ceph.rbd.csi.ceph.com/csi.sock, err: failed to dial socket /var/lib/kubelet/plugins/rook-ceph.rbd.csi.ceph.com/csi.sock, err: context deadline exceeded"
```

**Environment**:
* OS (e.g. from /etc/os-release): Debian GNU/Linux 10 (buster)
* Kernel (e.g. `uname -a`): Linux KubeNode2 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64 GNU/Linux
* Cloud provider or hardware configuration: VM on top hypervisor (baremetal)
* Rook version (use `rook version` inside of a Rook Pod): v1.1
* Storage backend version (e.g. for ceph do `ceph -v`): destroyed so can not check, i follow v1.1 documentation
* Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): destroyed as i did cleanup

Thank you

**Comment by vvavepacket** [comment]
I got a similar error. I have the same setup as above. Any fix or insights on this?

`Mar 30 02:14:30 prod-worker01 kubelet[4127]: I0330 02:14:30.785978    4127 operation_generator.go:551] MountVolume.WaitForAttach entering for volume "pvc-2145f41d-36f8-4ce7-a1c0-4a65182d7712" (UniqueName: "kubernetes.io/csi/rook-ceph.rbd.csi.ceph.com^0001-0009-rook-ceph-0000000000000003-d0fdeb1c-7215-11ea-8927-b20113b3acbe") pod "auth-postgres-deployment-55df584656-hjdjc" (UID: "5d03125b-5c4c-4519-9820-e3af70e152af") DevicePath ""
Mar 30 02:14:31 prod-worker01 kubelet[4127]: I0330 02:14:31.094343    4127 operation_generator.go:560] MountVolume.WaitForAttach succeeded for volume "pvc-2145f41d-36f8-4ce7-a1c0-4a65182d7712" (UniqueName: "kubernetes.io/csi/rook-ceph.rbd.csi.ceph.com^0001-0009-rook-ceph-0000000000000003-d0fdeb1c-7215-11ea-8927-b20113b3acbe") pod "auth-postgres-deployment-55df584656-hjdjc" (UID: "5d03125b-5c4c-4519-9820-e3af70e152af") DevicePath "csi-f6d0e2a6a8316f6dd1e836d8b66b3db84dbeab1e9eeb7f1aa76e5ca4d8304329"
Mar 30 02:14:31 prod-worker01 kubelet[4127]: I0330 02:14:31.095233    4127 clientconn.go:104] parsed scheme: ""
Mar 30 02:14:31 prod-worker01 kubelet[4127]: I0330 02:14:31.095267    4127 clientconn.go:104] scheme "" not registered, fallback to default scheme
Mar 30 02:14:31 prod-worker01 kubelet[4127]: I0330 02:14:31.095328    4127 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/var/lib/kubelet/plugins/rook-ceph.rbd.csi.ceph.com/csi.sock 0  <nil>}] <nil>}
Mar 30 02:14:31 prod-worker01 kubelet[4127]: I0330 02:14:31.095351    4127 clientconn.go:577] ClientConn switching balancer to "pick_first"
Mar 30 02:14:31 prod-worker01 kubelet[4127]: W0330 02:14:31.095689    4127 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {/var/lib/kubelet/plugins/rook-ceph.rbd.csi.ceph.com/csi.sock 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins/rook-ceph.rbd.csi.ceph.com/csi.sock: connect: connection refused". Reconnecting...
Mar 30 02:14:31 prod-worker01 kubelet[4127]: E0330 02:14:31.095787    4127 csi_attacher.go:270] kubernetes.io/csi: attacher.MountDevice failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins/rook-ceph.rbd.csi.ceph.com/csi.sock: connect: connection refused"
Mar 30 02:14:31 prod-worker01 kubelet[4127]: E0330 02:14:31.096254    4127 nestedpendingoperations.go:270] Operation for "\"kubernetes.io/csi/rook-ceph.rbd.csi.ceph.com^0001-0009-rook-ceph-0000000000000003-d0fdeb1c-7215-11ea-8927-b20113b3acbe\"" failed. No retries permitted until 2020-03-30 02:16:33.096162503 +0200 CEST m=+67597.884198176 (durationBeforeRetry 2m2s). Error: "MountVolume.MountDevice failed for volume \"pvc-2145f41d-36f8-4ce7-a1c0-4a65182d7712\" (UniqueName: \"kubernetes.io/csi/rook-ceph.rbd.csi.ceph.com^0001-0009-rook-ceph-0000000000000003-d0fdeb1c-7215-11ea-8927-b20113b3acbe\") pod \"auth-postgres-deployment-55df584656-hjdjc\" (UID: \"5d03125b-5c4c-4519-9820-e3af70e152af\") : rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial unix /var/lib/kubelet/plugins/rook-ceph.rbd.csi.ceph.com/csi.sock: connect: connection refused\""`

**Comment by travisn** [comment]
@nalakawula @vvavepacket Still hitting this issue? Reopening since I haven't heard of a resolution.

**Comment by Madhu-1** [comment]
@travisn this is resolved in kube 1.17 https://github.com/kubernetes/kubernetes/pull/84533

**Comment by onedr0p** [comment]
I removed rook-ceph a month ago and just notice these logs are also happening to me.

```

E0902 14:43:27.811149     846 goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins_registry/rook-ceph.cephfs.csi.ceph.com-reg.sock" failed. No retries permitted until 2020-09-02 14:45:29.811057122 -0400 EDT m=+416679.227273702 (durationBeforeRetry 2m2s). Error: "RegisterPlugin error -- dial failed at socket /var/lib/kubelet/plugins_registry/rook-ceph.cephfs.csi.ceph.com-reg.sock, err: failed to dial socket /var/lib/kubelet/plugins_registry/rook-ceph.cephfs.csi.ceph.com-reg.sock, err: context deadline exceeded"
--
  |   | E0902 14:43:27.810988     846 goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins_registry/rook-ceph.rbd.csi.ceph.com-reg.sock" failed. No retries permitted until 2020-09-02 14:45:29.810896942 -0400 EDT m=+416679.227113565 (durationBeforeRetry 2m2s). Error: "RegisterPlugin error -- dial failed at socket /var/lib/kubelet/plugins_registry/rook-ceph.rbd.csi.ceph.com-reg.sock, err: failed to dial socket /var/lib/kubelet/plugins_registry/rook-ceph.rbd.csi.ceph.com-reg.sock, err: context deadline exceeded"

```

**Comment by travisn** [comment]
@Madhu-1 Any more thoughts on this? Looks like it's still an issue in 1.18.

**Comment by DesistDaydream** [comment]
I have the same issue.
k8s version: v1.18.8
I try rook v1.4 the did clean up as described in https://rook.github.io/docs/rook/v1.4/ceph-teardown.html
But there are a lot of useless logs in kubelet

```
Oct  6 10:48:30 node-2 kubelet: E1006 10:48:30.701994   17427 goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins_registry/rook-ceph.rbd.csi.ceph.com-reg.sock" failed. No retries permitted until 2020-10-06 10:49:02.70195761 +0800 CST m=+141.381273597 (durationBeforeRetry 32s). Error: "RegisterPlugin error -- dial failed at socket /var/lib/kubelet/plugins_registry/rook-ceph.rbd.csi.ceph.com-reg.sock, err: failed to dial socket /var/lib/kubelet/plugins_registry/rook-ceph.rbd.csi.ceph.com-reg.sock, err: context deadline exceeded"
Oct  6 10:48:30 node-2 kubelet: E1006 10:48:30.702083   17427 goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins_registry/rook-ceph.cephfs.csi.ceph.com-reg.sock" failed. No retries permitted until 2020-10-06 10:49:02.702020332 +0800 CST m=+141.381336400 (durationBeforeRetry 32s). Error: "RegisterPlugin error -- dial failed at socket /var/lib/kubelet/plugins_registry/rook-ceph.cephfs.csi.ceph.com-reg.sock, err: failed to dial socket /var/lib/kubelet/plugins_registry/rook-ceph.cephfs.csi.ceph.com-reg.sock, err: context deadline exceeded"
```

**Comment by CermakM** [comment]
Same thing on Kubernetes 18.5

**Comment by notevery** [comment]
Just mv the *.sock files to another folder, and restart the kubelet.

**Comment by onedr0p** [comment]
> Just mv the *.sock files to another folder, and restart the kubelet. 

@notevery that's assuming those files even exist, which they do not.

**Comment by Madhu-1** [comment]
The registry socket removal functionality is added in https://github.com/kubernetes-csi/node-driver-registrar/pull/61. if you are using node-driver-registrar v.2.0.0 you should not see this issue

**Comment by Horkyze** [comment]
Is kubelet trying to dial the ceph socket, just because the socket file exists in that specific directory (`/var/lib/kubelet/plugins_registry/`)?
In that case would removing the sockets be a fix?

---
Or the initiative to connect to this socket comes from some setting/registration done during install of rook.
In that case the tear-down didn't delete all components of rook.
What can one do to get rid of it?

**Comment by BlaineEXE** [comment]
You should be able to simply remove the socket file on the host.
