### ISSUE TITLE
[Important] Pod can't mount volume after server suddenly shutdown

### ISSUE THREAD

**Issue by ceyhunn** [rook/rook#4914]
** Bug Report **
After server suddenly shutdown, kubernetes pods didn't work
Pods error message:
`MountVolume.MountDevice failed for volume "pvc-cd68303a-c4e9-49df-be77-5289a77d2a73" : rpc error: code = Internal desc = 'xfs_repair' found errors on device /dev/rbd0 but could not correct them: Phase 1 - find and verify superblock... - reporting progress in intervals of 15 minutes Phase 2 - using internal log - zero log... ERROR: The filesystem has valuable metadata changes in a log which needs to be replayed. Mount the filesystem to replay the log, and unmount it before re-running xfs_repair. If you are unable to mount the filesystem, then use the -L option to destroy the log and attempt a repair. Note that destroying the log may cause corruption -- please attempt a mount of the filesystem before doing this`

But rook-ceph cluster works well. Health is ok. I can't custom map csi image with rbd inside rook-ceph-tools. It gives me error like following:
```
rbd: failed to set udev buffer size: (1) Operation not permitted
rbd: sysfs write failed
In some cases useful info is found in syslog - try "dmesg | tail".
rbd: map failed: (30) Read-only file system
```

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 18.04
* Kernel (e.g. `uname -a`): 4.15.0-88-generic
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): 1.2.3
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.5
* Kubernetes version (use `kubectl version`): 1.16.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): rancher 
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

**Comment by galexrt** [comment]
@ceyhunn Make sure the PVC is not mounted in any Pod right now (e.g., if it is one of many in a Deployment / ReplicaSet, use the `paused` option in the Deployment / ReplicaSet to stop rollout) and then use the direct mount Pod to map, mount and run `xfs_repair` on the block device, see https://rook.io/docs/rook/v1.2/direct-tools.html.

**Comment by nktpro** [comment]
Ran into this exact issue ourselves today, which caused production outage due to a regression in the `mounter` of `kubernetes/utils`. Github issue was created at the proper place here: https://github.com/kubernetes/utils/issues/141

**Comment by ceyhunn** [comment]
I restored snaphot  for my cluster, because before @galexrt wrote the comment I guessed  that this problem caused by rook upgrade (v1.2.1 -> 1.2.3). Snaplhots with rook version 1.2.3, I had no success, but with rook version 1.2.1 , it worked. I don't know exactly the problem occurs again.

**Comment by whymatter** [comment]
Hi, I have the same problem. After a reboot, my pod was not able to remount the PVC. I tried to delete the pod and create a new one but same problem. I do not use any Deployment / RS.

**Comment by whymatter** [comment]
I found this one https://github.com/kubernetes/kubernetes/issues/60987 and it really seems to be related?

**Comment by Techinica** [comment]
Whilst K8S issue with the xfs mounter is definitely a problem here, my bigger issue right now is that while ceph is rebalancing my cluster, its causing the pods to restart with this issue. 

It seems to occur whenever the number of PGs in the pool is changed (auto balancer is modifying it due to me adding more OSDs to the pool). This is a real pain because my pods are right now restarting every ~30 mins and I need to run the manual map/mount/umount/unmap process for each image in the pool every time it happens.

**Comment by whymatter** [comment]
You can rename the xfs_repair tool. That way kubernetes will still try to run it, report an error but continue to mount your pods. An othed option would be to migrate to ext4.

**Comment by Techinica** [comment]
@whymatter yeah, renaming is what I resorted to. Regarding xfs vs ext4, I'm really only on it now because of the rook PR that made it the default a while ago, suggesting performance was far superior.

**Comment by fr3aker** [comment]
The problem has been fixed in ceph-csi 2.1.0. Would be nice to have that as the default version in rook. This bug is really problematic.

**Comment by kdoustar** [comment]
But my CSI version is 2.1.2 and I still have this problem, who should I proceed?
I cannot manually map any rbd image.
Thanks,

**Comment by solovyevt** [comment]
Please reopen, issue still persists on 1.4.2

**Comment by dimm0** [comment]
Hitting this in 1.4.7

**Comment by travisn** [comment]
@Madhu-1 Can you take another look at this?

**Comment by dimm0** [comment]
I mean hitting the "I can't custom map csi image with rbd inside rook-ceph-tools" one. Is this related to CSI at all?

**Comment by travisn** [comment]
Ah, I missed that this was a custom mount from the toolbox. Did you try using the [direct mount pod](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/direct-mount.yaml) instead of the toolbox? In recent releases, the toolbox doesn't mount /dev by default.

**Comment by dimm0** [comment]
Omg, no... Thanks, I'll try
I guess this can be closed then

**Comment by travisn** [comment]
Ok, perhaps others hit the same issue where the toolbox doesn't have those mounts anymore.
