### ISSUE TITLE
prepare jobs failing with "failed to parse device list / unexpected end of JSON input"

### ISSUE THREAD

**Issue by stuartpb** [rook/rook#6315]
**Is this a bug report or feature request?**
* Bug Report

I have a storage cluster with 3 nodes (identified by label), each having multiple drives attached.

```yaml
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    # see the "Cluster Settings" section below for more details on which image of ceph to run
    image: ceph/ceph:v15.2.5
  dataDirHostPath: /var/lib/rook
  dashboard:
    enabled: true
  monitoring:
    enabled: true
  mon:
    count: 3
    allowMultiplePerNode: true
  driveGroups:
  - name: storberry
    spec:
      data_devices:
        all: true
    placement:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: st8s.testtrack4.com/storage-group
              operator: In
              values:
              - storberry
```

The drives are recognized - here are the logs from one node's discover pod:

```
2020-09-24 08:18:17.955060 I | rookcmd: starting Rook v1.4.3 with arguments '/usr/local/bin/rook discover --discover-interval 60m --use-ceph-volume'
2020-09-24 08:18:17.955377 I | rookcmd: flag values: --discover-interval=1h0m0s, --help=false, --log-flush-frequency=5s, --log-level=INFO, --operator-image=, --service-account=, --use-ceph-volume=true
2020-09-24 08:18:17.959440 I | rook-discover: updating device configmap
2020-09-24 08:18:18.673550 W | inventory: skipping device "sda1". exit status 32
2020-09-24 08:18:18.776407 I | inventory: skipping device "mmcblk1" because it has child, considering the child instead.
2020-09-24 08:18:18.828730 I | rook-discover: localdevices: "sda, sdb, mmcblk1p1, mmcblk1p2"
2020-09-24 08:18:18.829002 I | rook-discover: Getting ceph-volume inventory information
2020-09-24 08:18:24.847206 I | sys: Output: NAME="sda" SIZE="2000398933504" TYPE="disk" PKNAME=""
2020-09-24 08:18:24.847297 I | sys: Device found - sda
2020-09-24 08:18:24.871309 I | sys: Output: NAME="sdb" SIZE="120034123776" TYPE="disk" PKNAME=""
2020-09-24 08:18:24.871415 I | sys: Device found - sdb
2020-09-24 08:18:24.888512 I | rook-discover: available devices: [{Name:sda Parent: HasChildren:false DevLinks:/dev/disk/by-id/usb-Seagate_Portable_NAAHGF0V-0:0 /dev/disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:2:1.0-scsi-0:0:0:0 Size:2000398933504 UUID:a5226d1e-0881-4bdf-8d98-d710b3a091cc Serial:Seagate_Portable_NAAHGF0V-0:0 Type:disk Rotational:true Readonly:false Partitions:[] Filesystem: Vendor:Seagate Model:Portable WWN: WWNVendorExtension: Empty:true CephVolumeData:{"path":"/dev/sda","available":true,"rejected_reasons":[],"sys_api":{"removable":"0","ro":"0","vendor":"Seagate","model":"Portable","rev":"9300","sas_address":"","sas_device_handle":"","support_discard":"0","rotational":"1","nr_requests":"58","scheduler_mode":"mq-deadline","partitions":{},"sectors":0,"sectorsize":"512","size":2000398933504.0,"human_readable_size":"1.82 TB","path":"/dev/sda","locked":0},"lvs":[]} RealPath:/dev/sda KernelName:sda Encrypted:false} {Name:sdb Parent: HasChildren:false DevLinks:/dev/disk/by-id/usb-PNY_CS90_0_120GB_SSD_191224002402-0:0 /dev/disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1:1.0-scsi-0:0:0:0 Size:120034123776 UUID:734cdc8c-5a91-4300-baf2-a61beff423eb Serial:PNY_CS90_0_120GB_SSD_191224002402-0:0 Type:disk Rotational:true Readonly:false Partitions:[] Filesystem: Vendor:PNY_CS90 Model:0_120GB_SSD WWN: WWNVendorExtension: Empty:true CephVolumeData:{"path":"/dev/sdb","available":true,"rejected_reasons":[],"sys_api":{"removable":"0","ro":"0","vendor":"PNY CS90","model":"0 120GB SSD","rev":"CS90","sas_address":"","sas_device_handle":"","support_discard":"0","rotational":"1","nr_requests":"2","scheduler_mode":"mq-deadline","partitions":{},"sectors":0,"sectorsize":"512","size":120034123776.0,"human_readable_size":"111.79 GB","path":"/dev/sdb","locked":0},"lvs":[]} RealPath:/dev/sdb KernelName:sdb Encrypted:false}]
2020-09-24 08:18:25.306913 I | rook-discover: using the regular expressions ["(?i)dm-[0-9]+" "(?i)rbd[0-9]+" "(?i)nbd[0-9]+"]
2020-09-24 09:18:25.307051 I | rook-discover: updating device configmap
2020-09-24 09:18:25.464509 I | inventory: skipping device "mmcblk1" because it has child, considering the child instead.
2020-09-24 09:18:25.514896 I | rook-discover: localdevices: "sda, sdb, mmcblk1p1, mmcblk1p2"
2020-09-24 09:18:25.514968 I | rook-discover: Getting ceph-volume inventory information
2020-09-24 09:18:30.096269 I | sys: Output: NAME="sda" SIZE="2000398933504" TYPE="disk" PKNAME=""
2020-09-24 09:18:30.096376 I | sys: Device found - sda
2020-09-24 09:18:30.117872 I | sys: Output: NAME="sdb" SIZE="120034123776" TYPE="disk" PKNAME=""
2020-09-24 09:18:30.117984 I | sys: Device found - sdb
2020-09-24 09:18:30.133873 I | rook-discover: available devices: [{Name:sda Parent: HasChildren:false DevLinks:/dev/disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:2:1.0-scsi-0:0:0:0 /dev/disk/by-id/usb-Seagate_Portable_NAAHGF0V-0:0 Size:2000398933504 UUID:c196996d-26a9-4d31-9498-51c8ed6ed45e Serial:Seagate_Portable_NAAHGF0V-0:0 Type:disk Rotational:true Readonly:false Partitions:[] Filesystem: Vendor:Seagate Model:Portable WWN: WWNVendorExtension: Empty:true CephVolumeData:{"path":"/dev/sda","available":true,"rejected_reasons":[],"sys_api":{"removable":"0","ro":"0","vendor":"Seagate","model":"Portable","rev":"9300","sas_address":"","sas_device_handle":"","support_discard":"0","rotational":"1","nr_requests":"58","scheduler_mode":"mq-deadline","partitions":{},"sectors":0,"sectorsize":"512","size":2000398933504.0,"human_readable_size":"1.82 TB","path":"/dev/sda","locked":0},"lvs":[]} RealPath:/dev/sda KernelName:sda Encrypted:false} {Name:sdb Parent: HasChildren:false DevLinks:/dev/disk/by-id/usb-PNY_CS90_0_120GB_SSD_191224002402-0:0 /dev/disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1:1.0-scsi-0:0:0:0 Size:120034123776 UUID:2621ff50-8dbd-4644-9246-b79ac6f717da Serial:PNY_CS90_0_120GB_SSD_191224002402-0:0 Type:disk Rotational:true Readonly:false Partitions:[] Filesystem: Vendor:PNY_CS90 Model:0_120GB_SSD WWN: WWNVendorExtension: Empty:true CephVolumeData:{"path":"/dev/sdb","available":true,"rejected_reasons":[],"sys_api":{"removable":"0","ro":"0","vendor":"PNY CS90","model":"0 120GB SSD","rev":"CS90","sas_address":"","sas_device_handle":"","support_discard":"0","rotational":"1","nr_requests":"2","scheduler_mode":"mq-deadline","partitions":{},"sectors":0,"sectorsize":"512","size":120034123776.0,"human_readable_size":"111.79 GB","path":"/dev/sdb","locked":0},"lvs":[]} RealPath:/dev/sdb KernelName:sdb Encrypted:false}]
2020-09-24 10:18:30.134580 I | rook-discover: updating device configmap
2020-09-24 10:18:30.295665 I | inventory: skipping device "mmcblk1" because it has child, considering the child instead.
2020-09-24 10:18:30.344441 I | rook-discover: localdevices: "sda, sdb, mmcblk1p1, mmcblk1p2"
2020-09-24 10:18:30.344507 I | rook-discover: Getting ceph-volume inventory information
2020-09-24 10:18:35.040968 I | sys: Output: NAME="sda" SIZE="2000398933504" TYPE="disk" PKNAME=""
2020-09-24 10:18:35.041051 I | sys: Device found - sda
2020-09-24 10:18:35.062275 I | sys: Output: NAME="sdb" SIZE="120034123776" TYPE="disk" PKNAME=""
2020-09-24 10:18:35.062357 I | sys: Device found - sdb
2020-09-24 10:18:35.078367 I | rook-discover: available devices: [{Name:sda Parent: HasChildren:false DevLinks:/dev/disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:2:1.0-scsi-0:0:0:0 /dev/disk/by-id/usb-Seagate_Portable_NAAHGF0V-0:0 Size:2000398933504 UUID:ae4a1525-dade-48f8-9315-fed4fc7a9cec Serial:Seagate_Portable_NAAHGF0V-0:0 Type:disk Rotational:true Readonly:false Partitions:[] Filesystem: Vendor:Seagate Model:Portable WWN: WWNVendorExtension: Empty:true CephVolumeData:{"path":"/dev/sda","available":true,"rejected_reasons":[],"sys_api":{"removable":"0","ro":"0","vendor":"Seagate","model":"Portable","rev":"9300","sas_address":"","sas_device_handle":"","support_discard":"0","rotational":"1","nr_requests":"58","scheduler_mode":"mq-deadline","partitions":{},"sectors":0,"sectorsize":"512","size":2000398933504.0,"human_readable_size":"1.82 TB","path":"/dev/sda","locked":0},"lvs":[]} RealPath:/dev/sda KernelName:sda Encrypted:false} {Name:sdb Parent: HasChildren:false DevLinks:/dev/disk/by-id/usb-PNY_CS90_0_120GB_SSD_191224002402-0:0 /dev/disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1:1.0-scsi-0:0:0:0 Size:120034123776 UUID:b54d5199-1a60-4be5-b70a-31a19edecfde Serial:PNY_CS90_0_120GB_SSD_191224002402-0:0 Type:disk Rotational:true Readonly:false Partitions:[] Filesystem: Vendor:PNY_CS90 Model:0_120GB_SSD WWN: WWNVendorExtension: Empty:true CephVolumeData:{"path":"/dev/sdb","available":true,"rejected_reasons":[],"sys_api":{"removable":"0","ro":"0","vendor":"PNY CS90","model":"0 120GB SSD","rev":"CS90","sas_address":"","sas_device_handle":"","support_discard":"0","rotational":"1","nr_requests":"2","scheduler_mode":"mq-deadline","partitions":{},"sectors":0,"sectorsize":"512","size":120034123776.0,"human_readable_size":"111.79 GB","path":"/dev/sdb","locked":0},"lvs":[]} RealPath:/dev/sdb KernelName:sdb Encrypted:false}]
```

However, all of the `rook-ceph-osd-prepare` pods end up going into a crash loop, with this as the only log entry:

```
failed to parse device list (""): failed to JSON unmarshal configured devices (""): unexpected end of JSON input
```

## Environment

* OS (e.g. from /etc/os-release): OpenSUSE Kubic
* Kernel (e.g. `uname -a`): 5.8.7-1-default aarch64
* Cloud provider or hardware configuration: Bare metal heterogeneous cluster
* Rook version (use `rook version` inside of a Rook Pod): 1.4.3
* Storage backend version (e.g. for ceph do `ceph -v`): 15.2.5
* Kubernetes version (use `kubectl version`): 1.19.1
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubeadm

**Comment by travisn** [comment]
@BlaineEXE Could you take a look at this issue with drivegroups?

**Comment by BlaineEXE** [comment]
I think this is the issue I fixed with https://github.com/rook/rook/pull/6267. It should be in the next Rook update. v1.4.5 IIRC

**Comment by travisn** [comment]
@stuartpb To test with the latest unofficial release build you can use the image `rook/ceph:v1.4.4-17.gd86d6cd` until v1.4.5 is released.

**Comment by stuartpb** [comment]
Looks like that's fixed it for at least two of the nodes - the third still shows the prepare job as having failed, but the Pod's been deleted and I can't check the logs.

Not sure what the smoothest way to restart the job would be: would the Operator recreate it if I delete it?

**Comment by travisn** [comment]
@stuartpb To trigger the failed OSD job, you can actually restart the operator pod and will reconcile the OSDs again.

**Comment by stuartpb** [comment]
Well, it didn't seem to be restarting that job, so I deleted the job and then deleted the operator, and it's not coming back - what can I do to recreate the job?

**Comment by stuartpb** [comment]
Okay, here's the logs from the failed prepare pod:

```
[2020-09-24 21:22:18,867][ceph_volume.process][INFO  ] stdout ID_FS_TYPE=btrfs
[2020-09-24 21:22:18,867][ceph_volume.process][INFO  ] stdout ID_FS_USAGE=filesystem
[2020-09-24 21:22:18,868][ceph_volume.process][INFO  ] stdout ID_FS_UUID=c432d88f-bf72-476b-8e0a-b4739c7c2bf3
[2020-09-24 21:22:18,868][ceph_volume.process][INFO  ] stdout ID_FS_UUID_ENC=c432d88f-bf72-476b-8e0a-b4739c7c2bf3
[2020-09-24 21:22:18,868][ceph_volume.process][INFO  ] stdout ID_FS_UUID_SUB=9f37c7ba-b7cd-4df2-bcb7-9303b6d86a9c
[2020-09-24 21:22:18,868][ceph_volume.process][INFO  ] stdout ID_FS_UUID_SUB_ENC=9f37c7ba-b7cd-4df2-bcb7-9303b6d86a9c
[2020-09-24 21:22:18,868][ceph_volume.process][INFO  ] stdout ID_NAME=SDU1
[2020-09-24 21:22:18,868][ceph_volume.process][INFO  ] stdout ID_PART_ENTRY_DISK=179:0
[2020-09-24 21:22:18,869][ceph_volume.process][INFO  ] stdout ID_PART_ENTRY_NUMBER=2
[2020-09-24 21:22:18,869][ceph_volume.process][INFO  ] stdout ID_PART_ENTRY_OFFSET=34816
[2020-09-24 21:22:18,869][ceph_volume.process][INFO  ] stdout ID_PART_ENTRY_SCHEME=dos
[2020-09-24 21:22:18,869][ceph_volume.process][INFO  ] stdout ID_PART_ENTRY_SIZE=123439104
[2020-09-24 21:22:18,870][ceph_volume.process][INFO  ] stdout ID_PART_ENTRY_TYPE=0x83
[2020-09-24 21:22:18,870][ceph_volume.process][INFO  ] stdout ID_PART_ENTRY_UUID=aaf3ee14-02
[2020-09-24 21:22:18,870][ceph_volume.process][INFO  ] stdout ID_PART_TABLE_TYPE=dos
[2020-09-24 21:22:18,870][ceph_volume.process][INFO  ] stdout ID_PART_TABLE_UUID=aaf3ee14
[2020-09-24 21:22:18,870][ceph_volume.process][INFO  ] stdout ID_PATH=platform-fe340000.emmc2
[2020-09-24 21:22:18,870][ceph_volume.process][INFO  ] stdout ID_PATH_TAG=platform-fe340000_emmc2
[2020-09-24 21:22:18,871][ceph_volume.process][INFO  ] stdout ID_SERIAL=0x14a11ae7
[2020-09-24 21:22:18,871][ceph_volume.process][INFO  ] stdout MAJOR=179
[2020-09-24 21:22:18,871][ceph_volume.process][INFO  ] stdout MINOR=2
[2020-09-24 21:22:18,871][ceph_volume.process][INFO  ] stdout PARTN=2
[2020-09-24 21:22:18,871][ceph_volume.process][INFO  ] stdout SUBSYSTEM=block
[2020-09-24 21:22:18,872][ceph_volume.process][INFO  ] stdout TAGS=:systemd:
[2020-09-24 21:22:18,872][ceph_volume.process][INFO  ] stdout USEC_INITIALIZED=40873570
[2020-09-24 21:22:18,873][ceph_volume.process][INFO  ] Running command: /usr/bin/ceph-bluestore-tool show-label --dev /dev/mmcblk1
[2020-09-24 21:22:18,941][ceph_volume.process][INFO  ] stderr unable to read label for /dev/mmcblk1: (2) No such file or directory
[2020-09-24 21:22:18,942][ceph_volume.process][INFO  ] Running command: /usr/sbin/udevadm info --query=property /dev/mmcblk1
[2020-09-24 21:22:18,960][ceph_volume.process][INFO  ] stdout DEVLINKS=/dev/disk/by-path/platform-fe340000.emmc2 /dev/disk/by-id/mmc-SDU1_0x14a11ae7
[2020-09-24 21:22:18,960][ceph_volume.process][INFO  ] stdout DEVNAME=/dev/mmcblk1
[2020-09-24 21:22:18,961][ceph_volume.process][INFO  ] stdout DEVPATH=/devices/platform/emmc2bus/fe340000.emmc2/mmc_host/mmc1/mmc1:59b4/block/mmcblk1
[2020-09-24 21:22:18,961][ceph_volume.process][INFO  ] stdout DEVTYPE=disk
[2020-09-24 21:22:18,961][ceph_volume.process][INFO  ] stdout ID_NAME=SDU1
[2020-09-24 21:22:18,961][ceph_volume.process][INFO  ] stdout ID_PART_TABLE_TYPE=dos
[2020-09-24 21:22:18,961][ceph_volume.process][INFO  ] stdout ID_PART_TABLE_UUID=aaf3ee14
[2020-09-24 21:22:18,961][ceph_volume.process][INFO  ] stdout ID_PATH=platform-fe340000.emmc2
[2020-09-24 21:22:18,962][ceph_volume.process][INFO  ] stdout ID_PATH_TAG=platform-fe340000_emmc2
[2020-09-24 21:22:18,962][ceph_volume.process][INFO  ] stdout ID_SERIAL=0x14a11ae7
[2020-09-24 21:22:18,962][ceph_volume.process][INFO  ] stdout MAJOR=179
[2020-09-24 21:22:18,962][ceph_volume.process][INFO  ] stdout MINOR=0
[2020-09-24 21:22:18,962][ceph_volume.process][INFO  ] stdout SUBSYSTEM=block
[2020-09-24 21:22:18,962][ceph_volume.process][INFO  ] stdout TAGS=:systemd:
[2020-09-24 21:22:18,963][ceph_volume.process][INFO  ] stdout USEC_INITIALIZED=40727271
[2020-09-24 21:22:18,963][ceph.deployment.drive_selection.selector][DEBUG ] Processing disk /dev/sda
[2020-09-24 21:22:18,964][ceph.deployment.drive_selection.selector][DEBUG ] Found matching disk: /dev/sda
[2020-09-24 21:22:18,964][ceph.deployment.drive_selection.selector][DEBUG ] Adding disk /dev/sda
[2020-09-24 21:22:18,964][ceph.deployment.drive_selection.selector][DEBUG ] Processing disk /dev/mmcblk1
[2020-09-24 21:22:18,964][ceph.deployment.drive_selection.selector][DEBUG ] Ignoring disk /dev/mmcblk1. Disk is not available
[2020-09-24 21:22:18,965][ceph.deployment.drive_selection.selector][DEBUG ] device_filter is None
[2020-09-24 21:22:18,965][ceph.deployment.drive_selection.selector][DEBUG ] device_filter is None
[2020-09-24 21:22:18,965][ceph.deployment.drive_selection.selector][DEBUG ] device_filter is None
[2020-09-24 21:22:18,965][ceph_volume.2020-09-24T21:22:19.607320840Z drive_group.main][INFO  ] Running ceph-volume command: lvm prepare --bluestore --data /dev/sda --no-systemd
[2020-09-24 21:22:18,966][ceph_volume.process][INFO  ] Running command: /usr/bin/lsblk -plno KNAME,NAME,TYPE
[2020-09-24 21:22:18,976][ceph_volume.process][INFO  ] stdout /dev/sda       /dev/sda       disk
[2020-09-24 21:22:18,977][ceph_volume.process][INFO  ] stdout /dev/mmcblk1   /dev/mmcblk1   disk
[2020-09-24 21:22:18,977][ceph_volume.process][INFO  ] stdout /dev/mmcblk1p1 /dev/mmcblk1p1 part
[2020-09-24 21:22:18,977][ceph_volume.process][INFO  ] stdout /dev/mmcblk1p2 /dev/mmcblk1p2 part
[2020-09-24 21:22:18,993][ceph_volume.process][INFO  ] Running command: /usr/sbin/lvs --noheadings --readonly --separator=";" -a -S lv_path=/dev/sda -o lv_tags,lv_path,lv_name,vg_name,lv_uuid,lv_size
[2020-09-24 21:22:19,116][ceph_volume.process][INFO  ] stderr Udev is running and DM_DISABLE_UDEV environment variable is set. Bypassing udev, LVM will manage logical volume symlinks in device directory.
[2020-09-24 21:22:19,117][ceph_volume.process][INFO  ] stderr Udev is running and DM_DISABLE_UDEV environment variable is set. Bypassing udev, LVM will obtain device list by scanning device directory.
[2020-09-24 21:22:19,119][ceph_volume.process][INFO  ] Running command: /usr/bin/lsblk --nodeps -P -o NAME,KNAME,MAJ:MIN,FSTYPE,MOUNTPOINT,LABEL,UUID,RO,RM,MODEL,SIZE,STATE,OWNER,GROUP,MODE,ALIGNMENT,PHY-SEC,LOG-SEC,ROTA,SCHED,TYPE,DISC-ALN,DISC-GRAN,DISC-MAX,DISC-ZERO,PKNAME,PARTLABEL /dev/sda
[2020-09-24 21:22:19,140][ceph_volume.process][INFO  ] stdout NAME="sda" KNAME="sda" MAJ:MIN="8:0" FSTYPE="" MOUNTPOINT="" LABEL="" UUID="" RO="0" RM="0" MODEL="0 120GB SSD     " SIZE="111.8G" STATE="running" OWNER="root" GROUP="" MODE="brw-rw----" ALIGNMENT="0" PHY-SEC="512" LOG-SEC="512" ROTA="1" SCHED="mq-deadline" TYPE="disk" DISC-ALN="0" DISC-GRAN="0B" DISC-MAX="0B" DISC-ZERO="0" PKNAME="" PARTLABEL=""
[2020-09-24 21:22:19,142][ceph_volume.process][INFO  ] Running command: /usr/sbin/blkid -p /dev/sda
[2020-09-24 21:22:19,163][ceph_volume.process][INFO  ] Running command: /usr/sbin/pvs --noheadings --readonly --units=b --nosuffix --separator=";" -o vg_name,pv_count,lv_count,vg_attr,vg_extent_count,vg_free_count,vg_extent_size /dev/sda
[2020-09-24 21:22:19,356][ceph_volume.process][INFO  ] stderr Udev is running and DM_DISABLE_UDEV environment variable is set. Bypassing udev, LVM will manage logical volume symlinks in device directory.
[2020-09-24 21:22:19,357][ceph_volume.process][INFO  ] stderr Udev is running and DM_DISABLE_UDEV environment variable is set. Bypassing udev, LVM will obtain device list by scanning device directory.
[2020-09-24 21:22:19,358][ceph_volume.process][INFO  ] stderr Failed to find physical volume "/dev/sda".
[2020-09-24 21:22:19,359][ceph_volume.process][INFO  ] Running command: /usr/bin/ceph-bluestore-tool show-label --dev /dev/sda
[2020-09-24 21:22:19,429][ceph_volume.process][INFO  ] stderr unable to read label for /dev/sda: (2) No such file or directory
[2020-09-24 21:22:19,430][ceph_volume.process][INFO  ] Running command: /usr/bin/ceph-bluestore-tool show-label --dev /dev/sda
[2020-09-24 21:22:19,494][ceph_volume.process][INFO  ] stderr unable to read label for /dev/sda: (2) No such file or directory
[2020-09-24 21:22:19,495][ceph_volume.process][INFO  ] Running command: /usr/sbin/udevadm info --query=property /dev/sda
[2020-09-24 21:22:19,512][ceph_volume.process][INFO  ] stdout COMPAT_SYMLINK_GENERATION=2
[2020-09-24 21:22:19,513][ceph_volume.process][INFO  ] stdout DEVLINKS=/dev/disk/by-id/usb-PNY_CS90_0_120GB_SSD_191224031953-0:0 /dev/disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1:1.0-scsi-0:0:0:0
[2020-09-24 21:22:19,513][ceph_volume.process][INFO  ] stdout DEVNAME=/dev/sda
[2020-09-24 21:22:19,513][ceph_volume.process][INFO  ] stdout DEVPATH=/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb2/2-1/2-1:1.0/host0/target0:0:0/0:0:0:0/block/sda
[2020-09-24 21:22:19,513][ceph_volume.process][INFO  ] stdout DEVTYPE=disk
[2020-09-24 21:22:19,514][ceph_volume.process][INFO  ] stdout ID_BUS=usb
[2020-09-24 21:22:19,514][ceph_volume.process][INFO  ] stdout ID_INSTANCE=0:0
[2020-09-24 21:22:19,514][ceph_volume.process][INFO  ] stdout ID_MODEL=0_120GB_SSD
[2020-09-24 21:22:19,514][ceph_volume.process][INFO  ] stdout ID_MODEL_ENC=0\x20120GB\x20SSD\x20\x20\x20\x20\x20
[2020-09-24 21:22:19,514][ceph_volume.process][INFO  ] stdout ID_MODEL_ID=0711
[2020-09-24 21:22:19,514][ceph_volume.process][INFO  ] stdout ID_PATH=platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1:1.0-scsi-0:0:0:0
[2020-09-24 21:22:19,515][ceph_volume.process][INFO  ] stdout ID_PATH_TAG=platform-fd500000_pcie-pci-0000_01_00_0-usb-0_1_1_0-scsi-0_0_0_0
[2020-09-24 21:22:19,515][ceph_volume.process][INFO  ] stdout ID_REVISION=CS90
[2020-09-24 21:22:19,515][ceph_volume.process][INFO  ] stdout ID_SERIAL=PNY_CS90_0_120GB_SSD_191224031953-0:0
[2020-09-24 21:22:19,515][ceph_volume.process][INFO  ] stdout ID_SERIAL_SHORT=191224031953
[2020-09-24 21:22:19,515][ceph_volume.process][INFO  ] stdout ID_TYPE=disk
[2020-09-24 21:22:19,515][ceph_volume.process][INFO  ] stdout ID_USB_DRIVER=usb-storage
[2020-09-24 21:22:19,515][ceph_volume.process][INFO  ] stdout ID_USB_INTERFACES=:080650:
[2020-09-24 21:22:19,516][ceph_volume.process][INFO  ] stdout ID_USB_INTERFACE_NUM=00
[2020-09-24 21:22:19,516][ceph_volume.process][INFO  ] stdout ID_VENDOR=PNY_CS90
[2020-09-24 21:22:19,516][ceph_volume.process][INFO  ] stdout ID_VENDOR_ENC=PNY\x20CS90
[2020-09-24 21:22:19,516][ceph_volume.process][INFO  ] stdout ID_VENDOR_ID=2109
[2020-09-24 21:22:19,516][ceph_volume.process][INFO  ] stdout MAJOR=8
[2020-09-24 21:22:19,516][ceph_volume.process][INFO  ] stdout MINOR=0
[2020-09-24 21:22:19,516][ceph_volume.process][INFO  ] stdout SUBSYSTEM=block
[2020-09-24 21:22:19,517][ceph_volume.process][INFO  ] stdout TAGS=:systemd:
[2020-09-24 21:22:19,517][ceph_volume.process][INFO  ] stdout USEC_INITIALIZED=41058334
failed to configure Drive Group "storberry": failed ceph-volume call (see ceph-volume log above for more details): exit status 2
```

**Comment by stuartpb** [comment]
I caught one as it was initializing this time - here's what I saw:

```
2020-09-24 22:49:49.105760 I | rookcmd: starting Rook v1.4.4-17.gd86d6cd with arguments '/rook/rook ceph osd provision'
2020-09-24 22:49:49.106072 I | rookcmd: flag values: --cluster-id=87e55744-df1e-4272-8649-e067483b0ea0, --data-device-filter=, --data-device-path-filter=, --data-devices=, --drive-groups={"storberry":"{\"data_devices\":{\"all\":true},\"placement\":{\"host_pattern\":\"*\"},\"service_id\":\"storberry\"}"}, --encrypted-device=false, --force-format=false, --help=false, --location=, --log-flush-frequency=5s, --log-level=DEBUG, --metadata-device=, --node-name=stumethyst.403.testtrack4.com, --operator-image=, --osd-database-size=0, --osd-store=, --osd-wal-size=576, --osds-per-device=1, --pvc-backed-osd=false, --service-account=
2020-09-24 22:49:49.106117 I | op-mon: parsing mon endpoints: h=10.104.89.66:6789,a=10.100.60.99:6789,b=10.97.14.186:6789
2020-09-24 22:49:49.156931 I | op-osd: CRUSH location=root=default host=stumethyst-403-testtrack4-com
2020-09-24 22:49:49.157010 I | cephcmd: crush location of osd: root=default host=stumethyst-403-testtrack4-com
2020-09-24 22:49:49.157049 D | exec: Running command: nsenter --mount=/rootfs/proc/1/ns/mnt -- /usr/sbin/lvm --help
2020-09-24 22:49:49.186104 I | cephosd: successfully called nsenter
2020-09-24 22:49:49.186187 I | cephosd: binary "/usr/sbin/lvm" found on the host, proceeding with osd preparation
2020-09-24 22:49:49.227216 D | cephclient: No ceph configuration override to merge as "rook-config-override" configmap is empty
2020-09-24 22:49:49.227289 I | cephclient: writing config file /var/lib/rook/rook-ceph/rook-ceph.config
2020-09-24 22:49:49.227752 I | cephclient: generated admin config in /var/lib/rook/rook-ceph
2020-09-24 22:49:49.228451 D | cephosd: config file @ /etc/ceph/ceph.conf: [global]
fsid                = a179d670-145f-43e0-9c27-1e4341c10593
mon initial members = a b h
mon host            = [v2:10.100.60.99:3300,v1:10.100.60.99:6789],[v2:10.97.14.186:3300,v1:10.97.14.186:6789],[v2:10.104.89.66:3300,v1:10.104.89.66:6789]
public addr         = 10.40.0.4
cluster addr        = 10.40.0.4
[client.admin]
keyring = /var/lib/rook/rook-ceph/client.admin.keyring
2020-09-24 22:49:49.228502 I | cephosd: discovering hardware
2020-09-24 22:49:49.228533 D | exec: Running command: lsblk --all --noheadings --list --output KNAME
2020-09-24 22:49:49.240701 D | exec: Running command: lsblk /dev/sda --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-09-24 22:49:49.252139 D | exec: Running command: sgdisk --print /dev/sda
2020-09-24 22:49:49.262983 D | exec: Running command: udevadm info --query=property /dev/sda
2020-09-24 22:49:49.283438 D | exec: Running command: lsblk --noheadings --pairs /dev/sda
2020-09-24 22:49:49.295515 D | exec: Running command: lsblk /dev/mmcblk1 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-09-24 22:49:49.304611 D | exec: Running command: sgdisk --print /dev/mmcblk1
2020-09-24 22:49:49.313816 D | exec: Running command: udevadm info --query=property /dev/mmcblk1
2020-09-24 22:49:49.335659 D | exec: Running command: lsblk --noheadings --pairs /dev/mmcblk1
2020-09-24 22:49:49.348427 I | inventory: skipping device "mmcblk1" because it has child, considering the child instead.
2020-09-24 22:49:49.348552 D | exec: Running command: lsblk /dev/mmcblk1p1 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-09-24 22:49:49.356652 D | exec: Running command: udevadm info --query=property /dev/mmcblk1p1
2020-09-24 22:49:49.378408 D | exec: Running command: lsblk /dev/mmcblk1p2 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-09-24 22:49:49.385087 D | exec: Running command: udevadm info --query=property /dev/mmcblk1p2
2020-09-24 22:49:49.402271 D | inventory: discovered disks are [0x40003da120 0x400052e5a0 0x40001caea0]
2020-09-24 22:49:49.402348 I | cephosd: creating and starting the osds
2020-09-24 22:49:49.438477 D | exec: Running command: stdbuf -oL ceph-volume --log-path /tmp/ceph-log drive-group
2020-09-24 22:49:50.457117 D | cephosd: usage: ceph-volume drive-group [-h] [--spec [SPEC]] [--dry-run] [path]
    Deploy OSDs according to a drive groups specification.
    The DriveGroup specification must be passed in json.
    It can either be (preference in this order)
      - in a file, path passed as a positional argument
      - read from stdin, pass "-" as a positional argument
      - a json string passed via the --spec argument
    Either the path postional argument or --spec must be specifed.
    
positional arguments:
  path           Path to file containing drive group spec or "-" to read from
                 stdin
optional arguments:
  -h, --help     show this help message and exit
  --spec [SPEC]  drive-group json string
  --dry-run      dry run, only print the batch command that would be run
2020-09-24 22:49:50.457326 I | cephclient: getting or creating ceph auth key "client.bootstrap-osd"
2020-09-24 22:49:50.457586 D | exec: Running command: ceph auth get-or-create-key client.bootstrap-osd mon allow profile bootstrap-osd --connect-timeout=15 --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --name=client.admin --keyring=/var/lib/rook/rook-ceph/client.admin.keyring --format json --out-file /tmp/747817831
2020-09-24 22:49:51.971538 I | cephosd: configuring Drive Group "storberry": {"data_devices":{"all":true},"placement":{"host_pattern":"*"},"service_id":"storberry"}
2020-09-24 22:49:51.971649 D | exec: Running command: stdbuf -oL ceph-volume --log-path /tmp/ceph-log drive-group --spec {"data_devices":{"all":true},"placement":{"host_pattern":"*"},"service_id":"storberry"}
```

**Comment by stuartpb** [comment]
Okay, I got the full logs via kubectl: [here](https://gist.github.com/stuartpb/2fd851ba38fb664ac483377eac2be952) is the full log output for the pod.

**Comment by stuartpb** [comment]
> ```
> 2020-09-24 22:49:49.438477 D | exec: Running command: stdbuf -oL ceph-volume --log-path /tmp/ceph-log drive-group
> 2020-09-24 22:49:50.457117 D | cephosd: usage: ceph-volume drive-group [-h] [--spec [SPEC]] [--dry-run] [path]
>     Deploy OSDs according to a drive groups specification.
>     The DriveGroup specification must be passed in json.
>     It can either be (preference in this order)
>       - in a file, path passed as a positional argument
>       - read from stdin, pass "-" as a positional argument
>       - a json string passed via the --spec argument
>     Either the path postional argument or --spec must be specifed.
>     
> positional arguments:
>   path           Path to file containing drive group spec or "-" to read from
>                  stdin
> optional arguments:
>   -h, --help     show this help message and exit
>   --spec [SPEC]  drive-group json string
>   --dry-run      dry run, only print the batch command that would be run
> ```

Hmm... if the spec is being passed in via stdin and that's the actual command line being executed, shouldn't it be `stdbuf -oL ceph-volume --log-path /tmp/ceph-log drive-group -` (ie. with a final `-`)?

**Comment by stuartpb** [comment]
It should be noted that this node was bought used (from Amazon Fulfillment), and the root of this failure could potentially be in hardware - let me know if there's something I could do to investigate that.

**Comment by stuartpb** [comment]
It's also worth noting that I flashed the other storage nodes around the beginning of the month; while they've all been kept up to date, it's theoretically possible that there could be a configuration difference introduced between the two that's causing only the newer host to fail.

The part where it can't find the physical volume looks vaguely like https://github.com/rook/rook/issues/5996#issuecomment-675342818

**Comment by stuartpb** [comment]
Anyway, whatever the issue with that one node is, it seems like it's separate from the original problem - I'll go ahead and open a separate ticket for it. Thanks!
