### ISSUE TITLE
Rancher CephCluster state shows error while ready

### ISSUE THREAD

**Issue by electrical** [rook/rook#6977]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Rancher CephCluster resource details show confusing status.
The cluster is up and running fine and there are no errors further, but the 'error' state can be very confusing.

Screenshot: 

![Screenshot 2021-01-14 at 19 16 28](https://user-images.githubusercontent.com/271677/104638980-c7181d80-569e-11eb-962f-4898b7464767.png)

**Environment**:

* Rook version (use `rook version` inside of a Rook Pod): 1.5.5

**Comment by travisn** [comment]
From the [slack discussion](https://rook-io.slack.com/archives/CK9CF5H2R/p1610650897015100), it seems the problem is that the `ProgressingCompleted` condition is set to `false` instead of `true`.
```
 - lastHeartbeatTime: "2021-01-14T18:47:11Z"
    lastTransitionTime: "2021-01-14T18:45:43Z"
    message: Cluster progression is completed
    reason: ProgressingCompleted
    status: "False"
 ```

**Comment by electrical** [comment]
Here is the full yaml output of the CephCluster resource https://gist.github.com/electrical/4276dd79df2886d2e84229739c9e6e85

**Comment by travisn** [comment]
I believe this is fixed by #7059 in the v1.5.6 rook release last week. @electrical Do you see it is fixed now after upgrading?

**Comment by electrical** [comment]
I'll verify as soon as possible. Thanks!

**Comment by electrical** [comment]
@travisn I've done a fresh deployment on a new cluster and it's not fixed.

Output of the cephClusters resource: https://gist.github.com/electrical/c2f489f8f96da6adb562930bc1eb5be7

**Comment by travisn** [comment]
The "Ready" action is "true" since the cluster is done being configured and the "Progressing" action is "false" because it has completed. Is Rancher expecting "Progressing" to be "True"? That doesn't seem right either.
```
  - lastHeartbeatTime: "2021-02-03T19:49:07Z"
    lastTransitionTime: "2021-02-03T19:44:58Z"
    message: Cluster progression is completed
    reason: ProgressingCompleted
    status: "False"
    type: Progressing
  - lastHeartbeatTime: "2021-02-03T19:49:06Z"
    lastTransitionTime: "2021-02-03T19:49:06Z"
    message: Cluster created successfully
    reason: ClusterCreated
    status: "True"
    type: Ready
```

**Comment by electrical** [comment]
I think it's related to the `lastHeartbeatTime ` from what can see ?

**Comment by electrical** [comment]
As an example, this is from the remote cluster connecting to the ceph cluster:
In this case the`lastHeartbeatTime` for the connected status is after the connecting status.

```
  conditions:
  - lastHeartbeatTime: "2021-02-03T23:03:35Z"
    lastTransitionTime: "2021-02-03T23:03:35Z"
    message: Cluster is connecting
    reason: ClusterConnecting
    status: "True"
    type: Connecting
  - lastHeartbeatTime: "2021-02-03T23:03:45Z"
    lastTransitionTime: "2021-02-03T23:03:45Z"
    message: Cluster connected successfully
    reason: ClusterConnected
    status: "True"
    type: Connected
```

**Comment by ron1** [comment]
Maybe Rancher is simply looking for the status to be True of the lastest condition, i.e., the condition with the most recent lastHeartbeatTime in the case of CephCluster. If so, can the rook-ceph operator be modified to set conditions in such a way that Rancher expectations are satisfied?

**Comment by electrical** [comment]
Had another look at the output:

```
  - lastHeartbeatTime: "2021-02-06T07:58:32Z"
    lastTransitionTime: "2021-02-03T19:44:58Z"
    message: Cluster progression is completed
    reason: ProgressingCompleted
    status: "False"
    type: Progressing
  - lastHeartbeatTime: "2021-02-03T19:49:06Z"
    lastTransitionTime: "2021-02-03T19:49:06Z"
    message: Cluster created successfully
    reason: ClusterCreated
    status: "True"
    type: Ready
```

For some reason the `ProgressingCompleted` event gets updated frequently. I'm not sure what process within Rook-ceph handles that.

**Comment by ron1** [comment]
And maybe rook-ceph should ensure that under normal circumstances it follows up a ProgressingCompleted condition with a condition whose status is "true".

**Comment by ron1** [comment]
@travisn @electrical What do you think about this [patch](https://github.com/rook/rook/compare/master...ron1:fix-ceph-cluster-ready-status-condition-ordering) for the issue that orders the conditions such that the false condition is created before the true Ready condition?

**Comment by travisn** [comment]
> @travisn @electrical What do you think about this [patch](https://github.com/rook/rook/compare/master...ron1:fix-ceph-cluster-ready-status-condition-ordering) that orders the conditions such that the false condition is created before the true Ready condition? I suspect this will satisfy the requirements imposed by Rancher Continuous Delivery.

Agreed, the only thing I can see here as well is that the timestamps aren't ordered as Rancher expects them, moving that check up would make sense in that case. Please do open a PR for that, thanks!

**Comment by ron1** [comment]
@travisn Since the false condition is now created before the true Ready condition, it seems that the setting of LastTransitionTime and LastHeartbeatTime to metav1.NewTime(time.Now()) should provide the desired behavior. Am I missing something?

**Comment by travisn** [comment]
> @travisn Since the false condition is now created before the true Ready condition, I was thinking that the setting of timestamps LastTransitionTime and LastHeartbeatTime to metav1.NewTime(time.Now()) should provide the desired ordering. Am I missing something?

If there was a transition, I see both those timestamps updated to `time.Now()` in the code [here](https://github.com/rook/rook/blob/d99092dcfc82b3d02c412358e1b84c7287f4f4bf/pkg/operator/ceph/config/conditions.go#L75-L79). Is this what you're looking for?

Perhaps what we need is that the progress condition not have the heartbeat updated if it's not in progress (and it didn't just complete being in progress).

**Comment by ron1** [comment]
But since the false condition in the patch is now created before the Ready true condition, `time.now()` for the false condition will be earlier than the true condition which is the requirement.

**Comment by travisn** [comment]
> But since the false condition in the patch is now created before the Ready true condition via `ConditionExport` from `checkConditionFalse`, `time.now()` for the false condition will be earlier than the `time.now()` from the true condition which should satisfy the requirement.

Agreed, this should do it, I thought you were referring to some other need to set the timestamp.

**Comment by electrical** [comment]
The logic sounds good yeah. Looking forward to try it out :-)

**Comment by ron1** [comment]
The CephCluster Status in the test results her: https://pipelines.actions.githubusercontent.com/iiogn9Wx5zqXCM87xPkIxnTPJIdS2VhbCKrLZsm52MBx3qEW56/_apis/pipelines/1/runs/20818/signedlogcontent/12?urlExpires=2021-02-11T16%3A06%3A18.4258477Z&urlSigningMethod=HMACV1&urlSignature=w8KHCU4aoNkFWYiRYnRbs%2BK5cs8R%2Bu%2FFUlMG3GKnMkQ%3D for the revised patch look promising.
