### ISSUE TITLE
Object Storage page does not load in the Ceph dashboard by default

### ISSUE THREAD

**Issue by travisn** [rook/rook#9660]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The object store pages in the Ceph dashboard are not loading. This seems a regression since #4676 was implemented to set the rgw creds as required for the dashboard. I'm not seeing what is missing now so the dashboard will work for the object store.

**Expected behavior:**
When the object store CR is created and configured by Rook, the dashboard object store should automatically be enabled. 

**How to reproduce it (minimal and precise):**

- kubectl create -f crds.yaml -f common.yaml -f operator.yaml
- kubectl create -f cluster-test.yaml -f object-test.yaml
- After the rgw daemon is configured, go to the ceph dashboard
- Click on the "Object Gateway" and one of the pages (Daemons, Users, or Buckets)
- See that the pages are not loading.

![Screen Shot 2022-01-26 at 3 38 09 PM](https://user-images.githubusercontent.com/1048514/151258896-f2c7bb6e-5a3d-44d1-868b-9d8f0292feee.png)

**Comment by thotz** [comment]
@travisn can you please give details about the ceph version in which this issue is seen?

**Comment by travisn** [comment]
@thotz  This is with the latest rook master and Ceph 16.2.7.

**Comment by thotz** [comment]
@travisn : I tried with latest master and ceph v16.2.7, not able to reproduce this issue 
![image](https://user-images.githubusercontent.com/2588766/151775601-1f3c0ccd-b83d-4528-8853-6b2165745717.png)

**Comment by travisn** [comment]
@thotz What is your environment? Testing in a fresh minikube, I get the same issue. 

I should have attached the mgr logs before, looks like there is an exception being hit in the mgr. Attached is the full log. 
[mgr-a.log](https://github.com/rook/rook/files/7974870/mgr-a.log). 
Where is it getting the endpoint `172.17.0.1:8080`? I don't see any K8s services or pod IPs with that ip.

```
debug 2022-01-31T23:12:14.440+0000 7fc2ed303700  0 [dashboard INFO rgw_client] Found RGW daemon with configuration: host=172.17.0.1, port=8080, ssl=False
debug 2022-01-31T23:12:14.445+0000 7fc2ed303700  0 [dashboard ERROR rest_client] RGW REST API failed GET, connection error (url=http://172.17.0.1:8080/admin/metadata/user?myself): [errno: 111] Connection refused
debug 2022-01-31T23:12:14.456+0000 7fc2ed303700  0 [dashboard ERROR rgw_client] RGW REST API cannot be reached: Connection refused [errno 111]. Please check your configuration and that the API endpoint is accessible
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 162, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1269, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1315, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1264, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 978, in send
    self.connect()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 184, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 171, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fc2eb2985c0>: Failed to establish a new connection: [Errno 111] Connection refused

```

**Comment by thotz** [comment]
@travisn:  Mine setup is with minikube but it bit old version 

Even I don't have much idea. I fell like `172.17.0.1:8080` set from mgr module itself. The from `src/pybind/mgr/dashboard/services/rgw_client.py` it tries to find daemon server address and port from a `service map` of the manager, not sure how it is populated

Before the above exception there was another occurred from your logs
debug 2022-01-31T23:12:06.708+0000 7fc2f0309700  0 [dashboard ERROR exception] Internal Server Error
Traceback (most recent call last):
  File "/usr/share/ceph/mgr/dashboard/services/exception.py", line 46, in dashboard_exception_handler
    return handler(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/share/ceph/mgr/dashboard/controllers/home.py", line 135, in __call__
    return serve_file(full_path)
  File "/usr/lib/python3.6/site-packages/cherrypy/lib/static.py", line 77, in serve_file
    cptools.validate_since()
  File "/usr/lib/python3.6/site-packages/cherrypy/lib/cptools.py", line 116, in validate_since
    raise cherrypy.HTTPRedirect([], 304)

May post this retry to get RGW daemon details, I can also a lot of reference for "172.17.0.1" in the logs, looks like `docker0` of your machine/vm. 
Can please check with console/dashboard team who may know the actual code flow.

**Comment by jmolmo** [comment]
@travisn:  As @thotz commented the [Ceph dashboard retrieves the list of rgw endpoints](https://github.com/ceph/ceph/blob/40a71744915433ab436ff9663e040e0768b4d53e/src/pybind/mgr/dashboard/services/rgw_client.py#L60) from the ceph service_map.

The error found in the manager log points towards two different possibilities:

1. The RGW daemon is in 172.17.0.1:8080 and "something" blocks communication. We can discard this part , because you said that there is no service/pod using that direction
2. The service_map is providing the wrong ip for the rgw endpoints... I do not know what component is filling the "service_map" (it seems a dark point for most of us, maybe the rgw daemon pass this information to the mon/mgr?), so the problem must be there. (And also is very strange that the problem happens in minikube and not in other envs. )

In any case , I think it is important to remark that in cephadm, we must configure explicitly the rgw endpoints in order to [provide the right RGW ](https://github.com/ceph/ceph/blob/40a71744915433ab436ff9663e040e0768b4d53e/src/pybind/mgr/cephadm/services/cephadmservice.py#L830) endpoint for each rgw daemon.

In Rook Operator I have not found nothing similar.

Can you check if using manually the command :

`# ceph config set client.rgw.daemonx beast endpoint=<ip>:<port>`
Note: Double check you are using the right parameter for your env.

The problem is fixed?

**Comment by epuertat** [comment]
@travisn have you checked if running [`ceph dashboard set-rgw-credentials`](https://docs.ceph.com/en/latest/mgr/dashboard/#enabling-the-object-gateway-management-frontend) does the trick? That was a change introduced in 16.2.6 and cephadm uses it for configuring Dashboard-RGW. I just grepped the Rook repo and saw it still uses the old way (`set-rgw-api-access-key` and `set-rgw-api-secret-key`).

**Comment by travisn** [comment]
@epuertat The `set-rgw-credentials` fails in the rook toolbox. Perhaps the way rook names the realm, zone, and zonegroup isn't compatible? Would you expect the old way to be broken though? At least those calls to `set-rgw-api-access-key` and `set-rgw-api-secret-key` are succeeding.
```
$ ceph dashboard set-rgw-credentials
Error EINVAL: No RGW credentials found, please consult the documentation on how to enable RGW for the dashboard.
```

@jmolmo `beast` doesn't seem to be the correct setting, this isn't working for me, I don't see documentation on that setting.
```
$  ceph config set client.rgw.my.store.a beast endpoint=10.105.237.69:80
Error EINVAL: unrecognized config option 'beast'
```

**Comment by epuertat** [comment]
@travisn that last error message [point to this code](https://github.com/ceph/ceph/blob/75c4960abf3b81ff7c6f36e816e1c6a29ceabc9e/src/pybind/mgr/dashboard/services/rgw_client.py#L267). As you may see it's mostly consuming the radosgw-admin from the CLI. That failure might mean that the CLI tool is not accessible there or it failed to start. The radosgw-admin command performed are:
* `realm list`
* `user info --uid <user_id>` (with `--rgw-realm ...` in case realms are defined)
* As system user is expected, otherwise it'll be created.

And, the previous error you mentioned ("where the 172.17.0.1:8080 comes from") seems to point to [this chunk of code](https://github.com/ceph/ceph/blob/75c4960abf3b81ff7c6f36e816e1c6a29ceabc9e/src/pybind/mgr/dashboard/services/rgw_client.py#L64-L75), as you may see it uses the service map to obtain the RGW endpoint URL.

BTW, is there any way for us to trigger the Rook CI against a given Ceph PR (to avoid this kind of regressions)?

**Comment by travisn** [comment]
> @travisn that last error message [point to this code](https://github.com/ceph/ceph/blob/75c4960abf3b81ff7c6f36e816e1c6a29ceabc9e/src/pybind/mgr/dashboard/services/rgw_client.py#L267). As you may see it's mostly consuming the radosgw-admin from the CLI. That failure might mean that the CLI tool is not accessible there or it failed to start. The radosgw-admin command performed are:
> 
> * `realm list`
> * `user info --uid <user_id>` (with `--rgw-realm ...` in case realms are defined)
> * As system user is expected, otherwise it'll be created.

Rook does have a realm:
```
[rook@rook-ceph-tools-d6d7c985c-rjw4x /]$ radosgw-admin realm list
{
    "default_info": "0e002acd-bd7f-4766-afc5-42f28dee92cf",
    "realms": [
        "my-store"
    ]
}
```
And three users:
```
[rook@rook-ceph-tools-d6d7c985c-rjw4x /]$ radosgw-admin user list --rgw-realm my-store
[
    "dashboard-admin",
    "rook-ceph-internal-s3-user-checker-c555e12c-f764-4c42-af38-eb63e1a95a2a",
    "rgw-admin-ops-user"
]
```
Which uid is being queried?

> And, the previous error you mentioned ("where the 172.17.0.1:8080 comes from") seems to point to [this chunk of code](https://github.com/ceph/ceph/blob/75c4960abf3b81ff7c6f36e816e1c6a29ceabc9e/src/pybind/mgr/dashboard/services/rgw_client.py#L64-L75), as you may see it uses the service map to obtain the RGW endpoint URL.

So Rook is missing to set the RGW endpoint in the service map? Which command is that?

> BTW, is there any way for us to trigger the Rook CI against a given Ceph PR (to avoid this kind of regressions)?

The Rook CI runs daily against the Ceph master build, but we don't have a way to run against a Ceph PR since we would need a published image. While the Rook CI enables the dashboard, there is no validation of the dashboard done in rook. We should chat about how to add some basic testing in Rook though.

**Comment by epuertat** [comment]
> > @travisn that last error message [point to this code]
> And three users:
> 
> ```
> [rook@rook-ceph-tools-d6d7c985c-rjw4x /]$ radosgw-admin user list --rgw-realm my-store
> [
>     "dashboard-admin",
>     "rook-ceph-internal-s3-user-checker-c555e12c-f764-4c42-af38-eb63e1a95a2a",
>     "rgw-admin-ops-user"
> ]
> ```
> 
> Which uid is being queried?

That might be it: the [expected user is `dashboard`](https://github.com/ceph/ceph/blob/75c4960abf3b81ff7c6f36e816e1c6a29ceabc9e/src/pybind/mgr/dashboard/services/rgw_client.py#L238).

> > And, the previous error you mentioned ("where the 172.17.0.1:8080 comes from") seems to point to [this chunk of code](https://github.com/ceph/ceph/blob/75c4960abf3b81ff7c6f36e816e1c6a29ceabc9e/src/pybind/mgr/dashboard/services/rgw_client.py#L64-L75), as you may see it uses the service map to obtain the RGW endpoint URL.
> 
> So Rook is missing to set the RGW endpoint in the service map? Which command is that?

I'd assume that rgw sets that itself (there have been recent changes on that part, but only on daemon names/ids).

> > BTW, is there any way for us to trigger the Rook CI against a given Ceph PR (to avoid this kind of regressions)?
> 
> The Rook CI runs daily against the Ceph master build, but we don't have a way to run against a Ceph PR since we would need a published image. While the Rook CI enables the dashboard, there is no validation of the dashboard done in rook. We should chat about how to add some basic testing in Rook though.

Sure! BTW we have e2e tests (simulating user actions on a browser) that technically should be independent from the underlying orchestration (it's just JS directly from the browser), so you could launch them here with a [Github action](https://github.com/cypress-io/github-action) or Jenkins.

**Comment by travisn** [comment]
> expected user is `dashboard`

So the `ceph dashboard set-rgw-credentials` should be creating the `dashboard` user when it isn't found, right?

**Comment by epuertat** [comment]
Looks so... Since it's not there, it might mean that the radosgw-admin command didn't work (permissions, roles, ?), but in that case we would get a "Unable to create rgw use".

**Comment by galexrt** [comment]
@travisn I haven't seen this with #10137. The PR is improving the "does the user exist in the object store" detecting in general and not just when two object stores exist.

When the PR has been merged, a fix should be to delete the `dashboard-admin` user from the object store(s) and wait till the operator has reconciled the object store(s). `radosgw-admin user rm --uid=dashboard-admin --rgw-realm=OBJECTSTORE_NAME` (`OBJECTSTORE_NAME` can also be retrieved using `radosgw-admin realm list`).

**Comment by travisn** [comment]
It seems I'm the only one not seeing the object store not working. Are you testing in minikube as well? Even testing with #10137 I still see that the dashboard says it is not configured.

**Comment by galexrt** [comment]
@travisn I have checked on a multi node live cluster :dagger: 
Can you check if `ceph dashboard get-rgw-...key` returns something in the minikube cluster? Maybe something isn't getting correctly initialized.

**Comment by travisn** [comment]
Yes, it has a dashboard key configured in the test cluster:
```
$ ceph dashboard get-rgw-api-access-key
M361YN2M3A2ONW24AO2Z
$ ceph dashboard get-rgw-api-secret-key
CdnwRhCLbiuGbKY6mpj1BTeKjGlo9IZ1EncOiBAQ
```
I tried both with v16 and v17, restarted the mgr pod, refreshed the browser, etc, and still can't get the object store to show in the dashboard.

**Comment by galexrt** [comment]
@travisn Are you getting the same error in the logs? I'll try to reproduce it tomorrow.

**Comment by travisn** [comment]
> @travisn Are you getting the same error in the logs? I'll try to reproduce it tomorrow.

The error in the logs is still the same as posted [earlier](https://github.com/rook/rook/issues/9660#issuecomment-1026323910). 
Do you see a `dashboard` user in your cluster where it is working? Or consistent rgw user info compared to [this comment](https://github.com/rook/rook/issues/9660#issuecomment-1029457591)?

**Comment by galexrt** [comment]
Does this still happen with the latest v1.9.2 release?

**Comment by travisn** [comment]
> Does this still happen with the latest v1.9.2 release?

With the latest master I still see the same failure. Was there a related change you hoped would fix it?

**Comment by suneclausen** [comment]
I have also experienced this issue (https://github.com/rook/rook/issues/9268) without resolving it. Hope this thread finds something that can make it work.

**Comment by quantiphi-adityaraparthi-ayla** [comment]
I had faced the similar issue when i replaced my failed OSD.. I was able to access all the pages in dashboard apart from daemon,users and bucket which are not loading and getting message as "Page Not Found" , although all those are getting access by s3 client.. 
Later i restarted the operator then the issue got resolved automatically in sometime..

**Comment by adityarap** [comment]
I had the similar issue when i have replaced my failed OSD then Object Storage page does not load in the Ceph dashboard. 
Although it can be accessed by using s3 client.. Later i have restarted operator then the issue got resolved automatcially..

**Comment by ningjunwei2** [comment]
@adityarap  i try delete the operator pod ,then it will start a new operator pod ,but it dont work

**Comment by travisn** [comment]
Still seems an issue

**Comment by vyom-soft** [comment]
May I know If this issue has been fixed in 1.10.4? or upper.

**Comment by travisn** [comment]
> May I know If this issue has been fixed in 1.10.4? or upper.

The rgw dashboard seems to work in some clusters, but not others, not sure on the solution for those clusters yet.

**Comment by jarnfast** [comment]
This appears to be coupled with the CNI used in cluster. Did some tests with RKE2 on AlmaLinux today.

The rgw dashboard does not work when running with Canal (flannel+calico) or Calico CNIs - but when using Cilium as CNI it works.

When looking at the servicemap it's obvious that when the Cilium CNI is used the servicemap contains the correct address - ie. the Pod IP. With the other CNIs the Node IP is returned as address.

**Cilium CNI**

```sh
$ kubectl -n rook-ceph get pods -o wide
NAME                                                         READY   STATUS      RESTARTS       AGE   IP               NODE               NOMINATED NODE   READINESS GATES
csi-cephfsplugin-fkv5j                                       2/2     Running     6 (17m ago)    97m   192.168.200.11   wn1.hyperv.local   <none>           <none>
..
rook-ceph-rgw-backup-a-685c8df759-lnwxg                      2/2     Running     12 (17m ago)   80m   10.42.0.93       wn1.hyperv.local   <none>           <none>
rook-ceph-rgw-backup-a-685c8df759-nfwrm                      2/2     Running     12 (17m ago)   80m   10.42.0.47       wn1.hyperv.local   <none>           <none>
```
ServiceMap (slimmed)
```json
{
  "services": {
    "rgw": {
      "daemons": {
        "summary": "",
        "64204": {
          "gid": 64204,
          "addr": "10.42.0.93:0/532643170",
          "metadata": {
            "arch": "x86_64",
            "ceph_release": "quincy",
            "ceph_version": "ceph version 17.2.5 (98318ae89f1a893a6ded3a640405cdbb33e08757) quincy (stable)",
            "frontend_config#0": "beast port=8080",
            "frontend_type#0": "beast",
            "hostname": "wn1.hyperv.local",
            "id": "backup.a",
            "pod_name": "rook-ceph-rgw-backup-a-685c8df759-lnwxg",
            "pod_namespace": "rook-ceph"
          }
        },
        "64286": {
          "gid": 64286,
          "addr": "10.42.0.47:0/975370012",
          "metadata": {
            "arch": "x86_64",
            "ceph_release": "quincy",
            "ceph_version": "ceph version 17.2.5 (98318ae89f1a893a6ded3a640405cdbb33e08757) quincy (stable)",
            "frontend_config#0": "beast port=8080",
            "frontend_type#0": "beast",
            "hostname": "wn1.hyperv.local",
            "id": "backup.a",
            "pod_name": "rook-ceph-rgw-backup-a-685c8df759-nfwrm",
            "pod_namespace": "rook-ceph"
          }
        }
      }
    }
  }
}
```

**Canal CNI**
```sh
$ kubectl -n rook-ceph get pods -o wide
NAME                                                         READY   STATUS      RESTARTS         AGE    IP               NODE               NOMINATED NODE   READINESS GATES
csi-cephfsplugin-fkv5j                                       2/2     Running     8 (3m42s ago)    129m   192.168.200.11   wn1.hyperv.local   <none>           <none>
..
rook-ceph-rgw-backup-a-685c8df759-lnwxg                      2/2     Running     16 (3m42s ago)   112m   10.42.0.169      wn1.hyperv.local   <none>           <none>
rook-ceph-rgw-backup-a-685c8df759-nfwrm                      2/2     Running     16 (3m42s ago)   112m   10.42.0.163      wn1.hyperv.local   <none>           <none>
```
ServiceMap (slimmed)
```json
{
  "services": {
    "rgw": {
      "daemons": {
        "summary": "",
        "84289": {
          "gid": 84289,
          "addr": "192.168.200.11:0/2871551955",
          "metadata": {
            "arch": "x86_64",
            "ceph_release": "quincy",
            "frontend_config#0": "beast port=8080",
            "frontend_type#0": "beast",
            "hostname": "wn1.hyperv.local",
            "id": "backup.a",
            "pod_name": "rook-ceph-rgw-backup-a-685c8df759-lnwxg",
            "pod_namespace": "rook-ceph"
          }
        },
        "84290": {
          "gid": 84290,
          "addr": "192.168.200.11:0/901403975",
          "metadata": {
            "arch": "x86_64",
            "ceph_release": "quincy",
            "ceph_version": "ceph version 17.2.5 (98318ae89f1a893a6ded3a640405cdbb33e08757) quincy (stable)",
            "frontend_config#0": "beast port=8080",
            "frontend_type#0": "beast",
            "hostname": "wn1.hyperv.local",
            "id": "backup.a",
            "pod_name": "rook-ceph-rgw-backup-a-685c8df759-nfwrm",
            "pod_namespace": "rook-ceph"
          }
        }
      }
    }
  }
}
```

**Comment by zer0def** [comment]
I can confirm @jarnfast's findings with just Flannel, as services declared in `ceph service dump` map onto node-local CNI bridge interface's address, `cni0`, on a cluster running on the overlay, not on host networking. I would guess that `192.168.200.11` in that context is a node's host netns address, per workaround described [here](https://github.com/rook/rook/issues/4006#issuecomment-602044153).

I've also noticed requests' source addresses to be either those of `cni0` when done locally and `flannel.1` when done across nodes, as if they were never properly encapsulated.
```
$ kubectl -n rook-ceph get pods -o wide; echo =====; kubectl -n rook-ceph exec -ti rook-ceph-tools-df7cf696d-f2tv4 -- ceph service dump; echo =====; lxc ls
NAME                                                        READY   STATUS      RESTARTS   AGE   IP               NODE                            NOMINATED NODE   READINESS GATES
csi-cephfsplugin-6lrvg                                      2/2     Running     0          38m   10.156.217.16    kubedee-rookery-worker-vwubri   <none>           <none>
csi-cephfsplugin-j8sg8                                      2/2     Running     0          38m   10.156.217.218   kubedee-rookery-worker-k1t8nj   <none>           <none>
csi-rbdplugin-86p4h                                         2/2     Running     0          38m   10.156.217.218   kubedee-rookery-worker-k1t8nj   <none>           <none>
csi-rbdplugin-ffjk7                                         2/2     Running     0          38m   10.156.217.16    kubedee-rookery-worker-vwubri   <none>           <none>
rook-ceph-rgw-my-store-a-6b74477d78-92dss                   1/1     Running     0          32m   10.244.1.60      kubedee-rookery-worker-k1t8nj   <none>           <none>
rook-ceph-rgw-my-store-a-6b74477d78-dvbjv                   1/1     Running     0          32m   10.244.2.48      kubedee-rookery-worker-vwubri   <none>           <none>
=====
{
    "epoch": 8,
    "modified": "2023-02-18T22:37:37.885734+0000",
    "services": {
        "rgw": {
            "daemons": {
                "summary": "",
                "14815": {
                    "start_epoch": 6,
                    "start_stamp": "2023-02-18T22:13:13.088544+0000",
                    "gid": 14815,
                    "addr": "10.244.1.1:0/757689985",
                    "metadata": {
                        "arch": "x86_64",
                        "ceph_release": "quincy",
                        "ceph_version": "ceph version 17.2.5 (98318ae89f1a893a6ded3a640405cdbb33e08757) quincy (stable)",
                        "ceph_version_short": "17.2.5",
                        "container_hostname": "rook-ceph-rgw-my-store-a-6b74477d78-92dss",
                        "container_image": "quay.io/ceph/ceph:v17.2.5",
                        "frontend_config#0": "beast port=8080",
                        "frontend_type#0": "beast",
                        "hostname": "kubedee-rookery-worker-k1t8nj",
                        "id": "my.store.a",
                        "kernel_description": "#1 SMP PREEMPT_DYNAMIC Debian 6.1.8-1 (2023-01-29)",
                        "kernel_version": "6.1.0-3-amd64",
                        "mem_swap_kb": "262140",
                        "mem_total_kb": "12249644",
                        "num_handles": "1",
                        "os": "Linux",
                        "pid": "1",
                        "pod_name": "rook-ceph-rgw-my-store-a-6b74477d78-92dss",
                        "pod_namespace": "rook-ceph",
                        "realm_id": "95599dec-185a-4453-8aa7-5464f6cc45b3",
                        "realm_name": "rookery",
                        "zone_id": "85747c80-8b87-41c1-99e4-e8010f93047b",
                        "zone_name": "rookery-a-rook-ceph",
                        "zonegroup_id": "acdc07aa-54ca-45eb-81f4-56d6feb6effe",
                        "zonegroup_name": "rookery-a"
                    },
                    "task_status": {}
                },
                "27281": {
                    "start_epoch": 6,
                    "start_stamp": "2023-02-18T22:13:13.130039+0000",
                    "gid": 27281,
                    "addr": "10.244.2.1:0/3907149699",
                    "metadata": {
                        "arch": "x86_64",
                        "ceph_release": "quincy",
                        "ceph_version": "ceph version 17.2.5 (98318ae89f1a893a6ded3a640405cdbb33e08757) quincy (stable)",
                        "ceph_version_short": "17.2.5",
                        "container_hostname": "rook-ceph-rgw-my-store-a-6b74477d78-dvbjv",
                        "container_image": "quay.io/ceph/ceph:v17.2.5",
                        "frontend_config#0": "beast port=8080",
                        "frontend_type#0": "beast",
                        "hostname": "kubedee-rookery-worker-vwubri",
                        "id": "my.store.a",
                        "kernel_description": "#1 SMP PREEMPT_DYNAMIC Debian 6.1.8-1 (2023-01-29)",
                        "kernel_version": "6.1.0-3-amd64",
                        "mem_swap_kb": "262140",
                        "mem_total_kb": "12249652",
                        "num_handles": "1",
                        "os": "Linux",
                        "pid": "1",
                        "pod_name": "rook-ceph-rgw-my-store-a-6b74477d78-dvbjv",
                        "pod_namespace": "rook-ceph",
                        "realm_id": "95599dec-185a-4453-8aa7-5464f6cc45b3",
                        "realm_name": "rookery",
                        "zone_id": "85747c80-8b87-41c1-99e4-e8010f93047b",
                        "zone_name": "rookery-a-rook-ceph",
                        "zonegroup_id": "acdc07aa-54ca-45eb-81f4-56d6feb6effe",
                        "zonegroup_name": "rookery-a"
                    },
                    "task_status": {}
                }
            }
        }
    }
}
=====
+-------------------------------+---------+------------------------+------+-----------------+-----------+
|             NAME              |  STATE  |          IPV4          | IPV6 |      TYPE       | SNAPSHOTS |
+-------------------------------+---------+------------------------+------+-----------------+-----------+
| kubedee-rookery-worker-k1t8nj | RUNNING | 10.244.1.1 (cni0)      |      | VIRTUAL-MACHINE | 0         |
|                               |         | 10.244.1.0 (flannel.1) |      |                 |           |
|                               |         | 10.161.38.185 (eth0)   |      |                 |           |
+-------------------------------+---------+------------------------+------+-----------------+-----------+
| kubedee-rookery-worker-vwubri | RUNNING | 10.244.2.1 (cni0)      |      | VIRTUAL-MACHINE | 0         |
|                               |         | 10.244.2.0 (flannel.1) |      |                 |           |
|                               |         | 10.161.38.109 (eth0)   |      |                 |           |
+-------------------------------+---------+------------------------+------+-----------------+-----------+
```

**Comment by zer0def** [comment]
Not willing to call it a solution just yet, but managed to solve the service map issue by making sure that `kube-proxy`'s `--cluster-cidr` overlaps with the pod CIDR, so that pod traffic isn't masqueraded when contacting a service, which also forces putting `--service-cluster-ip-range` on `kube-apiserver` and `kube-controller-manager` to be within the cluster/pod CIDR, since I can't be bothered to add more complexity through additional routing.

**Comment by jarnfast** [comment]
FWIW ceph 18.0.0 appears to break everything as they move to using the `metadata.hostname` property instead of `addr`: https://github.com/ceph/ceph/commit/ca8f77d6a7fa361328a942e3f37c81dd9577d4de

Great for bare-metal installations .. k8s not so much.

**Comment by zer0def** [comment]
Pods created as part of a StatefulSet referring to a headless service (through `.spec.serviceName`) are aware of their FQDN through said service, so it could become a reasonable fallback.

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: patroni-f0f0a337-config
  namespace: openstack
spec:
  clusterIP: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: patroni-f0f0a337
  namespace: openstack
spec:
  serviceName: patroni-f0f0a337-config
  selector:
    matchLabels:
      app: patroni
      component: pgsql
      release: patroni-f0f0a337
  template:
    metadata:
      labels:
        app: patroni
        component: pgsql
        release: patroni-f0f0a337
```

```sh
kubectl -n openstack exec -tic patroni pod/patroni-f0f0a337-1 -- hostname -f
patroni-f0f0a337-1.patroni-f0f0a337-config.openstack.svc.cluster.local
```

**Comment by xoxys** [comment]
I have the same issue on a k3s cluster with calico.

**Comment by galexrt** [comment]
Had a great discussion with @avanthakkar and others at Ceph dev summit in Amsterdam. We were able to narrow it down in my private Rook Ceph cluster. The 2nd point is the one that might be causing the main source of this issue.

1. `ceph dashboard set-rgw-credentials` - It is run on the MGR, in Rook the MGR ceph.conf does not have the mon_hosts in it, as they are pased in through the startup flags/args.
    * Make Rook pass in the mon hosts to the MGR ceph.conf as well.
    * Or if the mon_hosts flag is set on the MGR, pass it on to the "run rgwadmin command" function in the MGR.
2. Ceph dashboard uses the RGW daemon host instead of the "service address", e.g., Rook in hostnetwork mode tries to connect to "k8s-node-01:PORT" and not the K8S service address. NOTE: This might also affect, non-hostnetwork clusters (needs to be tested).
    * From Avan Thakkar: https://github.com/ceph/ceph/pull/42252 might have broken the "original" of getting **the "service name"** for an object store.
    * A way to set the "(reachable) service address" of each object store would be one way to get back a similiar experience as before,

**Comment by zer0def** [comment]
Per point 2.2., I think using StatefulSets with headless Services would work. This would be a change from existing use of Deployments, since Kubernetes validation no longer considers `.spec.serviceName` as valid there (if that had worked before), however Pods part of a StatefulSet with `.spec.serviceName` are both aware of their cluster-wide network identity (`hostname -f`) and targetable using in-cluster name resolution.

As for replicability, I'm reasonably certain every CNI configured to NAT inter-host traffic surfaces the issue. This could be highlighted by specifying `CephObjectStore`'s `.spec.gateway.placement` node and pod affinities in a manner placing all rgw pods/processes on the same node as, ideally, a single mgr pod relating to the target cluster.

Example Flannel configurations for masqueraded (breaking) and routed (working) `ConfigMap` data sections from my ephemeral test environment follow:

- masqueraded (default served by upstream):
```
data:
  cni-conf.json: |
    {
      "name": "cbr0",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "flannel",
          "delegate": {
            "type": "bridge",
            "hairpinMode": true,
            "isDefaultGateway": true
          }
        },
        {
          "type": "portmap",
          "capabilities": {"portMappings": true}
        }
      ]
    }
  net-conf.json: |
    {
      "Network": "10.244.0.0/16",
      "Backend": {"Type": "vxlan"}
    }
```

- routed:
```data:
  cni-conf.json: |
    {
      "name": "cbr0",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "flannel",
          "delegate": {
            "type": "ptp"
          },
          "ipam": {
            "type": "host-local",
            "routes": [{"dst":"0.0.0.0/0"}]
          }
        },
        {
          "type": "portmap",
          "capabilities": {"portMappings": true}
        }
      ]
    }
  net-conf.json: |
    {
      "Network": "10.244.0.0/16",
      "Backend": {"Type": "wireguard", "PSK": "1qZESW+TvIupS65Z42atCdyhkrJkBq8e3NWfDf+JsyA=", "PersistentKeepaliveInterval": 5}
    }
```

**Comment by mkhpalm** [comment]
Is the crux of this issue based on this change that is being back ported into older releases? 

* https://tracker.ceph.com/issues/56970
* 18: https://github.com/ceph/ceph/commit/826460338453f7d6749428f6b6a2db04b75e4df6
* 16.2.11+: https://github.com/ceph/ceph/commit/ca8f77d6a7fa361328a942e3f37c81dd9577d4de
* etc

In our case we downgraded from 16.2.13 -> 16.2.10 so everything seems to work as intended with rook 1.7.11.

**Comment by voarsh2** [comment]
Hmm. Yeah, I have this issue. I can't get objectstore setup.

**Comment by evanrich** [comment]
just deployed a cephobjectstore into my setup as well, have this issue as well.  Object store is created and running, but can't see it with latest rook-ceph operator configured. (17.2.6)

**Comment by parth-gr** [comment]
@avanthakkar any update?

**Comment by avanthakkar** [comment]
Sorry I'm not actively working on this issue. I'm busy with some other Ceph tasks, so unassigning this task for now if someone wants to take over।

**Comment by sirtoobii** [comment]
This issue is also present in cephadm deployments (ceph 17.2.6). Apparently there used to be an `ceph dashboard set-rgw-api-host HOST` command?

**Comment by os14** [comment]
having the same issue on cluster with calico

**Comment by dpeckett** [comment]
Given the issues around implementing a more complex fix, how about we modify the mgr client to attempt to preferentially use the hostname but fallback to the address.

**Comment by daniel-tedra** [comment]
I have this issue too, mgr is looking for ceph-mon DNS record to set the rgw credentials and it fails. is there any workaround to solve this?

**Comment by dpeckett** [comment]
If you promise not to rely on my published images and instead build your own  (I'll probably add more patches in the future that break things) it's pretty easy to revert the change that's causing all this trouble:

https://github.com/gpu-ninja/ceph-images

**Comment by daniel-tedra** [comment]
> If you promise not to rely on my published images and instead build your own (I'll probably add more patches in the future that break things) it's pretty easy to revert the change that's causing all this trouble:
> 
> https://github.com/gpu-ninja/ceph-images

Thank you very much mate, but I am not a developer, and I would not like to keep my custom images/repositories. 
By the way, now I'm facing that radosgw-admin not providing a method to create buckets...very disappointing.

**Comment by wedobetter** [comment]
Upon upgrading `17.2.6 -> 18.2.0` I am having the same problem:

```bash
requests.exceptions.ConnectionError: HTTPConnectionPool(host='k8s-node3', port=8080): Max retries exceeded with url: /admin/metadata/user?myself (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f722a349710>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

Note the host `k8s-node3` is my physical Kubernetes node which is obv not listening on that port. 

This is the service it should be connecting to:
```bash
rook-ceph-rgw-ceph-objectstore   ClusterIP   10.110.66.182    <none>        80/TCP              120d
```

**Comment by travisn** [comment]
@avanthakkar Could you summarize your viewpoint on this issue? We really need help from the Ceph dashboard team on this. Thanks!

**Comment by pisko1979** [comment]
Hi all

any news on this? 
we have same problem after upgrade rook (from 1.8 to 1.9.13) and ceph (from 16.2.7 to 16.2.13). 
dashboard uses node address and not k8s service

debug 2023-08-23T10:39:17.561+0000 7fe1637e1700  0 [dashboard ERROR rest_client] RGW REST API failed GET, connection error (url=http://**k8s-lab-s1**:8080/admin/metadata/user?myself): [errno: 111] Connection refused
debug 2023-08-23T10:39:17.561+0000 7fe1637e1700  0 [dashboard ERROR rgw_client] RGW REST API cannot be reached: Connection refused [errno 111]. Please check your configuration and that the API endpoint is accessible

thanks

**Comment by rajeshvijayarajan** [comment]
I have run into the same problem. My workaround (obviously not a permanent solution) was to go to the /etc/hosts of the mgr container, and then create an entry of the following form:
<cluster-ip of rook-ceph-rgw-xxx pod> <hostname-of-k8shost-its-trying-to-get-to>

A proper fix is very much appreciated.

**Comment by mkhpalm** [comment]
It looks like a proper fix is coming down from ceph. Should be included with the release of pacific v16.2.15, quincy v17.2.7, and reef v18.2.1

https://tracker.ceph.com/issues/62396

**Comment by jhoblitt** [comment]
I seems like we need to figure out how to improve communication between the rook and ceph core community. This isn't a new to rook users bug and I'm fairly sure it was reported in other redmine issues.

**Comment by rkachach** [comment]
As of my initial investigation I found that several issues in fact are related to running the `radosgw-admin` from the mgr pod and not being able to reach the monitors. When this happens normally we end up with logs such as:

`unable to get monitor info from DNS SRV with service name: ceph-mon
`

The command `radosgw-admin` internally is implemented as (`mgr_module.py`):

```
    @API.expose
    def send_rgwadmin_command(self, args: List[str],
                              stdout_as_json: bool = True) -> Tuple[int, Union[str, dict], str]:
        try:
            cmd = [
                    'radosgw-admin',
                    '-c', str(self.get_ceph_conf_path()),
                    '-k', str(self.get_ceph_option('keyring')),
                    '-n', f'mgr.{self.get_mgr_id()}',
                ] + args
```

From a debugging session it end up calling cmds like:

`radosgw-admin -c /var/lib/ceph/mgr/ceph-a/ceph.conf -k /etc/ceph/keyring-store/keyring -n mgr.a zonegroup list
`

So basically it's looking for a ceph conf file in `/etc/ceph/ceph.conf` which doesn't exist on the mgr pod. A simple workaround for this is to use the rook config override feature to provide a custom ceph configuration. For that user have to run the following cmd:

`kubectl -n rook-ceph edit configmap rook-config-override`

And then Introduce a simple ceph conf indicating the mon ip, i.e:

```
apiVersion: v1
data:
  config: |
    [global]
    mon_host = <ceph-mon-ip>:<ceph-mon-port>
```

This information can be found either in the file `/etc/ceph/ceph.conf` from the toolbox or by running:

`kubectl get configmap -n rook-ceph rook-ceph-mon-endpoints -o jsonpath="{['data']['data']}"`

**NOTE:**

Please, in case of using ceph.conf from the toolbox copy just the `mon_host` (without any key/kering info).

**Comment by rkachach** [comment]
The PR https://github.com/rook/rook/pull/13256 should fix the `radosgw-admin` issue

**Comment by Mihai-CMM** [comment]
I still see this issue on ceph 18.2 and  rook/ceph:v1.12.8-4.gc6f573ba8. Are there any new developments made here?

**Comment by rkachach** [comment]
@Mihai-CMM `18.2.0` doesn't contain any of these fixes. The should come with `v18.2.1` as part of the new ceph reef release.

**Comment by xavi-clovr** [comment]
Same here. I'm new in the Rook and Ceph world but at least I could really see how the credentials in radosgw for `dashboard` were correctly set and were matching with the Ceph credentials defined in the keyring and in the Ceph Dashboard (from the ceph commands).
However Dashboard is unable to access to it. Also tried with multiple API endpoints from the Dashboard Swagger and really got the same bad responses that I see in the logs (unable to access with Errno 111, as someone pointed out in this thread before).
In my opinion seems that Dashboard is not pointing to the correct site where my object store GW is exposed. Is there any way to fix that? Where is defined the config that Dashboard uses to get each Object GW?

**Comment by ivanovpavel1983** [comment]
Release 1.12.9 solved my problem with the dashboard and object gateway. Thank you.

**Comment by Mihai-CMM** [comment]
What ceph version? I didn't had any issues with all rook versions but i am stuck on ceph 16

**Comment by Mihai-CMM** [comment]
Ok this is still not solved :on rook 12.9 and ceph 18.2

**Comment by rspier** [comment]
I believe it's fixed in ceph 18.2.1…   supposedly coming soon

**Comment by ivanovpavel1983** [comment]
I reset the "rgw" parameters, delete the user dashboard-admin, restart operator 1.12.9. 
After that everything works:
![ceph](https://github.com/rook/rook/assets/5180093/f9e9738b-a019-49ef-86c4-6bb8f02013b3)

**Comment by Mihai-CMM** [comment]
Yeey - I tried on rook 13 and ceph 18.2.1 and works out of the box :) (on a fresh install)
Thanks

**Comment by rajeshvijayarajan** [comment]
I only performed minor upgrades on my cluster. Upgraded Rook to v1.12.10 and the Ceph cluster to v.17.2.7. I can confirm the issue is resolved.

**Comment by rkachach** [comment]
This issue should be fixed on `Ceph v18.2.1` which comes by default with `Rook v 1.13.1`

**Comment by bumarcell** [comment]
I'm running rook v1.12.10 and Ceph v16.2.14 and getting the following error when trying to reach RGW from the dashboard:
```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='ceph-host', port=8080): Max retries exceeded with url: /admin/metadata/user?myself (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0a63840cc0>: Failed to establish a new connection: [Errno 111] Connection refused',))
```
I already ran `ceph dashboard set-rgw-credentials`and got positive output.
The host `ceph-host` is the name of the node on which the rgw pod is running [here](https://docs.ceph.com/en/pacific/mgr/orchestrator/#definition-of-terms)
I believe the problem is with the port 8080, which I don't know where it's coming from. It should default to 80 and that's the port on the svc created by the CephObjectStore.

**Comment by rkachach** [comment]
@bumarcell it seems that the issue you are facing is different from the one reported on this issue (already closed BTW). I'll encourage first checking if newest versions of rook/ceph to see if it solves your issue otherwise please open a new issue describing in details your env and how to reproduce the issue.

**Comment by voarsh2** [comment]
> I only performed minor upgrades on my cluster. Upgraded Rook to v1.12.10 and the Ceph cluster to v.17.2.7. I can confirm the issue is resolved.

I'm on v12.10.

Am I missing something? Do I need to do something? ObjectStore pod is running, Ceph sees it as ObjectStore as running (pool is healthy, but dashboard still says it can't connect........

**Comment by rkachach** [comment]
> > I only performed minor upgrades on my cluster. Upgraded Rook to v1.12.10 and the Ceph cluster to v.17.2.7. I can confirm the issue is resolved.
> 
> I'm on v12.10.
> 
> Am I missing something? Do I need to do something? ObjectStore pod is running, Ceph sees Object Gateway as running (pool is healthy), but dashboard still says it can't connect........

https://github.com/rook/rook/issues/9660#issuecomment-1880837373

And once on v18.2.1 plz read carefully through https://github.com/rook/rook/issues/13527
